export const highEndSites = [
   "Lv",
   "Dior",
   "Fendi",
   "Loropiana",
   "Brunello",
   "Hermes",
   "Jacquemus",
];

export const coreSourcingSites = [
   "Farfetch",
   "Cettire",
   "Prada",
   "YSL",
   "Burberry",
   "Celine",
   "Balenciaga",
   "Miumiu",
   "Bottega",
   "Maisonmargiela",
   "Loewe",
   "Stone",
   "Lemaire",
   "Ferragamo",
   "Dolce",
   "Therow",
   "Maxmara",
   "Moncler",
   "Alexander",
   "Givenchy",
   "Sandro",
   "Tods",
   "Valentino",
   "Acne",
   "Herno",
   "Thombrowne",
   "Tomford",
   "Ami",
   "Jilsander",
   "Ourlegacy",
   "Polene",
   "Rickowens",
   "Apc",
   "Chloe",
   "Gucci",
   "Isabelmarant",
   "Longchamp",
   "Maisonkitsune",
   "Maje",
];

export const plans = [
   {
      name: "Boutique",
      price: "월 55만원",
      sixMonthPrice: "313만원",
      annualPrice: "594만원",
      priceNote: "VAT 포함, 서버 비용 포함",
      description:
         "공식 홈페이지가 아닌 대형 플랫폼을 대상으로 상품등록 및 재고관리를 이용할 수 있는 플랜",
      features: [
         "대형 플랫폼 사이트 1개",
         "월 요청 처리량 10만건",
         "초기 셋팅 110만원",
         "추가 비용 : 호스팅 연동 11만원",
      ],
      recommended: false,
   },
   {
      name: "Basic",
      price: "월 19만원",
      sixMonthPrice: "108만원",
      annualPrice: "205만원",
      priceNote: "VAT 포함, 서버 비용 포함",
      description: "다음 플랜으로 가기 위한, 플로우머스를 맛보기로 경험할 수 있는 가성비 모델",
      features: [
         "핵심 소싱 사이트 2개",
         "월 요청 처리량 5천건",
         "하이엔드 사이트 0개",
         "추가 비용 : 호스팅 연동 11만원",
      ],
      recommended: false,
   },
   {
      name: "Pro",
      price: "월 49만원",
      sixMonthPrice: "279만원",
      annualPrice: "529만원",
      priceNote: "VAT 포함, 서버 비용 포함",
      description: "명품 구매대행과 플랫폼 운영 및 다중 사이트를 효율적으로 관리할 수 있습니다.",
      features: [
         "핵심 소싱 사이트 8개",
         "월 요청 처리량 5만건",
         "하이엔드 사이트 2개",
         "호스팅 연동 무료셋팅",
      ],
      recommended: true,
   },
   {
      name: "Enterprise",
      price: "월 110만원부터",
      sixMonthPrice: "627만원부터",
      annualPrice: "1,188만원부터",
      priceNote: "VAT 포함, 서버 비용 포함",
      description: "모든 하이엔드 사이트와 대규모 상품등록이 가능하며 매출 영향에 최적화로 운영이 가능합니다.",
      features: [
         "핵심 소싱 사이트 40개 이상",
         "월 요청 처리량 20만건 이상",
         "하이엔드 사이트 전체 제공",
         "호스팅 다중 연동 무료셋팅",
      ],
      recommended: false,
   },
];

export const comparison = [
   ["월 이용료", "55만원", "19만원", "49만원", "110만원부터"],
   ["VAT", "포함", "포함", "포함", "포함"],
   ["서버 비용", "포함", "포함", "포함", "포함"],
   ["대상 사이트", "대형 부티크 플랫폼", "공식 홈페이지", "공식 홈페이지", "전체+맞춤"],
   ["플랫폼 사이트", "1개", "-", "-", "요청 가능"],
   ["핵심 소싱 사이트", "-", "2개", "8개", "40개 이상"],
   ["하이엔드 사이트", "-", "0개", "2개", "전체 제공"],
   ["월 요청 처리량", "10만건", "5천건", "5만건", "20만건 이상"],
   ["지원 플랫폼", "전체", "전체", "전체", "전체+요청 가능"],
   ["상품 자동 수집", "O", "O", "O", "O"],
   ["상품 자동 등록", "O", "O", "O", "O"],
   ["재고관리 요청", "가능", "가능", "가능", "우선 처리"],
   ["수집 예약", "원클릭 예약", "원클릭 예약", "원클릭 예약", "우선 처리"],
   ["SEO 상품명 최적화", "O", "O", "O", "O"],
   ["SEO 상품 상세 최적화", "O", "O", "O", "O"],
   ["마진/치환 설정", "O", "O", "O", "O"],
   ["초기 셋팅", "110만원(VAT 포함)", "11만원(VAT 포함)", "무료", "무료"],
   ["호스팅 연동", "11만원(VAT 포함)", "11만원(VAT 포함)", "무료", "무료"],
   ["24시간 실시간 채팅", "O", "O", "O", "우선 지원"],
   ["사이트 추가 요청", "가능", "상담", "유료", "무료"],
   ["플랫폼 구축 요청", "상담", "상담", "유료", "무료"],
];
