INSERT INTO mapping (
  site,
  "siteUrl",
  "categoryName",
  "godoMallCategoryName",
  "godoMallCategoryCode",
  designers,
  "afterDesigners",
  "customId",
  "accountPlatform"
) VALUES
('Acne', 'https://www.acnestudios.com/nl/en/man/belts/', '남성 - SHOES & ACCESSORIES - Belts', '패션잡화>벨트>남성벨트>캐주얼벨트', '50003989', NULL, NULL, 'bcm499', 'smartstore_2'),
('Acne', 'https://www.acnestudios.com/nl/en/woman/outerwear/', '여성 - CLOTHING - Outerwear', '패션의류>여성의류>아우터>재킷', '50021360', NULL, NULL, 'bcm499', 'smartstore_2'),
('Acne', 'https://www.acnestudios.com/nl/en/woman/trousers/', '여성 - CLOTHING - Trousers', '패션의류>여성의류>바지', '50000810', NULL, NULL, 'bcm499', 'smartstore_2'),
('Acne', 'https://www.acnestudios.com/nl/en/woman/t-shirts/', '여성 - CLOTHING - T-shirts', '패션의류>여성의류>티셔츠', '50000803', NULL, NULL, 'bcm499', 'smartstore_2'),
('Acne', 'https://www.acnestudios.com/nl/en/woman/knitwear/', '여성 - CLOTHING - Knitwear', '패션의류>여성의류>니트>풀오버', '50021299', NULL, NULL, 'bcm499', 'smartstore_2'),
('Acne', 'https://www.acnestudios.com/nl/en/woman/suit-jackets/', '여성 - CLOTHING - Suit Jackets', '패션의류>여성의류>아우터>재킷', '50021360', NULL, NULL, 'bcm499', 'smartstore_2'),
('Acne', 'https://www.acnestudios.com/nl/en/woman/dresses/', '여성 - CLOTHING - Dresses', '패션의류>여성의류>원피스', '50000807', NULL, NULL, 'bcm499', 'smartstore_2'),
('Acne', 'https://www.acnestudios.com/nl/en/woman/shirts-and-blouses/', '여성 - CLOTHING - Shirts & Blouses', '패션의류>여성의류>블라우스/셔츠', '50000804', NULL, NULL, 'bcm499', 'smartstore_2'),
('Acne', 'https://www.acnestudios.com/nl/en/woman/skirts/', '여성 - CLOTHING - Skirts', '패션의류>여성의류>스커트', '50000808', NULL, NULL, 'bcm499', 'smartstore_2'),
('Acne', 'https://www.acnestudios.com/nl/en/woman/shorts/', '여성 - CLOTHING - Shorts', '패션의류>여성의류>바지', '50000810', NULL, NULL, 'bcm499', 'smartstore_2'),
('Acne', 'https://www.acnestudios.com/nl/en/scarves/', '여성 - SHOES & ACCESSORIES - Scarves', '패션잡화>패션소품>스카프>롱', '50004010', NULL, NULL, 'bcm499', 'smartstore_2'),
('Acne', 'https://www.acnestudios.com/nl/en/woman/hats/', '여성 - SHOES & ACCESSORIES - Hats', '패션잡화>모자>사파리모자', '50000546', NULL, NULL, 'bcm499', 'smartstore_2'),
('Acne', 'https://www.acnestudios.com/nl/en/woman/eyewear/', '여성 - SHOES & ACCESSORIES - Eyewear', '패션잡화>선글라스/안경테>선글라스', '50000554', NULL, NULL, 'bcm499', 'smartstore_2'),
('Acne', 'https://www.acnestudios.com/nl/en/woman/belts/', '여성 - SHOES & ACCESSORIES - Belts', '패션잡화>벨트>여성벨트', '50000539', NULL, NULL, 'bcm499', 'smartstore_2'),
('Acne', 'https://www.acnestudios.com/nl/en/man/outerwear/', '남성 - CLOTHING - Outerwear', '패션의류>남성의류>아우터>재킷', '50021640', NULL, NULL, 'bcm499', 'smartstore_2'),
('Acne', 'https://www.acnestudios.com/nl/en/man/trousers/', '남성 - CLOTHING - Trousers', '패션의류>남성의류>바지', '50000836', NULL, NULL, 'bcm499', 'smartstore_2'),
('Acne', 'https://www.acnestudios.com/nl/en/man/knitwear/', '남성 - CLOTHING - Knitwear', '패션의류>남성의류>니트>풀오버', '50021579', NULL, NULL, 'bcm499', 'smartstore_2'),
('Acne', 'https://www.acnestudios.com/nl/en/man/t-shirts/', '남성 - CLOTHING - T-shirts', '패션의류>남성의류>티셔츠', '50000830', NULL, NULL, 'bcm499', 'smartstore_2'),
('Acne', 'https://www.acnestudios.com/nl/en/man/shirts/', '남성 - CLOTHING - Shirts', '패션의류>남성의류>셔츠/남방', '50000833', NULL, NULL, 'bcm499', 'smartstore_2'),
('Acne', 'https://www.acnestudios.com/nl/en/man/suit-jackets/', '남성 - CLOTHING - Suit Jackets', '패션의류>남성의류>아우터>재킷', '50021640', NULL, NULL, 'bcm499', 'smartstore_2'),
('Acne', 'https://www.acnestudios.com/nl/en/man/shorts/', '남성 - CLOTHING - Shorts', '패션의류>남성의류>바지', '50000836', NULL, NULL, 'bcm499', 'smartstore_2'),
('Acne', 'https://www.acnestudios.com/nl/en/scarves/', '남성 - SHOES & ACCESSORIES - Scarves', '패션잡화>패션소품>스카프>롱', '50004010', NULL, NULL, 'bcm499', 'smartstore_2'),
('Acne', 'https://www.acnestudios.com/nl/en/man/hats/', '남성 - SHOES & ACCESSORIES - Hats', '패션잡화>모자>사파리모자', '50000546', NULL, NULL, 'bcm499', 'smartstore_2'),
('Acne', 'https://www.acnestudios.com/nl/en/man/eyewear/', '남성 - SHOES & ACCESSORIES - Eyewear', '패션잡화>선글라스/안경테>선글라스', '50000554', NULL, NULL, 'bcm499', 'smartstore_2'),
('Acne', 'https://www.acnestudios.com/nl/en/bags/top-handle-bags/', '가방 - TYPES - Top Handle Bags', '패션잡화>여성가방>토트백', '50000640', NULL, NULL, 'bcm499', 'smartstore_2'),
('Acne', 'https://www.acnestudios.com/nl/en/bags/shoulder-bags/', '가방 - TYPES - Shoulder Bags', '패션잡화>여성가방>숄더백', '50000639', NULL, NULL, 'bcm499', 'smartstore_2'),
('Acne', 'https://www.acnestudios.com/nl/en/bags/backpack/', '가방 - TYPES - Backpacks', '패션잡화>여성가방>백팩', '50000644', NULL, NULL, 'bcm499', 'smartstore_2'),
('Acne', 'https://www.acnestudios.com/nl/en/bags/crossbody/', '가방 - TYPES - Crossbody Bags', '패션잡화>여성가방>크로스백', '50000641', NULL, NULL, 'bcm499', 'smartstore_2'),
('Acne', 'https://www.acnestudios.com/nl/en/bags/totes/', '가방 - TYPES - Totes', '패션잡화>여성가방>토트백', '50000640', NULL, NULL, 'bcm499', 'smartstore_2');
