INSERT INTO mapping (
  site,
  "siteUrl",
  "categoryName",
  "godoMallCategoryName",
  "godoMallCategoryCode",
  designers,
  "afterDesigners",
  "customId",
  "accountPlatform"
) VALUES
('Alexander', 'https://www.alexandermcqueen.com/en-nl/ca/women/ready-to-wear/tailoring', 'WOMEN - Ready-to-Wear - Tailoring', '패션의류>여성의류>정장세트', '50000816', NULL, NULL, 'bcm499', 'smartstore_2'),
('Alexander', 'https://www.alexandermcqueen.com/en-nl/ca/women/ready-to-wear/coats-and-outerwear', 'WOMEN - Ready-to-Wear - Coats and Outerwear', '패션의류>여성의류>아우터>재킷', '50021360', NULL, NULL, 'bcm499', 'smartstore_2'),
('Alexander', 'https://www.alexandermcqueen.com/en-nl/ca/women/ready-to-wear/jackets', 'WOMEN - Ready-to-Wear - Jackets', '패션의류>여성의류>아우터>재킷', '50021360', NULL, NULL, 'bcm499', 'smartstore_2'),
('Alexander', 'https://www.alexandermcqueen.com/en-nl/ca/women/ready-to-wear/dresses', 'WOMEN - Ready-to-Wear - Dresses', '패션의류>여성의류>원피스', '50000807', NULL, NULL, 'bcm499', 'smartstore_2'),
('Alexander', 'https://www.alexandermcqueen.com/en-nl/ca/women/ready-to-wear/knitwear', 'WOMEN - Ready-to-Wear - Knitwear', '패션의류>여성의류>니트>풀오버', '50021299', NULL, NULL, 'bcm499', 'smartstore_2'),
('Alexander', 'https://www.alexandermcqueen.com/en-nl/ca/women/ready-to-wear/tops-and-shirts', 'WOMEN - Ready-to-Wear - Tops and Shirts', '패션의류>여성의류>블라우스/셔츠', '50000804', NULL, NULL, 'bcm499', 'smartstore_2'),
('Alexander', 'https://www.alexandermcqueen.com/en-nl/ca/women/ready-to-wear/t-shirts-and-sweatshirts', 'WOMEN - Ready-to-Wear - T-Shirts and Sweatshirts', '패션의류>여성의류>티셔츠', '50000803', NULL, NULL, 'bcm499', 'smartstore_2'),
('Alexander', 'https://www.alexandermcqueen.com/en-nl/ca/women/ready-to-wear/skirts', 'WOMEN - Ready-to-Wear - Skirts', '패션의류>여성의류>스커트', '50000808', NULL, NULL, 'bcm499', 'smartstore_2'),
('Alexander', 'https://www.alexandermcqueen.com/en-nl/ca/women/ready-to-wear/trousers', 'WOMEN - Ready-to-Wear - Trousers', '패션의류>여성의류>바지', '50000810', NULL, NULL, 'bcm499', 'smartstore_2'),
('Alexander', 'https://www.alexandermcqueen.com/en-nl/ca/women/handbags/clutches', 'WOMEN - Handbags - Clutches', '패션잡화>여성가방>클러치백', '50000642', NULL, NULL, 'bcm499', 'smartstore_2'),
('Alexander', 'https://www.alexandermcqueen.com/en-nl/ca/women/handbags/shoulder-bags', 'WOMEN - Handbags - Shoulder Bags', '패션잡화>여성가방>숄더백', '50000639', NULL, NULL, 'bcm499', 'smartstore_2'),
('Alexander', 'https://www.alexandermcqueen.com/en-nl/ca/women/handbags/crossbody-bags', 'WOMEN - Handbags - Crossbody Bags', '패션잡화>여성가방>크로스백', '50000641', NULL, NULL, 'bcm499', 'smartstore_2'),
('Alexander', 'https://www.alexandermcqueen.com/en-nl/ca/women/handbags/top-handles', 'WOMEN - Handbags - Top Handles', '패션잡화>여성가방>토트백', '50000640', NULL, NULL, 'bcm499', 'smartstore_2'),
('Alexander', 'https://www.alexandermcqueen.com/en-nl/ca/women/shoes/sandals-and-slides', 'WOMEN - Shoes - Sandals and Slides', '패션잡화>여성신발>샌들>스트랩샌들', '50003842', NULL, NULL, 'bcm499', 'smartstore_2'),
('Alexander', 'https://www.alexandermcqueen.com/en-nl/ca/women/shoes/sneakers', 'WOMEN - Shoes - Sneakers', '패션잡화>여성신발>단화>스니커즈', '50003822', NULL, NULL, 'bcm499', 'smartstore_2'),
('Alexander', 'https://www.alexandermcqueen.com/en-nl/ca/women/shoes/pumps', 'WOMEN - Shoes - Pumps and Heels', '패션잡화>여성신발>힐/펌프스>펌프스', '50003830', NULL, NULL, 'bcm499', 'smartstore_2'),
('Alexander', 'https://www.alexandermcqueen.com/en-nl/ca/women/shoes/flat-shoes', 'WOMEN - Shoes - Flat Shoes', '패션잡화>여성신발>단화>플랫', '50003817', NULL, NULL, 'bcm499', 'smartstore_2'),
('Alexander', 'https://www.alexandermcqueen.com/en-nl/ca/women/shoes/boots', 'WOMEN - Shoes - Boots', '패션잡화>여성신발>부츠>앵클/숏부츠', '50004191', NULL, NULL, 'bcm499', 'smartstore_2'),
('Alexander', 'https://www.alexandermcqueen.com/en-nl/ca/women/shoes/boxe-sneaker', 'WOMEN - Shoes - Boxe Sneaker', '패션잡화>여성신발>단화>스니커즈', '50003822', NULL, NULL, 'bcm499', 'smartstore_2'),
('Alexander', 'https://www.alexandermcqueen.com/en-nl/ca/women/shoes/ec1-sneaker', 'WOMEN - Shoes - EC1 Sneaker', '패션잡화>여성신발>단화>스니커즈', '50003822', NULL, NULL, 'bcm499', 'smartstore_2'),
('Alexander', 'https://www.alexandermcqueen.com/en-nl/ca/women/shoes/oversized-sneaker', 'WOMEN - Shoes - Oversized Sneaker', '패션잡화>여성신발>단화>스니커즈', '50003822', NULL, NULL, 'bcm499', 'smartstore_2'),
('Alexander', 'https://www.alexandermcqueen.com/en-nl/ca/women/shoes/tread-slick', 'WOMEN - Shoes - Tread Slick', '패션잡화>여성신발>단화>스니커즈', '50003822', NULL, NULL, 'bcm499', 'smartstore_2'),
('Alexander', 'https://www.alexandermcqueen.com/en-nl/ca/women/accessories/sunglasses', 'WOMEN - Accessories - Sunglasses', '패션잡화>선글라스/안경테>선글라스', '50000554', NULL, NULL, 'bcm499', 'smartstore_2'),
('Alexander', 'https://www.alexandermcqueen.com/en-nl/ca/women/accessories/scarves', 'WOMEN - Accessories - Scarves', '패션잡화>패션소품>스카프>롱', '50004010', NULL, NULL, 'bcm499', 'smartstore_2'),
('Alexander', 'https://www.alexandermcqueen.com/en-nl/ca/women/accessories/belts', 'WOMEN - Accessories - Belts', '패션잡화>벨트>여성벨트', '50000539', NULL, NULL, 'bcm499', 'smartstore_2'),
('Alexander', 'https://www.alexandermcqueen.com/en-nl/ca/women/jewellery/necklaces-and-pendants', 'WOMEN - Jewellery - Necklaces and Pendants', '패션잡화>주얼리>목걸이>패션목걸이', '50004174', NULL, NULL, 'bcm499', 'smartstore_2'),
('Alexander', 'https://www.alexandermcqueen.com/en-nl/ca/women/jewellery/earrings', 'WOMEN - Jewellery - Earrings', '패션잡화>주얼리>귀걸이>패션귀걸이', '50004164', NULL, NULL, 'bcm499', 'smartstore_2'),
('Alexander', 'https://www.alexandermcqueen.com/en-nl/ca/women/jewellery/bracelets', 'WOMEN - Jewellery - Bracelets', '패션잡화>주얼리>팔찌>패션팔찌', '50004194', NULL, NULL, 'bcm499', 'smartstore_2'),
('Alexander', 'https://www.alexandermcqueen.com/en-nl/ca/women/jewellery/rings', 'WOMEN - Jewellery - Rings', '패션잡화>주얼리>반지>패션반지', '50004155', NULL, NULL, 'bcm499', 'smartstore_2'),
('Alexander', 'https://www.alexandermcqueen.com/en-nl/ca/men/ready-to-wear/tailoring', 'MEN - Ready-to-Wear - Tailoring', '패션의류>남성의류>정장세트', '50000840', NULL, NULL, 'bcm499', 'smartstore_2'),
('Alexander', 'https://www.alexandermcqueen.com/en-nl/ca/men/ready-to-wear/coats-and-outerwear', 'MEN - Ready-to-Wear - Coats and Outerwear', '패션의류>남성의류>아우터>재킷', '50021640', NULL, NULL, 'bcm499', 'smartstore_2'),
('Alexander', 'https://www.alexandermcqueen.com/en-nl/ca/men/ready-to-wear/jackets', 'MEN - Ready-to-Wear - Jackets', '패션의류>남성의류>아우터>재킷', '50021640', NULL, NULL, 'bcm499', 'smartstore_2'),
('Alexander', 'https://www.alexandermcqueen.com/en-nl/ca/men/ready-to-wear/knitwear', 'MEN - Ready-to-Wear - Knitwear', '패션의류>남성의류>니트>풀오버', '50021579', NULL, NULL, 'bcm499', 'smartstore_2'),
('Alexander', 'https://www.alexandermcqueen.com/en-nl/ca/men/ready-to-wear/t-shirts-and-sweatshirts', 'MEN - Ready-to-Wear - T-Shirts and Sweatshirts', '패션의류>남성의류>티셔츠', '50000830', NULL, NULL, 'bcm499', 'smartstore_2'),
('Alexander', 'https://www.alexandermcqueen.com/en-nl/ca/men/ready-to-wear/shirts', 'MEN - Ready-to-Wear - Shirts', '패션의류>남성의류>셔츠/남방', '50000833', NULL, NULL, 'bcm499', 'smartstore_2'),
('Alexander', 'https://www.alexandermcqueen.com/en-nl/ca/men/ready-to-wear/trousers', 'MEN - Ready-to-Wear - Trousers', '패션의류>남성의류>바지', '50000836', NULL, NULL, 'bcm499', 'smartstore_2'),
('Alexander', 'https://www.alexandermcqueen.com/en-nl/ca/the-sling', 'MEN - Bags - T-Bar Sling', '패션잡화>남성가방>힙색/슬링백', '50000652', NULL, NULL, 'bcm499', 'smartstore_2'),
('Alexander', 'https://www.alexandermcqueen.com/en-nl/ca/men/shoes/sandals-and-slides', 'MEN - Shoes - Sandals and Slides', '패션잡화>남성신발>샌들', '50000789', NULL, NULL, 'bcm499', 'smartstore_2'),
('Alexander', 'https://www.alexandermcqueen.com/en-nl/ca/men/shoes/sneakers', 'MEN - Shoes - Sneakers', '패션잡화>남성신발>스니커즈', '50000788', NULL, NULL, 'bcm499', 'smartstore_2'),
('Alexander', 'https://www.alexandermcqueen.com/en-nl/ca/men/shoes/loafers-and-lace-ups', 'MEN - Shoes - Loafers and Lace Ups', '패션잡화>남성신발>구두', '50000787', NULL, NULL, 'bcm499', 'smartstore_2'),
('Alexander', 'https://www.alexandermcqueen.com/en-nl/ca/men/shoes/boots', 'MEN - Shoes - Boots', '패션잡화>남성신발>부츠>앵클/숏부츠', '50021999', NULL, NULL, 'bcm499', 'smartstore_2'),
('Alexander', 'https://www.alexandermcqueen.com/en-nl/ca/men/shoes/boxe-sneaker', 'MEN - Shoes - Boxe Sneaker', '패션잡화>남성신발>스니커즈', '50000788', NULL, NULL, 'bcm499', 'smartstore_2'),
('Alexander', 'https://www.alexandermcqueen.com/en-nl/ca/men/shoes/ec1-sneakers', 'MEN - Shoes - EC1 Sneaker', '패션잡화>남성신발>스니커즈', '50000788', NULL, NULL, 'bcm499', 'smartstore_2'),
('Alexander', 'https://www.alexandermcqueen.com/en-nl/ca/men/shoes/oversized-sneaker', 'MEN - Shoes - Oversized Sneaker', '패션잡화>남성신발>스니커즈', '50000788', NULL, NULL, 'bcm499', 'smartstore_2'),
('Alexander', 'https://www.alexandermcqueen.com/en-nl/ca/men/accessories/sunglasses', 'MEN - Accessories - Sunglasses', '패션잡화>선글라스/안경테>선글라스', '50000554', NULL, NULL, 'bcm499', 'smartstore_2'),
('Alexander', 'https://www.alexandermcqueen.com/en-nl/ca/men/accessories/scarves', 'MEN - Accessories - Scarves', '패션잡화>패션소품>스카프>롱', '50004010', NULL, NULL, 'bcm499', 'smartstore_2'),
('Alexander', 'https://www.alexandermcqueen.com/en-nl/ca/men/accessories/wallets-and-cardholders', 'MEN - Accessories - Wallets and Cardholders', '패션잡화>지갑>카드/명함지갑', '50000662', NULL, NULL, 'bcm499', 'smartstore_2'),
('Alexander', 'https://www.alexandermcqueen.com/en-nl/ca/men/accessories/ties', 'MEN - Accessories - Ties', '패션잡화>패션소품>넥타이>기본넥타이', '50004014', NULL, NULL, 'bcm499', 'smartstore_2'),
('Alexander', 'https://www.alexandermcqueen.com/en-nl/ca/men/accessories/belts', 'MEN - Accessories - Belts', '패션잡화>벨트>남성벨트>캐주얼벨트', '50003989', NULL, NULL, 'bcm499', 'smartstore_2'),
('Alexander', 'https://www.alexandermcqueen.com/en-nl/ca/men/jewellery/necklaces', 'MEN - Jewellery - Necklaces', '패션잡화>주얼리>목걸이>패션목걸이', '50004174', NULL, NULL, 'bcm499', 'smartstore_2'),
('Alexander', 'https://www.alexandermcqueen.com/en-nl/ca/men/jewellery/bracelets', 'MEN - Jewellery - Bracelets', '패션잡화>주얼리>팔찌>패션팔찌', '50004194', NULL, NULL, 'bcm499', 'smartstore_2'),
('Alexander', 'https://www.alexandermcqueen.com/en-nl/ca/men/jewellery/rings', 'MEN - Jewellery - Rings', '패션잡화>주얼리>반지>패션반지', '50004155', NULL, NULL, 'bcm499', 'smartstore_2');
