INSERT INTO mapping (
  site,
  "siteUrl",
  "categoryName",
  "godoMallCategoryName",
  "godoMallCategoryCode",
  designers,
  "afterDesigners",
  "customId",
  "accountPlatform"
) VALUES
('Ami', 'https://www.amiparis.com/en-nl/collections/women-jackets-and-coats', 'WOMEN - READY TO WEAR - Coats & Jackets', '패션의류>여성의류>아우터>재킷', '50021360', NULL, NULL, 'bcm499', 'smartstore_2'),
('Ami', 'https://www.amiparis.com/en-nl/collections/women-sweaters-and-cardigans', 'WOMEN - READY TO WEAR - Sweaters & Cardigans', '패션의류>여성의류>니트>풀오버', '50021299', NULL, NULL, 'bcm499', 'smartstore_2'),
('Ami', 'https://www.amiparis.com/en-nl/collections/women-t-shirts-and-tops', 'WOMEN - READY TO WEAR - T-shirts & Tops', '패션의류>여성의류>티셔츠', '50000803', NULL, NULL, 'bcm499', 'smartstore_2'),
('Ami', 'https://www.amiparis.com/en-nl/collections/women-dresses-and-jumpsuits', 'WOMEN - READY TO WEAR - Dresses & Jumpsuits', '패션의류>여성의류>원피스', '50000807', NULL, NULL, 'bcm499', 'smartstore_2'),
('Ami', 'https://www.amiparis.com/en-nl/collections/women-shirts', 'WOMEN - READY TO WEAR - Shirts', '패션의류>여성의류>블라우스/셔츠', '50000804', NULL, NULL, 'bcm499', 'smartstore_2'),
('Ami', 'https://www.amiparis.com/en-nl/collections/women-shorts-and-skirts', 'WOMEN - READY TO WEAR - Shorts & Skirts', '패션의류>여성의류>스커트', '50000808', NULL, NULL, 'bcm499', 'smartstore_2'),
('Ami', 'https://www.amiparis.com/en-nl/collections/women-pants', 'WOMEN - READY TO WEAR - Trousers', '패션의류>여성의류>바지', '50000810', NULL, NULL, 'bcm499', 'smartstore_2'),
('Ami', 'https://www.amiparis.com/en-nl/collections/women-belts', 'WOMEN - ACCESSORIES - Belts', '패션잡화>벨트>여성벨트', '50000539', NULL, NULL, 'bcm499', 'smartstore_2'),
('Ami', 'https://www.amiparis.com/en-nl/collections/women-hats-and-beanies', 'WOMEN - ACCESSORIES - Hats & Beanies', '패션잡화>모자>사파리모자', '50000546', NULL, NULL, 'bcm499', 'smartstore_2'),
('Ami', 'https://www.amiparis.com/en-nl/collections/women-caps', 'WOMEN - ACCESSORIES - Caps', '패션잡화>모자>사파리모자', '50000546', NULL, NULL, 'bcm499', 'smartstore_2'),
('Ami', 'https://www.amiparis.com/en-nl/collections/women-sunglasses', 'WOMEN - ACCESSORIES - Sunglasses', '패션잡화>선글라스/안경테>선글라스', '50000554', NULL, NULL, 'bcm499', 'smartstore_2'),
('Ami', 'https://www.amiparis.com/en-nl/collections/women-sneakers', 'WOMEN - SHOES - Sneakers', '패션잡화>여성신발>단화>스니커즈', '50003822', NULL, NULL, 'bcm499', 'smartstore_2'),
('Ami', 'https://www.amiparis.com/en-nl/collections/women-flat-shoes', 'WOMEN - SHOES - Flats', '패션잡화>여성신발>단화>플랫', '50003817', NULL, NULL, 'bcm499', 'smartstore_2'),
('Ami', 'https://www.amiparis.com/en-nl/collections/men-jackets-and-coats', 'MEN - READY TO WEAR - Coats & Jackets', '패션의류>남성의류>아우터>재킷', '50021640', NULL, NULL, 'bcm499', 'smartstore_2'),
('Ami', 'https://www.amiparis.com/en-nl/collections/men-sweaters-and-cardigans', 'MEN - READY TO WEAR - Sweaters & Cardigans', '패션의류>남성의류>니트>풀오버', '50021579', NULL, NULL, 'bcm499', 'smartstore_2'),
('Ami', 'https://www.amiparis.com/en-nl/collections/men-t-shirts-and-polos', 'MEN - READY TO WEAR - T-shirts & Polos', '패션의류>남성의류>티셔츠', '50000830', NULL, NULL, 'bcm499', 'smartstore_2'),
('Ami', 'https://www.amiparis.com/en-nl/collections/men-shirts', 'MEN - READY TO WEAR - Shirts', '패션의류>남성의류>셔츠/남방', '50000833', NULL, NULL, 'bcm499', 'smartstore_2'),
('Ami', 'https://www.amiparis.com/en-nl/collections/men-pants', 'MEN - READY TO WEAR - Trousers', '패션의류>남성의류>바지', '50000836', NULL, NULL, 'bcm499', 'smartstore_2'),
('Ami', 'https://www.amiparis.com/en-nl/collections/men-shorts', 'MEN - READY TO WEAR - Shorts', '패션의류>남성의류>바지', '50000836', NULL, NULL, 'bcm499', 'smartstore_2'),
('Ami', 'https://www.amiparis.com/en-nl/collections/men-belts', 'MEN - ACCESSORIES - Belts', '패션잡화>벨트>남성벨트>캐주얼벨트', '50003989', NULL, NULL, 'bcm499', 'smartstore_2'),
('Ami', 'https://www.amiparis.com/en-nl/collections/men-hats-and-beanies', 'MEN - ACCESSORIES - Hats & Beanies', '패션잡화>모자>사파리모자', '50000546', NULL, NULL, 'bcm499', 'smartstore_2'),
('Ami', 'https://www.amiparis.com/en-nl/collections/men-caps', 'MEN - ACCESSORIES - Caps', '패션잡화>모자>사파리모자', '50000546', NULL, NULL, 'bcm499', 'smartstore_2'),
('Ami', 'https://www.amiparis.com/en-nl/collections/men-sunglasses', 'MEN - ACCESSORIES - Sunglasses', '패션잡화>선글라스/안경테>선글라스', '50000554', NULL, NULL, 'bcm499', 'smartstore_2'),
('Ami', 'https://www.amiparis.com/en-nl/collections/men-sneakers', 'MEN - SHOES - Sneakers', '패션잡화>남성신발>스니커즈', '50000788', NULL, NULL, 'bcm499', 'smartstore_2'),
('Ami', 'https://www.amiparis.com/en-nl/collections/men-flat-shoes', 'MEN - SHOES - Flats', '패션잡화>남성신발>구두', '50000787', NULL, NULL, 'bcm499', 'smartstore_2'),
('Ami', 'https://www.amiparis.com/en-nl/collections/unisex-tote-bags', 'LEATHER GOODS - LEATHER GOODS - Tote Bags', '패션잡화>여성가방>토트백', '50000640', NULL, NULL, 'bcm499', 'smartstore_2'),
('Ami', 'https://www.amiparis.com/en-nl/collections/unisex-shoulder-bags', 'LEATHER GOODS - LEATHER GOODS - Crossbody bags', '패션잡화>여성가방>크로스백', '50000641', NULL, NULL, 'bcm499', 'smartstore_2'),
('Ami', 'https://www.amiparis.com/en-nl/collections/unisex-card-holder', 'LEATHER GOODS - SMALL LEATHER GOODS - Card holders', '패션잡화>지갑>카드/명함지갑', '50000662', NULL, NULL, 'bcm499', 'smartstore_2'),
('Ami', 'https://www.amiparis.com/en-nl/collections/unisex-wallets', 'LEATHER GOODS - SMALL LEATHER GOODS - Wallets', '패션잡화>지갑>여성지갑>반지갑', '50003982', NULL, NULL, 'bcm499', 'smartstore_2'),
('Ami', 'https://www.amiparis.com/en-nl/collections/unisex-pouches', 'LEATHER GOODS - SMALL LEATHER GOODS - Pouches', '패션잡화>여성가방>파우치', '50000643', NULL, NULL, 'bcm499', 'smartstore_2');
