INSERT INTO mapping (
  site,
  "siteUrl",
  "categoryName",
  "godoMallCategoryName",
  "godoMallCategoryCode",
  designers,
  "afterDesigners",
  "customId",
  "accountPlatform"
) VALUES
('Apc', 'https://www.apcstore.com/collections/outerwear-women', 'woman - ready-to-wear - outerwear & jackets', '패션의류>여성의류>아우터>재킷', '50021360', NULL, NULL, 'bcm499', 'smartstore_2'),
('Apc', 'https://www.apcstore.com/collections/blouses-shirts-women', 'woman - ready-to-wear - blouses & shirts', '패션의류>여성의류>블라우스/셔츠', '50000804', NULL, NULL, 'bcm499', 'smartstore_2'),
('Apc', 'https://www.apcstore.com/collections/knitwear-women', 'woman - ready-to-wear - knitwear', '패션의류>여성의류>니트>풀오버', '50021299', NULL, NULL, 'bcm499', 'smartstore_2'),
('Apc', 'https://www.apcstore.com/collections/pants-shorts-women', 'woman - ready-to-wear - pants & shorts', '패션의류>여성의류>바지', '50000810', NULL, NULL, 'bcm499', 'smartstore_2'),
('Apc', 'https://www.apcstore.com/collections/t-shirts-women', 'woman - ready-to-wear - t-shirts', '패션의류>여성의류>티셔츠', '50000803', NULL, NULL, 'bcm499', 'smartstore_2'),
('Apc', 'https://www.apcstore.com/collections/shoulder-bags-women', 'woman - bags - shoulder bags', '패션잡화>여성가방>숄더백', '50000639', NULL, NULL, 'bcm499', 'smartstore_2'),
('Apc', 'https://www.apcstore.com/collections/totes-shopping-bags-women', 'woman - bags - totes & shopping bags', '패션잡화>여성가방>토트백', '50000640', NULL, NULL, 'bcm499', 'smartstore_2'),
('Apc', 'https://www.apcstore.com/collections/sling-bags-women', 'woman - bags - crossbody bags', '패션잡화>여성가방>크로스백', '50000641', NULL, NULL, 'bcm499', 'smartstore_2'),
('Apc', 'https://www.apcstore.com/collections/eyewear', 'woman - accessories - glasses', '패션잡화>선글라스/안경테>선글라스', '50000554', NULL, NULL, 'bcm499', 'smartstore_2'),
('Apc', 'https://www.apcstore.com/collections/hats-caps-women', 'woman - accessories - hats & caps', '패션잡화>모자>사파리모자', '50000546', NULL, NULL, 'bcm499', 'smartstore_2'),
('Apc', 'https://www.apcstore.com/collections/scarves-women', 'woman - accessories - scarves', '패션잡화>패션소품>스카프>롱', '50004010', NULL, NULL, 'bcm499', 'smartstore_2'),
('Apc', 'https://www.apcstore.com/collections/belts-women', 'woman - accessories - belts', '패션잡화>벨트>여성벨트', '50000539', NULL, NULL, 'bcm499', 'smartstore_2'),
('Apc', 'https://www.apcstore.com/collections/outerwear-men', 'man - ready-to-wear - outerwear & jackets', '패션의류>남성의류>아우터>재킷', '50021640', NULL, NULL, 'bcm499', 'smartstore_2'),
('Apc', 'https://www.apcstore.com/collections/shirts-men', 'man - ready-to-wear - shirts', '패션의류>남성의류>셔츠/남방', '50000833', NULL, NULL, 'bcm499', 'smartstore_2'),
('Apc', 'https://www.apcstore.com/collections/t-shirts-men', 'man - ready-to-wear - t-shirts & polos', '패션의류>남성의류>티셔츠', '50000830', NULL, NULL, 'bcm499', 'smartstore_2'),
('Apc', 'https://www.apcstore.com/collections/knitwear-men', 'man - ready-to-wear - knitwear', '패션의류>남성의류>니트>풀오버', '50021579', NULL, NULL, 'bcm499', 'smartstore_2'),
('Apc', 'https://www.apcstore.com/collections/pants-men', 'man - ready-to-wear - pants & shorts', '패션의류>남성의류>바지', '50000836', NULL, NULL, 'bcm499', 'smartstore_2'),
('Apc', 'https://www.apcstore.com/collections/totes-shopping-bag-men', 'man - bags - tote & shopping bags', '패션잡화>남성가방>토트백', '50000647', NULL, NULL, 'bcm499', 'smartstore_2'),
('Apc', 'https://www.apcstore.com/collections/sling-bags-men', 'man - bags - crossbody bags', '패션잡화>남성가방>크로스백', '50000648', NULL, NULL, 'bcm499', 'smartstore_2'),
('Apc', 'https://www.apcstore.com/collections/backpacks-men', 'man - bags - backpacks', '패션잡화>남성가방>백팩', '50000651', NULL, NULL, 'bcm499', 'smartstore_2'),
('Apc', 'https://www.apcstore.com/collections/eyewear', 'man - accessories - glasses', '패션잡화>선글라스/안경테>선글라스', '50000554', NULL, NULL, 'bcm499', 'smartstore_2'),
('Apc', 'https://www.apcstore.com/collections/scarves-men', 'man - accessories - scarves', '패션잡화>패션소품>스카프>롱', '50004010', NULL, NULL, 'bcm499', 'smartstore_2'),
('Apc', 'https://www.apcstore.com/collections/hats-caps-men', 'man - accessories - hat & caps', '패션잡화>모자>사파리모자', '50000546', NULL, NULL, 'bcm499', 'smartstore_2'),
('Apc', 'https://www.apcstore.com/collections/belts-men', 'man - accessories - belts', '패션잡화>벨트>남성벨트>캐주얼벨트', '50003989', NULL, NULL, 'bcm499', 'smartstore_2');
