INSERT INTO mapping (
  site,
  "siteUrl",
  "categoryName",
  "godoMallCategoryName",
  "godoMallCategoryCode",
  designers,
  "afterDesigners",
  "customId",
  "accountPlatform"
)
VALUES
('Balenciaga', 'https://www.balenciaga.com/en-de/women/ready-to-wear-for-women/coats-and-jackets', 'women/ready-to-wear-for-women/coats-and-jackets', '패션의류>여성의류>아우터>재킷', '50021360', NULL, NULL, 'bcm499', 'smartstore_2'),
('Balenciaga', 'https://www.balenciaga.com/en-de/women/ready-to-wear-for-women/sweatshirts-and-hoodies', 'women/ready-to-wear-for-women/sweatshirts-and-hoodies', '패션의류>여성의류>티셔츠', '50000803', NULL, NULL, 'bcm499', 'smartstore_2'),
('Balenciaga', 'https://www.balenciaga.com/en-de/women/ready-to-wear-for-women/t-shirts', 'women/ready-to-wear-for-women/t-shirts', '패션의류>여성의류>티셔츠', '50000803', NULL, NULL, 'bcm499', 'smartstore_2'),
('Balenciaga', 'https://www.balenciaga.com/en-de/women/ready-to-wear-for-women/knitwear-for-women', 'women/ready-to-wear-for-women/knitwear-for-women', '패션의류>여성의류>니트>풀오버', '50021299', NULL, NULL, 'bcm499', 'smartstore_2'),
('Balenciaga', 'https://www.balenciaga.com/en-de/women/ready-to-wear-for-women/tops-and-shirts-for-women', 'women/ready-to-wear-for-women/tops-and-shirts-for-women', '패션의류>여성의류>블라우스/셔츠', '50000804', NULL, NULL, 'bcm499', 'smartstore_2'),
('Balenciaga', 'https://www.balenciaga.com/en-de/women/ready-to-wear-for-women/dresses-and-skirts-for-women', 'women/ready-to-wear-for-women/dresses-and-skirts-for-women', '패션의류>여성의류>원피스', '50000807', NULL, NULL, 'bcm499', 'smartstore_2'),
('Balenciaga', 'https://www.balenciaga.com/en-de/women/ready-to-wear-for-women/pants-for-women', 'women/ready-to-wear-for-women/pants-for-women', '패션의류>여성의류>바지', '50000810', NULL, NULL, 'bcm499', 'smartstore_2'),
('Balenciaga', 'https://www.balenciaga.com/en-de/women/shoes-for-women/sneakers-for-women', 'women/shoes-for-women/sneakers-for-women', '패션잡화>여성신발>단화>스니커즈', '50003822', NULL, NULL, 'bcm499', 'smartstore_2'),
('Balenciaga', 'https://www.balenciaga.com/en-de/women/shoes-for-women/boots-and-ankle-boots', 'women/shoes-for-women/boots-and-ankle-boots', '패션잡화>여성신발>부츠>앵클/숏부츠', '50004191', NULL, NULL, 'bcm499', 'smartstore_2'),
('Balenciaga', 'https://www.balenciaga.com/en-de/women/shoes-for-women/heels-for-women', 'women/shoes-for-women/heels-for-women', '패션잡화>여성신발>힐/펌프스>펌프스', '50003830', NULL, NULL, 'bcm499', 'smartstore_2'),
('Balenciaga', 'https://www.balenciaga.com/en-de/women/shoes-for-women/sandals-for-women', 'women/shoes-for-women/sandals-for-women', '패션잡화>여성신발>샌들>스트랩샌들', '50003842', NULL, NULL, 'bcm499', 'smartstore_2'),
('Balenciaga', 'https://www.balenciaga.com/en-de/women/bags-for-women/shoulder-bags-for-women', 'women/bags-for-women/shoulder-bags-for-women', '패션잡화>여성가방>숄더백', '50000639', NULL, NULL, 'bcm499', 'smartstore_2'),
('Balenciaga', 'https://www.balenciaga.com/en-de/women/bags-for-women/tote-bags', 'women/bags-for-women/tote-bags', '패션잡화>여성가방>토트백', '50000640', NULL, NULL, 'bcm499', 'smartstore_2'),
('Balenciaga', 'https://www.balenciaga.com/en-de/women/small-leather-goods%C2%A0for-women/clutches-and-pouches', 'women/small-leather-goods%C2%A0for-women/clutches-and-pouches', '패션잡화>여성가방>파우치', '50000643', NULL, NULL, 'bcm499', 'smartstore_2'),
('Balenciaga', 'https://www.balenciaga.com/en-de/women/small-leather-goods%C2%A0for-women/wallets-on-chain-for-women', 'women/small-leather-goods%C2%A0for-women/wallets-on-chain-for-women', '패션잡화>지갑>여성지갑>반지갑', '50003982', NULL, NULL, 'bcm499', 'smartstore_2'),
('Balenciaga', 'https://www.balenciaga.com/en-de/women/small-leather-goods%C2%A0for-women/wallets-for-women', 'women/small-leather-goods%C2%A0for-women/wallets-for-women', '패션잡화>지갑>여성지갑>반지갑', '50003982', NULL, NULL, 'bcm499', 'smartstore_2'),
('Balenciaga', 'https://www.balenciaga.com/en-de/women/small-leather-goods%C2%A0for-women/card-holders-for-women', 'women/small-leather-goods%C2%A0for-women/card-holders-for-women', '패션잡화>지갑>카드/명함지갑', '50000662', NULL, NULL, 'bcm499', 'smartstore_2'),
('Balenciaga', 'https://www.balenciaga.com/en-de/women/accessories/sunglasses', 'women/accessories/sunglasses', '패션잡화>선글라스/안경테>선글라스', '50000554', NULL, NULL, 'bcm499', 'smartstore_2'),
('Balenciaga', 'https://www.balenciaga.com/en-de/women/accessories/belts-for-women', 'women/accessories/belts-for-women', '패션잡화>벨트>여성벨트', '50000539', NULL, NULL, 'bcm499', 'smartstore_2'),
('Balenciaga', 'https://www.balenciaga.com/en-de/women/accessories/hair-accessories-for-women', 'women/accessories/hair-accessories-for-women', '패션잡화>헤어액세서리>헤어밴드', '50000560', NULL, NULL, 'bcm499', 'smartstore_2'),
('Balenciaga', 'https://www.balenciaga.com/en-de/men/ready-to-wear%C2%A0for-men/coats-and-jackets%C2%A0for-men', 'men/ready-to-wear%C2%A0for-men/coats-and-jackets%C2%A0for-men', '패션의류>남성의류>아우터>재킷', '50021640', NULL, NULL, 'bcm499', 'smartstore_2'),
('Balenciaga', 'https://www.balenciaga.com/en-de/men/ready-to-wear%C2%A0for-men/sweatshirts-and-hoodies%C2%A0for-men', 'men/ready-to-wear%C2%A0for-men/sweatshirts-and-hoodies%C2%A0for-men', '패션의류>남성의류>티셔츠', '50000830', NULL, NULL, 'bcm499', 'smartstore_2'),
('Balenciaga', 'https://www.balenciaga.com/en-de/men/ready-to-wear%C2%A0for-men/t-shirts%C2%A0for-men', 'men/ready-to-wear%C2%A0for-men/t-shirts%C2%A0for-men', '패션의류>남성의류>티셔츠', '50000830', NULL, NULL, 'bcm499', 'smartstore_2'),
('Balenciaga', 'https://www.balenciaga.com/en-de/men/ready-to-wear%C2%A0for-men/knitwear', 'men/ready-to-wear%C2%A0for-men/knitwear', '패션의류>남성의류>니트>풀오버', '50021579', NULL, NULL, 'bcm499', 'smartstore_2'),
('Balenciaga', 'https://www.balenciaga.com/en-de/men/ready-to-wear%C2%A0for-men/tops-and-shirts%C2%A0for-men', 'men/ready-to-wear%C2%A0for-men/tops-and-shirts%C2%A0for-men', '패션의류>남성의류>셔츠/남방', '50000833', NULL, NULL, 'bcm499', 'smartstore_2'),
('Balenciaga', 'https://www.balenciaga.com/en-de/men/ready-to-wear%C2%A0for-men/pants', 'men/ready-to-wear%C2%A0for-men/pants', '패션의류>남성의류>바지', '50000836', NULL, NULL, 'bcm499', 'smartstore_2'),
('Balenciaga', 'https://www.balenciaga.com/en-de/men/shoes-for-men/sneakers%C2%A0for-men', 'men/shoes-for-men/sneakers%C2%A0for-men', '패션잡화>남성신발>스니커즈', '50000788', NULL, NULL, 'bcm499', 'smartstore_2'),
('Balenciaga', 'https://www.balenciaga.com/en-de/men/shoes-for-men/sandals-and-mules%C2%A0for-men', 'men/shoes-for-men/sandals-and-mules%C2%A0for-men', '패션잡화>남성신발>샌들', '50000789', NULL, NULL, 'bcm499', 'smartstore_2'),
('Balenciaga', 'https://www.balenciaga.com/en-de/men/shoes-for-men/boots-and-derbies%C2%A0for-men', 'men/shoes-for-men/boots-and-derbies%C2%A0for-men', '패션잡화>남성신발>부츠>앵클/숏부츠', '50021999', NULL, NULL, 'bcm499', 'smartstore_2'),
('Balenciaga', 'https://www.balenciaga.com/en-de/men/bags-for-men/bags-and-totes%C2%A0for-men', 'men/bags-for-men/bags-and-totes%C2%A0for-men', '패션잡화>남성가방>토트백', '50000647', NULL, NULL, 'bcm499', 'smartstore_2'),
('Balenciaga', 'https://www.balenciaga.com/en-de/men/bags-for-men/backpacks', 'men/bags-for-men/backpacks', '패션잡화>남성가방>백팩', '50000651', NULL, NULL, 'bcm499', 'smartstore_2'),
('Balenciaga', 'https://www.balenciaga.com/en-de/men/bags-for-men/beltbags%C2%A0for-men', 'men/bags-for-men/beltbags%C2%A0for-men', '패션잡화>남성가방>힙색/슬링백', '50000652', NULL, NULL, 'bcm499', 'smartstore_2'),
('Balenciaga', 'https://www.balenciaga.com/en-de/men/bags-for-men/crossbodies-and-messengers%C2%A0for-men', 'men/bags-for-men/crossbodies-and-messengers%C2%A0for-men', '패션잡화>남성가방>크로스백', '50000648', NULL, NULL, 'bcm499', 'smartstore_2'),
('Balenciaga', 'https://www.balenciaga.com/en-de/men/small-leather-goods-for-men/wallets%C2%A0for-men', 'men/small-leather-goods-for-men/wallets%C2%A0for-men', '패션잡화>지갑>남성지갑>반지갑', '50003985', NULL, NULL, 'bcm499', 'smartstore_2'),
('Balenciaga', 'https://www.balenciaga.com/en-de/men/small-leather-goods-for-men/card-holders', 'men/small-leather-goods-for-men/card-holders', '패션잡화>지갑>카드/명함지갑', '50000662', NULL, NULL, 'bcm499', 'smartstore_2'),
('Balenciaga', 'https://www.balenciaga.com/en-de/men/small-leather-goods-for-men/clutches-and-pouches%C2%A0for-men', 'men/small-leather-goods-for-men/clutches-and-pouches%C2%A0for-men', '패션잡화>남성가방>클러치백', '50000649', NULL, NULL, 'bcm499', 'smartstore_2'),
('Balenciaga', 'https://www.balenciaga.com/en-de/men/accessories-for-men/sunglasses', 'men/accessories-for-men/sunglasses', '패션잡화>선글라스/안경테>선글라스', '50000554', NULL, NULL, 'bcm499', 'smartstore_2'),
('Balenciaga', 'https://www.balenciaga.com/en-de/men/accessories-for-men/belts%C2%A0for-men', 'men/accessories-for-men/belts%C2%A0for-men', '패션잡화>벨트>남성벨트>캐주얼벨트', '50003989', NULL, NULL, 'bcm499', 'smartstore_2')
ON CONFLICT (site, "siteUrl", "godoMallCategoryCode", "customId", "accountPlatform")
DO UPDATE SET
  "categoryName" = EXCLUDED."categoryName",
  "godoMallCategoryName" = EXCLUDED."godoMallCategoryName",
  designers = EXCLUDED.designers,
  "afterDesigners" = EXCLUDED."afterDesigners";
