INSERT INTO mapping (
  site,
  "siteUrl",
  "categoryName",
  "godoMallCategoryName",
  "godoMallCategoryCode",
  designers,
  "afterDesigners",
  "customId",
  "accountPlatform"
)
VALUES
('Bottega', 'https://www.bottegaveneta.com/en-de/women-collection-de/women-bags/women-crossbody-bags', 'women-collection-de - women-bags - women-crossbody-bags', '패션잡화>여성가방>크로스백', '50000641', NULL, NULL, 'bcm499', 'smartstore_2'),
('Bottega', 'https://www.bottegaveneta.com/en-de/women-collection-de/women-bags/shoulder', 'women-collection-de - women-bags - shoulder', '패션잡화>여성가방>숄더백', '50000639', NULL, NULL, 'bcm499', 'smartstore_2'),
('Bottega', 'https://www.bottegaveneta.com/en-de/women-collection-de/women-bags/handle', 'women-collection-de - women-bags - handle', '패션잡화>여성가방>토트백', '50000640', NULL, NULL, 'bcm499', 'smartstore_2'),
('Bottega', 'https://www.bottegaveneta.com/en-de/women-collection-de/women-bags/women-shopper', 'women-collection-de - women-bags - women-shopper', '패션잡화>여성가방>토트백', '50000640', NULL, NULL, 'bcm499', 'smartstore_2'),
('Bottega', 'https://www.bottegaveneta.com/en-de/women-collection-de/women-bags/clutch', 'women-collection-de - women-bags - clutch', '패션잡화>여성가방>클러치백', '50000642', NULL, NULL, 'bcm499', 'smartstore_2'),
('Bottega', 'https://www.bottegaveneta.com/en-de/women-collection-de/women-shoes/loafers-and-lace-ups', 'women-collection-de - women-shoes - loafers-and-lace-ups', '패션잡화>여성신발>단화>로퍼', '50003818', NULL, NULL, 'bcm499', 'smartstore_2'),
('Bottega', 'https://www.bottegaveneta.com/en-de/women-collection-de/women-shoes/ballerinas-and-slippers', 'women-collection-de - women-shoes - ballerinas-and-slippers', '패션잡화>여성신발>단화>플랫', '50003817', NULL, NULL, 'bcm499', 'smartstore_2'),
('Bottega', 'https://www.bottegaveneta.com/en-de/women-collection-de/women-shoes/women-sneakers', 'women-collection-de - women-shoes - women-sneakers', '패션잡화>여성신발>단화>스니커즈', '50003822', NULL, NULL, 'bcm499', 'smartstore_2'),
('Bottega', 'https://www.bottegaveneta.com/en-de/women-collection-de/women-shoes/women-sandals', 'women-collection-de - women-shoes - women-sandals', '패션잡화>여성신발>샌들>스트랩샌들', '50003842', NULL, NULL, 'bcm499', 'smartstore_2'),
('Bottega', 'https://www.bottegaveneta.com/en-de/women-collection-de/women-shoes/pumps', 'women-collection-de - women-shoes - pumps', '패션잡화>여성신발>힐/펌프스>펌프스', '50003830', NULL, NULL, 'bcm499', 'smartstore_2'),
('Bottega', 'https://www.bottegaveneta.com/en-de/women-collection-de/women-shoes/boots', 'women-collection-de - women-shoes - boots', '패션잡화>여성신발>부츠>앵클/숏부츠', '50004191', NULL, NULL, 'bcm499', 'smartstore_2'),
('Bottega', 'https://www.bottegaveneta.com/en-de/women-collection-de/women-wallets/small-wallets', 'women-collection-de - women-wallets - small-wallets', '패션잡화>지갑>여성지갑>반지갑', '50003982', NULL, NULL, 'bcm499', 'smartstore_2'),
('Bottega', 'https://www.bottegaveneta.com/en-de/women-collection-de/women-wallets/long-wallets', 'women-collection-de - women-wallets - long-wallets', '패션잡화>지갑>여성지갑>장지갑', '50003984', NULL, NULL, 'bcm499', 'smartstore_2'),
('Bottega', 'https://www.bottegaveneta.com/en-de/women-collection-de/women-wallets/card-cases', 'women-collection-de - women-wallets - card-cases', '패션잡화>지갑>카드/명함지갑', '50000662', NULL, NULL, 'bcm499', 'smartstore_2'),
('Bottega', 'https://www.bottegaveneta.com/en-de/women-collection-de/women-wallets/pouches', 'women-collection-de - women-wallets - pouches', '패션잡화>여성가방>파우치', '50000643', NULL, NULL, 'bcm499', 'smartstore_2'),
('Bottega', 'https://www.bottegaveneta.com/en-de/women-collection-de/women-clothing/women-outerwear', 'women-collection-de - women-clothing - women-outerwear', '패션의류>여성의류>아우터>재킷', '50021360', NULL, NULL, 'bcm499', 'smartstore_2'),
('Bottega', 'https://www.bottegaveneta.com/en-de/women-collection-de/women-clothing/jackets', 'women-collection-de - women-clothing - jackets', '패션의류>여성의류>아우터>재킷', '50021360', NULL, NULL, 'bcm499', 'smartstore_2'),
('Bottega', 'https://www.bottegaveneta.com/en-de/women-collection-de/women-clothing/knitwear', 'women-collection-de - women-clothing - knitwear', '패션의류>여성의류>니트>풀오버', '50021299', NULL, NULL, 'bcm499', 'smartstore_2'),
('Bottega', 'https://www.bottegaveneta.com/en-de/women-collection-de/women-clothing/dresses', 'women-collection-de - women-clothing - dresses', '패션의류>여성의류>원피스', '50000807', NULL, NULL, 'bcm499', 'smartstore_2'),
('Bottega', 'https://www.bottegaveneta.com/en-de/women-collection-de/women-clothing/trousers-and-shorts', 'women-collection-de - women-clothing - trousers-and-shorts', '패션의류>여성의류>바지', '50000810', NULL, NULL, 'bcm499', 'smartstore_2'),
('Bottega', 'https://www.bottegaveneta.com/en-de/women-collection-de/women-clothing/shirts', 'women-collection-de - women-clothing - shirts', '패션의류>여성의류>블라우스/셔츠', '50000804', NULL, NULL, 'bcm499', 'smartstore_2'),
('Bottega', 'https://www.bottegaveneta.com/en-de/women-collection-de/women-clothing/skirts', 'women-collection-de - women-clothing - skirts', '패션의류>여성의류>스커트', '50000808', NULL, NULL, 'bcm499', 'smartstore_2'),
('Bottega', 'https://www.bottegaveneta.com/en-de/women-collection-de/women-clothing/tops-and-t-shirts', 'women-collection-de - women-clothing - tops-and-t-shirts', '패션의류>여성의류>티셔츠', '50000803', NULL, NULL, 'bcm499', 'smartstore_2'),
('Bottega', 'https://www.bottegaveneta.com/en-de/women-collection-de/women-jewellery/women-earrings', 'women-collection-de - women-jewellery - women-earrings', '패션잡화>주얼리>귀걸이>패션귀걸이', '50004164', NULL, NULL, 'bcm499', 'smartstore_2'),
('Bottega', 'https://www.bottegaveneta.com/en-de/women-collection-de/women-jewellery/women-rings', 'women-collection-de - women-jewellery - women-rings', '패션잡화>주얼리>반지>패션반지', '50004155', NULL, NULL, 'bcm499', 'smartstore_2'),
('Bottega', 'https://www.bottegaveneta.com/en-de/women-collection-de/women-jewellery/bracelets', 'women-collection-de - women-jewellery - bracelets', '패션잡화>주얼리>팔찌>패션팔찌', '50004194', NULL, NULL, 'bcm499', 'smartstore_2'),
('Bottega', 'https://www.bottegaveneta.com/en-de/women-collection-de/women-jewellery/necklaces', 'women-collection-de - women-jewellery - necklaces', '패션잡화>주얼리>목걸이>패션목걸이', '50004174', NULL, NULL, 'bcm499', 'smartstore_2'),
('Bottega', 'https://www.bottegaveneta.com/en-de/women-collection-de/women-jewellery/women-brooch', 'women-collection-de - women-jewellery - women-brooch', '패션잡화>패션소품>브로치>패션브로치', '50004028', NULL, NULL, 'bcm499', 'smartstore_2'),
('Bottega', 'https://www.bottegaveneta.com/en-de/women-collection-de/women-accessories/women-belts', 'women-collection-de - women-accessories - women-belts', '패션잡화>벨트>여성벨트', '50000539', NULL, NULL, 'bcm499', 'smartstore_2'),
('Bottega', 'https://www.bottegaveneta.com/en-de/women-collection-de/women-accessories/scarves', 'women-collection-de - women-accessories - scarves', '패션잡화>패션소품>스카프>롱', '50004010', NULL, NULL, 'bcm499', 'smartstore_2'),
('Bottega', 'https://www.bottegaveneta.com/en-de/women-collection-de/women-accessories/women-hats', 'women-collection-de - women-accessories - women-hats', '패션잡화>모자>비니', '50000543', NULL, NULL, 'bcm499', 'smartstore_2'),
('Bottega', 'https://www.bottegaveneta.com/en-de/women-collection-de/women-eyewear/sunglasses', 'women-collection-de - women-eyewear - sunglasses', '패션잡화>선글라스/안경테>선글라스', '50000554', NULL, NULL, 'bcm499', 'smartstore_2'),
('Bottega', 'https://www.bottegaveneta.com/en-de/men-collection-de/men-bags/men-crossbody-bags', 'men-collection-de - men-bags - men-crossbody-bags', '패션잡화>남성가방>크로스백', '50000648', NULL, NULL, 'bcm499', 'smartstore_2'),
('Bottega', 'https://www.bottegaveneta.com/en-de/men-collection-de/men-bags/men-tote-bags', 'men-collection-de - men-bags - men-tote-bags', '패션잡화>남성가방>토트백', '50000647', NULL, NULL, 'bcm499', 'smartstore_2'),
('Bottega', 'https://www.bottegaveneta.com/en-de/men-collection-de/men-bags/backpack', 'men-collection-de - men-bags - backpack', '패션잡화>남성가방>백팩', '50000651', NULL, NULL, 'bcm499', 'smartstore_2'),
('Bottega', 'https://www.bottegaveneta.com/en-de/men-collection-de/men-bags/belt', 'men-collection-de - men-bags - belt', '패션잡화>남성가방>힙색/슬링백', '50000652', NULL, NULL, 'bcm499', 'smartstore_2'),
('Bottega', 'https://www.bottegaveneta.com/en-de/men-collection-de/men-bags/briefcase', 'men-collection-de - men-bags - briefcase', '패션잡화>남성가방>브리프케이스', '50000650', NULL, NULL, 'bcm499', 'smartstore_2'),
('Bottega', 'https://www.bottegaveneta.com/en-de/men-collection-de/men-bags/document-case', 'men-collection-de - men-bags - document-case', '패션잡화>남성가방>브리프케이스', '50000650', NULL, NULL, 'bcm499', 'smartstore_2'),
('Bottega', 'https://www.bottegaveneta.com/en-de/men-collection-de/men-shoes/men-sneakers', 'men-collection-de - men-shoes - men-sneakers', '패션잡화>남성신발>스니커즈', '50000788', NULL, NULL, 'bcm499', 'smartstore_2'),
('Bottega', 'https://www.bottegaveneta.com/en-de/men-collection-de/men-shoes/loafers', 'men-collection-de - men-shoes - loafers', '패션잡화>남성신발>구두', '50000787', NULL, NULL, 'bcm499', 'smartstore_2'),
('Bottega', 'https://www.bottegaveneta.com/en-de/men-collection-de/men-shoes/lace-ups', 'men-collection-de - men-shoes - lace-ups', '패션잡화>남성신발>구두', '50000787', NULL, NULL, 'bcm499', 'smartstore_2'),
('Bottega', 'https://www.bottegaveneta.com/en-de/men-collection-de/men-shoes/boots', 'men-collection-de - men-shoes - boots', '패션잡화>남성신발>부츠>앵클/숏부츠', '50021999', NULL, NULL, 'bcm499', 'smartstore_2'),
('Bottega', 'https://www.bottegaveneta.com/en-de/men-collection-de/men-shoes/slippers', 'men-collection-de - men-shoes - slippers', '패션잡화>남성신발>슬립온', '50000783', NULL, NULL, 'bcm499', 'smartstore_2'),
('Bottega', 'https://www.bottegaveneta.com/en-de/men-collection-de/men-shoes/men-sandals', 'men-collection-de - men-shoes - men-sandals', '패션잡화>남성신발>샌들', '50000789', NULL, NULL, 'bcm499', 'smartstore_2'),
('Bottega', 'https://www.bottegaveneta.com/en-de/men-collection-de/men-wallets/small-wallets', 'men-collection-de - men-wallets - small-wallets', '패션잡화>지갑>남성지갑>반지갑', '50003985', NULL, NULL, 'bcm499', 'smartstore_2'),
('Bottega', 'https://www.bottegaveneta.com/en-de/men-collection-de/men-wallets/long-wallets', 'men-collection-de - men-wallets - long-wallets', '패션잡화>지갑>남성지갑>장지갑', '50003987', NULL, NULL, 'bcm499', 'smartstore_2'),
('Bottega', 'https://www.bottegaveneta.com/en-de/men-collection-de/men-wallets/card-cases', 'men-collection-de - men-wallets - card-cases', '패션잡화>지갑>카드/명함지갑', '50000662', NULL, NULL, 'bcm499', 'smartstore_2'),
('Bottega', 'https://www.bottegaveneta.com/en-de/men-collection-de/men-wallets/pouches', 'men-collection-de - men-wallets - pouches', '패션잡화>남성가방>클러치백', '50000649', NULL, NULL, 'bcm499', 'smartstore_2'),
('Bottega', 'https://www.bottegaveneta.com/en-de/men-collection-de/men-clothing/coats', 'men-collection-de - men-clothing - coats', '패션의류>남성의류>아우터>재킷', '50021640', NULL, NULL, 'bcm499', 'smartstore_2'),
('Bottega', 'https://www.bottegaveneta.com/en-de/men-collection-de/men-clothing/jackets', 'men-collection-de - men-clothing - jackets', '패션의류>남성의류>아우터>재킷', '50021640', NULL, NULL, 'bcm499', 'smartstore_2'),
('Bottega', 'https://www.bottegaveneta.com/en-de/men-collection-de/men-clothing/knitwear', 'men-collection-de - men-clothing - knitwear', '패션의류>남성의류>니트>풀오버', '50021579', NULL, NULL, 'bcm499', 'smartstore_2'),
('Bottega', 'https://www.bottegaveneta.com/en-de/men-collection-de/men-clothing/trousers-and-shorts', 'men-collection-de - men-clothing - trousers-and-shorts', '패션의류>남성의류>바지', '50000836', NULL, NULL, 'bcm499', 'smartstore_2'),
('Bottega', 'https://www.bottegaveneta.com/en-de/men-collection-de/men-clothing/shirts', 'men-collection-de - men-clothing - shirts', '패션의류>남성의류>셔츠/남방', '50000833', NULL, NULL, 'bcm499', 'smartstore_2'),
('Bottega', 'https://www.bottegaveneta.com/en-de/men-collection-de/men-clothing/t-shirts', 'men-collection-de - men-clothing - t-shirts', '패션의류>남성의류>티셔츠', '50000830', NULL, NULL, 'bcm499', 'smartstore_2'),
('Bottega', 'https://www.bottegaveneta.com/en-de/men-collection-de/men-clothing/polos', 'men-collection-de - men-clothing - polos', '패션의류>남성의류>티셔츠', '50000830', NULL, NULL, 'bcm499', 'smartstore_2'),
('Bottega', 'https://www.bottegaveneta.com/en-de/men-collection-de/men-jewellery/men-earrings', 'men-collection-de - men-jewellery - men-earrings', '패션잡화>주얼리>귀걸이>패션귀걸이', '50004164', NULL, NULL, 'bcm499', 'smartstore_2'),
('Bottega', 'https://www.bottegaveneta.com/en-de/men-collection-de/men-jewellery/men-rings', 'men-collection-de - men-jewellery - men-rings', '패션잡화>주얼리>반지>패션반지', '50004155', NULL, NULL, 'bcm499', 'smartstore_2'),
('Bottega', 'https://www.bottegaveneta.com/en-de/men-collection-de/men-jewellery/bracelets', 'men-collection-de - men-jewellery - bracelets', '패션잡화>주얼리>팔찌>패션팔찌', '50004194', NULL, NULL, 'bcm499', 'smartstore_2'),
('Bottega', 'https://www.bottegaveneta.com/en-de/men-collection-de/men-jewellery/necklaces', 'men-collection-de - men-jewellery - necklaces', '패션잡화>주얼리>목걸이>패션목걸이', '50004174', NULL, NULL, 'bcm499', 'smartstore_2'),
('Bottega', 'https://www.bottegaveneta.com/en-de/men-collection-de/men-jewellery/cufflinks', 'men-collection-de - men-jewellery - cufflinks', '패션잡화>패션소품>커프스', '50000564', NULL, NULL, 'bcm499', 'smartstore_2'),
('Bottega', 'https://www.bottegaveneta.com/en-de/men-collection-de/men-accessories/men-belts', 'men-collection-de - men-accessories - men-belts', '패션잡화>벨트>남성벨트>캐주얼벨트', '50003989', NULL, NULL, 'bcm499', 'smartstore_2'),
('Bottega', 'https://www.bottegaveneta.com/en-de/men-collection-de/men-accessories/men-hats', 'men-collection-de - men-accessories - men-hats', '패션잡화>모자>비니', '50000543', NULL, NULL, 'bcm499', 'smartstore_2'),
('Bottega', 'https://www.bottegaveneta.com/en-de/men-collection-de/men-eyewear/sunglasses', 'men-collection-de - men-eyewear - sunglasses', '패션잡화>선글라스/안경테>선글라스', '50000554', NULL, NULL, 'bcm499', 'smartstore_2')
ON CONFLICT (site, "siteUrl", "godoMallCategoryCode", "customId", "accountPlatform")
DO UPDATE SET
  "categoryName" = EXCLUDED."categoryName",
  "godoMallCategoryName" = EXCLUDED."godoMallCategoryName",
  designers = EXCLUDED.designers,
  "afterDesigners" = EXCLUDED."afterDesigners";
