INSERT INTO mapping (
  site,
  "siteUrl",
  "categoryName",
  "godoMallCategoryName",
  "godoMallCategoryCode",
  designers,
  "afterDesigners",
  "customId",
  "accountPlatform"
) VALUES
('Brunello', 'https://shop.brunellocucinelli.com/en-fr/women/ready-to-wear/coats-jackets/', '여성 - Ready To Wear - Coats & Jackets', '패션의류>여성의류>아우터>재킷', '50021360', NULL, NULL, 'bcm499', 'smartstore_2'),
('Brunello', 'https://shop.brunellocucinelli.com/en-fr/women/ready-to-wear/knitwear/', '여성 - Ready To Wear - Knitwear', '패션의류>여성의류>니트>풀오버', '50021299', NULL, NULL, 'bcm499', 'smartstore_2'),
('Brunello', 'https://shop.brunellocucinelli.com/en-fr/women/ready-to-wear/blazers/', '여성 - Ready To Wear - Blazers', '패션의류>여성의류>아우터>재킷', '50021360', NULL, NULL, 'bcm499', 'smartstore_2'),
('Brunello', 'https://shop.brunellocucinelli.com/en-fr/women/ready-to-wear/dresses-jumpsuits/', '여성 - Ready To Wear - Dresses & Jumpsuits', '패션의류>여성의류>원피스', '50000807', NULL, NULL, 'bcm499', 'smartstore_2'),
('Brunello', 'https://shop.brunellocucinelli.com/en-fr/women/ready-to-wear/matching-sets/', '여성 - Ready To Wear - Matching Sets', '패션의류>여성의류>정장세트', '50000816', NULL, NULL, 'bcm499', 'smartstore_2'),
('Brunello', 'https://shop.brunellocucinelli.com/en-fr/women/ready-to-wear/t-shirts-tops/', '여성 - Ready To Wear - T-shirts & Tops', '패션의류>여성의류>티셔츠', '50000803', NULL, NULL, 'bcm499', 'smartstore_2'),
('Brunello', 'https://shop.brunellocucinelli.com/en-fr/women/ready-to-wear/shirts/', '여성 - Ready To Wear - Shirts', '패션의류>여성의류>블라우스/셔츠', '50000804', NULL, NULL, 'bcm499', 'smartstore_2'),
('Brunello', 'https://shop.brunellocucinelli.com/en-fr/women/ready-to-wear/skirts/', '여성 - Ready To Wear - Skirts', '패션의류>여성의류>스커트', '50000808', NULL, NULL, 'bcm499', 'smartstore_2'),
('Brunello', 'https://shop.brunellocucinelli.com/en-fr/women/ready-to-wear/pants/', '여성 - Ready To Wear - Pants', '패션의류>여성의류>바지', '50000810', NULL, NULL, 'bcm499', 'smartstore_2'),
('Brunello', 'https://shop.brunellocucinelli.com/en-fr/women/shoes/heels/', '여성 - Shoes - Heels', '패션잡화>여성신발>힐/펌프스>펌프스', '50003830', NULL, NULL, 'bcm499', 'smartstore_2'),
('Brunello', 'https://shop.brunellocucinelli.com/en-fr/women/shoes/sneakers/', '여성 - Shoes - Sneakers', '패션잡화>여성신발>단화>스니커즈', '50003822', NULL, NULL, 'bcm499', 'smartstore_2'),
('Brunello', 'https://shop.brunellocucinelli.com/en-fr/women/shoes/boots/', '여성 - Shoes - Boots', '패션잡화>여성신발>부츠>앵클/숏부츠', '50004191', NULL, NULL, 'bcm499', 'smartstore_2'),
('Brunello', 'https://shop.brunellocucinelli.com/en-fr/women/shoes/loafers-flat-shoes/', '여성 - Shoes - Loafers & Flat Shoes', '패션잡화>여성신발>단화>로퍼', '50003818', NULL, NULL, 'bcm499', 'smartstore_2'),
('Brunello', 'https://shop.brunellocucinelli.com/en-fr/women/shoes/sandals/', '여성 - Shoes - Sandals', '패션잡화>여성신발>샌들>스트랩샌들', '50003842', NULL, NULL, 'bcm499', 'smartstore_2'),
('Brunello', 'https://shop.brunellocucinelli.com/en-fr/women/bags/mini-bags-clutches/', '여성 - Bags - Mini Bags & Clutches', '패션잡화>여성가방>클러치백', '50000642', NULL, NULL, 'bcm499', 'smartstore_2'),
('Brunello', 'https://shop.brunellocucinelli.com/en-fr/women/bags/crossbody-bags/', '여성 - Bags - Crossbody Bags', '패션잡화>여성가방>크로스백', '50000641', NULL, NULL, 'bcm499', 'smartstore_2'),
('Brunello', 'https://shop.brunellocucinelli.com/en-fr/women/bags/handbags-shoppers/', '여성 - Bags - Handbags & Shoppers', '패션잡화>여성가방>토트백', '50000640', NULL, NULL, 'bcm499', 'smartstore_2'),
('Brunello', 'https://shop.brunellocucinelli.com/en-fr/women/accessories/womens-eyewear/', '여성 - Accessories - Eyewear', '패션잡화>선글라스/안경테>선글라스', '50000554', NULL, NULL, 'bcm499', 'smartstore_2'),
('Brunello', 'https://shop.brunellocucinelli.com/en-fr/women/accessories/small-leather-goods/', '여성 - Accessories - Small Leather Goods', '패션잡화>지갑>여성지갑>반지갑', '50003982', NULL, NULL, 'bcm499', 'smartstore_2'),
('Brunello', 'https://shop.brunellocucinelli.com/en-fr/women/accessories/scarves/', '여성 - Accessories - Scarves', '패션잡화>패션소품>스카프>롱', '50004010', NULL, NULL, 'bcm499', 'smartstore_2'),
('Brunello', 'https://shop.brunellocucinelli.com/en-fr/women/accessories/hats/', '여성 - Accessories - Hats', '패션잡화>모자>비니', '50000543', NULL, NULL, 'bcm499', 'smartstore_2'),
('Brunello', 'https://shop.brunellocucinelli.com/en-fr/women/accessories/belts/', '여성 - Accessories - Belts', '패션잡화>벨트>여성벨트', '50000539', NULL, NULL, 'bcm499', 'smartstore_2'),
('Brunello', 'https://shop.brunellocucinelli.com/en-fr/men/ready-to-wear/coats-jackets/', '남성 - Ready To Wear - Coats & Jackets', '패션의류>남성의류>아우터>재킷', '50021640', NULL, NULL, 'bcm499', 'smartstore_2'),
('Brunello', 'https://shop.brunellocucinelli.com/en-fr/men/ready-to-wear/knitwear/', '남성 - Ready To Wear - Knitwear', '패션의류>남성의류>니트>풀오버', '50021579', NULL, NULL, 'bcm499', 'smartstore_2'),
('Brunello', 'https://shop.brunellocucinelli.com/en-fr/men/ready-to-wear/blazers/', '남성 - Ready To Wear - Blazers', '패션의류>남성의류>아우터>재킷', '50021640', NULL, NULL, 'bcm499', 'smartstore_2'),
('Brunello', 'https://shop.brunellocucinelli.com/en-fr/men/ready-to-wear/suits/', '남성 - Ready To Wear - Suits', '패션의류>남성의류>정장세트', '50000840', NULL, NULL, 'bcm499', 'smartstore_2'),
('Brunello', 'https://shop.brunellocucinelli.com/en-fr/men/ready-to-wear/tuxedos/', '남성 - Ready To Wear - Tuxedos', '패션의류>남성의류>정장세트', '50000840', NULL, NULL, 'bcm499', 'smartstore_2'),
('Brunello', 'https://shop.brunellocucinelli.com/en-fr/men/ready-to-wear/t-shirts-polos/', '남성 - Ready To Wear - T-shirts & Polos', '패션의류>남성의류>티셔츠', '50000830', NULL, NULL, 'bcm499', 'smartstore_2'),
('Brunello', 'https://shop.brunellocucinelli.com/en-fr/men/ready-to-wear/shirts/', '남성 - Ready To Wear - Shirts', '패션의류>남성의류>셔츠/남방', '50000833', NULL, NULL, 'bcm499', 'smartstore_2'),
('Brunello', 'https://shop.brunellocucinelli.com/en-fr/men/ready-to-wear/pants/', '남성 - Ready To Wear - Pants', '패션의류>남성의류>바지', '50000836', NULL, NULL, 'bcm499', 'smartstore_2'),
('Brunello', 'https://shop.brunellocucinelli.com/en-fr/men/shoes/sneakers/', '남성 - Shoes - Sneakers', '패션잡화>남성신발>스니커즈', '50000788', NULL, NULL, 'bcm499', 'smartstore_2'),
('Brunello', 'https://shop.brunellocucinelli.com/en-fr/men/shoes/lace-ups/', '남성 - Shoes - Lace-ups', '패션잡화>남성신발>구두', '50000787', NULL, NULL, 'bcm499', 'smartstore_2'),
('Brunello', 'https://shop.brunellocucinelli.com/en-fr/men/shoes/loafers/', '남성 - Shoes - Loafers', '패션잡화>남성신발>구두', '50000787', NULL, NULL, 'bcm499', 'smartstore_2'),
('Brunello', 'https://shop.brunellocucinelli.com/en-fr/men/shoes/espadrilles/', '남성 - Shoes - Espadrilles', '패션잡화>남성신발>슬립온', '50000783', NULL, NULL, 'bcm499', 'smartstore_2'),
('Brunello', 'https://shop.brunellocucinelli.com/en-fr/men/shoes/slides-flip-flops/', '남성 - Shoes - Slides & Flip Flops', '패션잡화>남성신발>슬리퍼', '50000790', NULL, NULL, 'bcm499', 'smartstore_2'),
('Brunello', 'https://shop.brunellocucinelli.com/en-fr/men/accessories/mens-eyewear/', '남성 - Accessories - Eyewear', '패션잡화>선글라스/안경테>선글라스', '50000554', NULL, NULL, 'bcm499', 'smartstore_2'),
('Brunello', 'https://shop.brunellocucinelli.com/en-fr/men/accessories/small-leather-goods/', '남성 - Accessories - Small Leather Goods', '패션잡화>지갑>남성지갑>반지갑', '50003985', NULL, NULL, 'bcm499', 'smartstore_2'),
('Brunello', 'https://shop.brunellocucinelli.com/en-fr/men/accessories/bags/', '남성 - Accessories - Bags', '패션잡화>남성가방>토트백', '50000647', NULL, NULL, 'bcm499', 'smartstore_2'),
('Brunello', 'https://shop.brunellocucinelli.com/en-fr/men/accessories/scarves/', '남성 - Accessories - Scarves', '패션잡화>패션소품>스카프>롱', '50004010', NULL, NULL, 'bcm499', 'smartstore_2'),
('Brunello', 'https://shop.brunellocucinelli.com/en-fr/men/accessories/hats/', '남성 - Accessories - Hats', '패션잡화>모자>비니', '50000543', NULL, NULL, 'bcm499', 'smartstore_2'),
('Brunello', 'https://shop.brunellocucinelli.com/en-fr/men/accessories/belts/', '남성 - Accessories - Belts', '패션잡화>벨트>남성벨트>캐주얼벨트', '50003989', NULL, NULL, 'bcm499', 'smartstore_2');
