INSERT INTO mapping (
  site,
  "siteUrl",
  "categoryName",
  "godoMallCategoryName",
  "godoMallCategoryCode",
  designers,
  "afterDesigners",
  "customId",
  "accountPlatform"
)
VALUES
('Burberry', 'https://de.burberry.com/l/damen-maentel-jacken/', '여성 코트 · 재킷 - 코트 · 재킷', '패션의류>여성의류>아우터>재킷', '50021360', NULL, NULL, 'bcm499', 'smartstore_2'),
('Burberry', 'https://de.burberry.com/l/damenbekleidung/strickdesigns/', '여성 코트 · 재킷 - 니트웨어', '패션의류>여성의류>니트>풀오버', '50021299', NULL, NULL, 'bcm499', 'smartstore_2'),
('Burberry', 'https://de.burberry.com/l/damenbekleidung/poloshirts-t-shirts/', '여성 코트 · 재킷 - 폴로 · 티셔츠', '패션의류>여성의류>티셔츠', '50000803', NULL, NULL, 'bcm499', 'smartstore_2'),
('Burberry', 'https://de.burberry.com/l/damenbekleidung/blusen-oberteile/', '여성 코트 · 재킷 - 셔츠 · 탑', '패션의류>여성의류>블라우스/셔츠', '50000804', NULL, NULL, 'bcm499', 'smartstore_2'),
('Burberry', 'https://de.burberry.com/l/damenbekleidung/kleider/', '여성 코트 · 재킷 - 드레스', '패션의류>여성의류>원피스', '50000807', NULL, NULL, 'bcm499', 'smartstore_2'),
('Burberry', 'https://de.burberry.com/l/damenbekleidung/roecke/', '여성 코트 · 재킷 - 스커트', '패션의류>여성의류>스커트', '50000808', NULL, NULL, 'bcm499', 'smartstore_2'),
('Burberry', 'https://de.burberry.com/l/damenbekleidung/sweatshirts/', '여성 코트 · 재킷 - 후디 ∙ 스웨트셔츠', '패션의류>여성의류>티셔츠', '50000803', NULL, NULL, 'bcm499', 'smartstore_2'),
('Burberry', 'https://de.burberry.com/l/damenbekleidung/blazer-elegante-hosen/', '여성 코트 · 재킷 - 블레이저 · 테일러링', '패션의류>여성의류>아우터>재킷', '50021360', NULL, NULL, 'bcm499', 'smartstore_2'),
('Burberry', 'https://de.burberry.com/l/damenbekleidung/hosen-shorts/', '여성 코트 · 재킷 - 팬츠 · 쇼츠', '패션의류>여성의류>바지', '50000810', NULL, NULL, 'bcm499', 'smartstore_2'),
('Burberry', 'https://de.burberry.com/l/damentaschen/henkeltaschen/', '여성 가방 - 토트 백', '패션잡화>여성가방>토트백', '50000640', NULL, NULL, 'bcm499', 'smartstore_2'),
('Burberry', 'https://de.burberry.com/l/damentaschen/crossbody-taschen/', '여성 가방 - 크로스바디 백', '패션잡화>여성가방>크로스백', '50000641', NULL, NULL, 'bcm499', 'smartstore_2'),
('Burberry', 'https://de.burberry.com/l/damentaschen/schultertaschen/', '여성 가방 - 숄더 백', '패션잡화>여성가방>숄더백', '50000639', NULL, NULL, 'bcm499', 'smartstore_2'),
('Burberry', 'https://de.burberry.com/l/damentaschen/griff-an-der-oberseite/', '여성 가방 - 탑 핸들 백', '패션잡화>여성가방>토트백', '50000640', NULL, NULL, 'bcm499', 'smartstore_2'),
('Burberry', 'https://de.burberry.com/l/damentaschen/rucksaecke/', '여성 가방 - 백팩', '패션잡화>여성가방>백팩', '50000644', NULL, NULL, 'bcm499', 'smartstore_2'),
('Burberry', 'https://de.burberry.com/l/damenschuhe/sneaker/', '여성 슈즈 - 스니커즈', '패션잡화>여성신발>단화>스니커즈', '50003822', NULL, NULL, 'bcm499', 'smartstore_2'),
('Burberry', 'https://de.burberry.com/l/damenschuhe/sandalen/', '여성 슈즈 - 샌들', '패션잡화>여성신발>샌들>스트랩샌들', '50003842', NULL, NULL, 'bcm499', 'smartstore_2'),
('Burberry', 'https://de.burberry.com/l/damenschuhe/loafer-ballerinas/', '여성 슈즈 - 로퍼 ∙ 발레리나', '패션잡화>여성신발>단화>로퍼', '50003818', NULL, NULL, 'bcm499', 'smartstore_2'),
('Burberry', 'https://de.burberry.com/l/damenschuhe/stiefel/', '여성 슈즈 - 부츠', '패션잡화>여성신발>부츠>앵클/숏부츠', '50004191', NULL, NULL, 'bcm499', 'smartstore_2'),
('Burberry', 'https://de.burberry.com/l/damenschuhe/pumps/', '여성 슈즈 - 펌프스', '패션잡화>여성신발>힐/펌프스>펌프스', '50003830', NULL, NULL, 'bcm499', 'smartstore_2'),
('Burberry', 'https://de.burberry.com/l/accessoires-fuer-damen/schals/', '여성 선물 - 스카프', '패션잡화>패션소품>스카프>롱', '50004010', NULL, NULL, 'bcm499', 'smartstore_2'),
('Burberry', 'https://de.burberry.com/l/herren-maentel-jacken/', '남성 코트 · 재킷 - 코트 · 재킷', '패션의류>남성의류>아우터>재킷', '50021640', NULL, NULL, 'bcm499', 'smartstore_2'),
('Burberry', 'https://de.burberry.com/l/herrenbekleidung/poloshirts-t-shirts/poloshirts/', '남성 코트 · 재킷 - 폴로', '패션의류>남성의류>티셔츠', '50000830', NULL, NULL, 'bcm499', 'smartstore_2'),
('Burberry', 'https://de.burberry.com/l/herrenbekleidung/poloshirts-t-shirts/t-shirts/', '남성 코트 · 재킷 - 티셔츠', '패션의류>남성의류>티셔츠', '50000830', NULL, NULL, 'bcm499', 'smartstore_2'),
('Burberry', 'https://de.burberry.com/l/herrenbekleidung/kapuzenpullover-sweatshirts/', '남성 코트 · 재킷 - 후디 ∙ 스웨트셔츠', '패션의류>남성의류>티셔츠', '50000830', NULL, NULL, 'bcm499', 'smartstore_2'),
('Burberry', 'https://de.burberry.com/l/herrenbekleidung/hemden/', '남성 코트 · 재킷 - 셔츠', '패션의류>남성의류>셔츠/남방', '50000833', NULL, NULL, 'bcm499', 'smartstore_2'),
('Burberry', 'https://de.burberry.com/l/herrenbekleidung/strickdesigns/', '남성 코트 · 재킷 - 니트웨어', '패션의류>남성의류>니트>풀오버', '50021579', NULL, NULL, 'bcm499', 'smartstore_2'),
('Burberry', 'https://de.burberry.com/l/herrenbekleidung/hosen-shorts/', '남성 코트 · 재킷 - 팬츠 · 쇼츠', '패션의류>남성의류>바지', '50000836', NULL, NULL, 'bcm499', 'smartstore_2'),
('Burberry', 'https://de.burberry.com/l/herrenbekleidung/blazer-elegante-hosen/', '남성 코트 · 재킷 - 블레이저 · 테일러링', '패션의류>남성의류>아우터>재킷', '50021640', NULL, NULL, 'bcm499', 'smartstore_2'),
('Burberry', 'https://de.burberry.com/l/herrentaschen/crossbody-taschen/', '남성 가방 - 크로스바디 백', '패션잡화>남성가방>크로스백', '50000648', NULL, NULL, 'bcm499', 'smartstore_2'),
('Burberry', 'https://de.burberry.com/l/herrentaschen/rucksaecke/', '남성 가방 - 백팩', '패션잡화>남성가방>백팩', '50000651', NULL, NULL, 'bcm499', 'smartstore_2'),
('Burberry', 'https://de.burberry.com/l/herrentaschen/bauchtaschen/', '남성 가방 - 벨트 백', '패션잡화>남성가방>힙색/슬링백', '50000652', NULL, NULL, 'bcm499', 'smartstore_2'),
('Burberry', 'https://de.burberry.com/l/herrentaschen/henkeltaschen/', '남성 가방 - 토트 백', '패션잡화>남성가방>토트백', '50000647', NULL, NULL, 'bcm499', 'smartstore_2'),
('Burberry', 'https://de.burberry.com/l/herrentaschen/aktentaschen/', '남성 가방 - 브리프케이스', '패션잡화>남성가방>브리프케이스', '50000650', NULL, NULL, 'bcm499', 'smartstore_2'),
('Burberry', 'https://de.burberry.com/l/herrenschuhe/sneaker/', '남성 슈즈 - 스니커즈', '패션잡화>남성신발>스니커즈', '50000788', NULL, NULL, 'bcm499', 'smartstore_2'),
('Burberry', 'https://de.burberry.com/l/herrenschuhe/sandalen/', '남성 슈즈 - 샌들', '패션잡화>남성신발>샌들', '50000789', NULL, NULL, 'bcm499', 'smartstore_2'),
('Burberry', 'https://de.burberry.com/l/herrenschuhe/stiefel/', '남성 슈즈 - 부츠', '패션잡화>남성신발>부츠>앵클/숏부츠', '50021999', NULL, NULL, 'bcm499', 'smartstore_2'),
('Burberry', 'https://de.burberry.com/l/herrenschuhe/loafer-schnuerschuhe/', '남성 슈즈 - 로퍼 ∙ 레이스업', '패션잡화>남성신발>구두', '50000787', NULL, NULL, 'bcm499', 'smartstore_2'),
('Burberry', 'https://de.burberry.com/l/accessoires-fuer-herren/schals/', '남성 선물 - 스카프', '패션잡화>패션소품>스카프>롱', '50004010', NULL, NULL, 'bcm499', 'smartstore_2')
ON CONFLICT (site, "siteUrl", "godoMallCategoryCode", "customId", "accountPlatform")
DO UPDATE SET
  "categoryName" = EXCLUDED."categoryName",
  "godoMallCategoryName" = EXCLUDED."godoMallCategoryName",
  designers = EXCLUDED.designers,
  "afterDesigners" = EXCLUDED."afterDesigners";
