INSERT INTO mapping (
  site,
  "siteUrl",
  "categoryName",
  "godoMallCategoryName",
  "godoMallCategoryCode",
  designers,
  "afterDesigners",
  "customId",
  "accountPlatform"
) VALUES
('Celine', 'https://www.celine.com/en-de/women/handbags/cross-body-bags/', 'women - handbags - cross-body-bags', '패션잡화>여성가방>크로스백', '50000641', NULL, NULL, 'bcm499', 'smartstore_2'),
('Celine', 'https://www.celine.com/en-de/women/handbags/shoulder-bags/', 'women - handbags - shoulder-bags', '패션잡화>여성가방>숄더백', '50000639', NULL, NULL, 'bcm499', 'smartstore_2'),
('Celine', 'https://www.celine.com/en-de/women/handbags/top-handle-bags/', 'women - handbags - top-handle-bags', '패션잡화>여성가방>토트백', '50000640', NULL, NULL, 'bcm499', 'smartstore_2'),
('Celine', 'https://www.celine.com/en-de/women/handbags/hobo-and-tote-bags/', 'women - handbags - hobo-and-tote-bags', '패션잡화>여성가방>토트백', '50000640', NULL, NULL, 'bcm499', 'smartstore_2'),
('Celine', 'https://www.celine.com/en-de/women/small-leather-goods/wallets/', 'women - small-leather-goods - wallets', '패션잡화>지갑>여성지갑>반지갑', '50003982', NULL, NULL, 'bcm499', 'smartstore_2'),
('Celine', 'https://www.celine.com/en-de/women/small-leather-goods/coin-and-card-holders/', 'women - small-leather-goods - coin-and-card-holders', '패션잡화>지갑>카드/명함지갑', '50000662', NULL, NULL, 'bcm499', 'smartstore_2'),
('Celine', 'https://www.celine.com/en-de/women/small-leather-goods/pouches-and-tech-accessories/', 'women - small-leather-goods - pouches-and-tech-accessories', '패션잡화>여성가방>파우치', '50000643', NULL, NULL, 'bcm499', 'smartstore_2'),
('Celine', 'https://www.celine.com/en-de/women/ready-to-wear/shirts-and-tops/', 'women - ready-to-wear - shirts-and-tops', '패션의류>여성의류>블라우스/셔츠', '50000804', NULL, NULL, 'bcm499', 'smartstore_2'),
('Celine', 'https://www.celine.com/en-de/women/ready-to-wear/pants-and-shorts/', 'women - ready-to-wear - pants-and-shorts', '패션의류>여성의류>바지', '50000810', NULL, NULL, 'bcm499', 'smartstore_2'),
('Celine', 'https://www.celine.com/en-de/women/ready-to-wear/jackets/', 'women - ready-to-wear - jackets', '패션의류>여성의류>아우터>재킷', '50021360', NULL, NULL, 'bcm499', 'smartstore_2'),
('Celine', 'https://www.celine.com/en-de/women/ready-to-wear/coats/', 'women - ready-to-wear - coats', '패션의류>여성의류>아우터>재킷', '50021360', NULL, NULL, 'bcm499', 'smartstore_2'),
('Celine', 'https://www.celine.com/en-de/women/ready-to-wear/knitwear/', 'women - ready-to-wear - knitwear', '패션의류>여성의류>니트>풀오버', '50021299', NULL, NULL, 'bcm499', 'smartstore_2'),
('Celine', 'https://www.celine.com/en-de/women/ready-to-wear/t-shirts-and-sweatshirts/', 'women - ready-to-wear - t-shirts-and-sweatshirts', '패션의류>여성의류>티셔츠', '50000803', NULL, NULL, 'bcm499', 'smartstore_2'),
('Celine', 'https://www.celine.com/en-de/women/shoes/the-flat/', 'women - shoes - the-flat', '패션잡화>여성신발>단화>플랫', '50003817', NULL, NULL, 'bcm499', 'smartstore_2'),
('Celine', 'https://www.celine.com/en-de/women/shoes/ballet/', 'women - shoes - ballet', '패션잡화>여성신발>단화>플랫', '50003817', NULL, NULL, 'bcm499', 'smartstore_2'),
('Celine', 'https://www.celine.com/en-de/women/shoes/triomphe-slide/', 'women - shoes - triomphe-slide', '패션잡화>여성신발>슬리퍼', '50000780', NULL, NULL, 'bcm499', 'smartstore_2'),
('Celine', 'https://www.celine.com/en-de/women/shoes/sandals/', 'women - shoes - sandals', '패션잡화>여성신발>샌들>스트랩샌들', '50003842', NULL, NULL, 'bcm499', 'smartstore_2'),
('Celine', 'https://www.celine.com/en-de/women/shoes/loafers-and-flats/', 'women - shoes - loafers-and-flats', '패션잡화>여성신발>단화>로퍼', '50003818', NULL, NULL, 'bcm499', 'smartstore_2'),
('Celine', 'https://www.celine.com/en-de/women/shoes/sneakers/', 'women - shoes - sneakers', '패션잡화>여성신발>단화>스니커즈', '50003822', NULL, NULL, 'bcm499', 'smartstore_2'),
('Celine', 'https://www.celine.com/en-de/women/shoes/pumps/', 'women - shoes - pumps', '패션잡화>여성신발>힐/펌프스>펌프스', '50003830', NULL, NULL, 'bcm499', 'smartstore_2'),
('Celine', 'https://www.celine.com/en-de/women/shoes/boots-and-ankle-boots/', 'women - shoes - boots-and-ankle-boots', '패션잡화>여성신발>부츠>앵클/숏부츠', '50004191', NULL, NULL, 'bcm499', 'smartstore_2'),
('Celine', 'https://www.celine.com/en-de/women/accessories/belts/', 'women - accessories - belts', '패션잡화>벨트>여성벨트', '50000539', NULL, NULL, 'bcm499', 'smartstore_2'),
('Celine', 'https://www.celine.com/en-de/women/accessories/sunglasses/', 'women - accessories - sunglasses', '패션잡화>선글라스/안경테>선글라스', '50000554', NULL, NULL, 'bcm499', 'smartstore_2'),
('Celine', 'https://www.celine.com/en-de/women/accessories/silk-squares-and-accessories/', 'women - accessories - silk-squares-and-accessories', '패션잡화>패션소품>스카프>롱', '50004010', NULL, NULL, 'bcm499', 'smartstore_2'),
('Celine', 'https://www.celine.com/en-de/women/accessories/scarves-and-shawls/', 'women - accessories - scarves-and-shawls', '패션잡화>패션소품>스카프>롱', '50004010', NULL, NULL, 'bcm499', 'smartstore_2'),
('Celine', 'https://www.celine.com/en-de/women/accessories/hair-accessories/', 'women - accessories - hair-accessories', '패션잡화>헤어액세서리>헤어액세서리소품', '50000563', NULL, NULL, 'bcm499', 'smartstore_2'),
('Celine', 'https://www.celine.com/en-de/women/jewellery/earrings/', 'women - jewellery - earrings', '패션잡화>주얼리>귀걸이>패션귀걸이', '50004164', NULL, NULL, 'bcm499', 'smartstore_2'),
('Celine', 'https://www.celine.com/en-de/women/jewellery/bracelets/', 'women - jewellery - bracelets', '패션잡화>주얼리>팔찌>패션팔찌', '50004194', NULL, NULL, 'bcm499', 'smartstore_2'),
('Celine', 'https://www.celine.com/en-de/women/jewellery/necklaces/', 'women - jewellery - necklaces', '패션잡화>주얼리>목걸이>패션목걸이', '50004174', NULL, NULL, 'bcm499', 'smartstore_2'),
('Celine', 'https://www.celine.com/en-de/women/jewellery/rings/', 'women - jewellery - rings', '패션잡화>주얼리>반지>패션반지', '50004155', NULL, NULL, 'bcm499', 'smartstore_2'),
('Celine', 'https://www.celine.com/en-de/men/bags/cross-body-bags/', 'men - bags - cross-body-bags', '패션잡화>남성가방>크로스백', '50000648', NULL, NULL, 'bcm499', 'smartstore_2'),
('Celine', 'https://www.celine.com/en-de/men/bags/tote-bags/', 'men - bags - tote-bags', '패션잡화>남성가방>토트백', '50000647', NULL, NULL, 'bcm499', 'smartstore_2'),
('Celine', 'https://www.celine.com/en-de/men/bags/backpacks-1/', 'men - bags - backpacks-1', '패션잡화>남성가방>백팩', '50000651', NULL, NULL, 'bcm499', 'smartstore_2'),
('Celine', 'https://www.celine.com/en-de/men/small-leather-goods/wallets/', 'men - small-leather-goods - wallets', '패션잡화>지갑>남성지갑>반지갑', '50003985', NULL, NULL, 'bcm499', 'smartstore_2'),
('Celine', 'https://www.celine.com/en-de/men/small-leather-goods/coin-and-card-holders/', 'men - small-leather-goods - coin-and-card-holders', '패션잡화>지갑>카드/명함지갑', '50000662', NULL, NULL, 'bcm499', 'smartstore_2'),
('Celine', 'https://www.celine.com/en-de/men/ready-to-wear/shirts/', 'men - ready-to-wear - shirts', '패션의류>남성의류>셔츠/남방', '50000833', NULL, NULL, 'bcm499', 'smartstore_2'),
('Celine', 'https://www.celine.com/en-de/men/ready-to-wear/t-shirts-and-sweatshirts/', 'men - ready-to-wear - t-shirts-and-sweatshirts', '패션의류>남성의류>티셔츠', '50000830', NULL, NULL, 'bcm499', 'smartstore_2'),
('Celine', 'https://www.celine.com/en-de/men/ready-to-wear/knitwear/', 'men - ready-to-wear - knitwear', '패션의류>남성의류>니트>풀오버', '50021579', NULL, NULL, 'bcm499', 'smartstore_2'),
('Celine', 'https://www.celine.com/en-de/men/ready-to-wear/pants-and-shorts/', 'men - ready-to-wear - pants-and-shorts', '패션의류>남성의류>바지', '50000836', NULL, NULL, 'bcm499', 'smartstore_2'),
('Celine', 'https://www.celine.com/en-de/men/ready-to-wear/coats-and-blousons/', 'men - ready-to-wear - coats-and-blousons', '패션의류>남성의류>아우터>재킷', '50021640', NULL, NULL, 'bcm499', 'smartstore_2'),
('Celine', 'https://www.celine.com/en-de/men/shoes/derbies-and-mocassins/', 'men - shoes - derbies-and-mocassins', '패션잡화>남성신발>구두', '50000787', NULL, NULL, 'bcm499', 'smartstore_2'),
('Celine', 'https://www.celine.com/en-de/men/shoes/sneakers/', 'men - shoes - sneakers', '패션잡화>남성신발>스니커즈', '50000788', NULL, NULL, 'bcm499', 'smartstore_2'),
('Celine', 'https://www.celine.com/en-de/men/shoes/sandals/', 'men - shoes - sandals', '패션잡화>남성신발>샌들', '50000789', NULL, NULL, 'bcm499', 'smartstore_2'),
('Celine', 'https://www.celine.com/en-de/men/shoes/boots/', 'men - shoes - boots', '패션잡화>남성신발>부츠>앵클/숏부츠', '50021999', NULL, NULL, 'bcm499', 'smartstore_2'),
('Celine', 'https://www.celine.com/en-de/men/accessories/sunglasses/', 'men - accessories - sunglasses', '패션잡화>선글라스/안경테>선글라스', '50000554', NULL, NULL, 'bcm499', 'smartstore_2'),
('Celine', 'https://www.celine.com/en-de/men/accessories/belts/', 'men - accessories - belts', '패션잡화>벨트>남성벨트>캐주얼벨트', '50003989', NULL, NULL, 'bcm499', 'smartstore_2'),
('Celine', 'https://www.celine.com/en-de/men/jewellery/necklaces/', 'men - jewellery - necklaces', '패션잡화>주얼리>목걸이>패션목걸이', '50004174', NULL, NULL, 'bcm499', 'smartstore_2'),
('Celine', 'https://www.celine.com/en-de/men/jewellery/earrings/', 'men - jewellery - earrings', '패션잡화>주얼리>귀걸이>패션귀걸이', '50004164', NULL, NULL, 'bcm499', 'smartstore_2');
