INSERT INTO mapping (
  site,
  "siteUrl",
  "categoryName",
  "godoMallCategoryName",
  "godoMallCategoryCode",
  designers,
  "afterDesigners",
  "customId",
  "accountPlatform"
) VALUES
('Fendi', 'https://www.fendi.com/de-en/woman/bags/backpacks', 'woman - bags - backpacks', '패션잡화>여성가방>백팩', '50000644', NULL, NULL, 'bcm499', 'smartstore_2'),
('Fendi', 'https://www.fendi.com/de-en/woman/bags/shoulder-crossbody-bags', 'woman - bags - shoulder-crossbody-bags', '패션잡화>여성가방>숄더백', '50000639', NULL, NULL, 'bcm499', 'smartstore_2'),
('Fendi', 'https://www.fendi.com/de-en/woman/bags/tote-bags', 'woman - bags - tote-bags', '패션잡화>여성가방>토트백', '50000640', NULL, NULL, 'bcm499', 'smartstore_2'),
('Fendi', 'https://www.fendi.com/de-en/woman/bags/bucket-bags', 'woman - bags - bucket-bags', '패션잡화>여성가방>숄더백', '50000639', NULL, NULL, 'bcm499', 'smartstore_2'),
('Fendi', 'https://www.fendi.com/de-en/woman/bags/boston-bags', 'woman - bags - boston-bags', '패션잡화>여성가방>토트백', '50000640', NULL, NULL, 'bcm499', 'smartstore_2'),
('Fendi', 'https://www.fendi.com/de-en/woman/bags/clutches-pochette', 'woman - bags - clutches-pochette', '패션잡화>여성가방>클러치백', '50000642', NULL, NULL, 'bcm499', 'smartstore_2'),
('Fendi', 'https://www.fendi.com/de-en/woman/ready-to-wear/tops-shirts', 'woman - ready-to-wear - tops-shirts', '패션의류>여성의류>블라우스/셔츠', '50000804', NULL, NULL, 'bcm499', 'smartstore_2'),
('Fendi', 'https://www.fendi.com/de-en/woman/ready-to-wear/t-shirts-sweatshirts', 'woman - ready-to-wear - t-shirts-sweatshirts', '패션의류>여성의류>티셔츠', '50000803', NULL, NULL, 'bcm499', 'smartstore_2'),
('Fendi', 'https://www.fendi.com/de-en/woman/ready-to-wear/knitwear', 'woman - ready-to-wear - knitwear', '패션의류>여성의류>니트>풀오버', '50021299', NULL, NULL, 'bcm499', 'smartstore_2'),
('Fendi', 'https://www.fendi.com/de-en/woman/ready-to-wear/jackets', 'woman - ready-to-wear - jackets', '패션의류>여성의류>아우터>재킷', '50021360', NULL, NULL, 'bcm499', 'smartstore_2'),
('Fendi', 'https://www.fendi.com/de-en/woman/ready-to-wear/dresses', 'woman - ready-to-wear - dresses', '패션의류>여성의류>원피스', '50000807', NULL, NULL, 'bcm499', 'smartstore_2'),
('Fendi', 'https://www.fendi.com/de-en/woman/ready-to-wear/skirts', 'woman - ready-to-wear - skirts', '패션의류>여성의류>스커트', '50000808', NULL, NULL, 'bcm499', 'smartstore_2'),
('Fendi', 'https://www.fendi.com/de-en/woman/ready-to-wear/pants-shorts', 'woman - ready-to-wear - pants-shorts', '패션의류>여성의류>바지', '50000810', NULL, NULL, 'bcm499', 'smartstore_2'),
('Fendi', 'https://www.fendi.com/de-en/woman/ready-to-wear/coats-outerwear', 'woman - ready-to-wear - coats-outerwear', '패션의류>여성의류>아우터>재킷', '50021360', NULL, NULL, 'bcm499', 'smartstore_2'),
('Fendi', 'https://www.fendi.com/de-en/woman/shoes/sneakers', 'woman - shoes - sneakers', '패션잡화>여성신발>단화>스니커즈', '50003822', NULL, NULL, 'bcm499', 'smartstore_2'),
('Fendi', 'https://www.fendi.com/de-en/woman/shoes/slides', 'woman - shoes - slides', '패션잡화>여성신발>슬리퍼', '50000780', NULL, NULL, 'bcm499', 'smartstore_2'),
('Fendi', 'https://www.fendi.com/de-en/woman/shoes/sandals-mules', 'woman - shoes - sandals-mules', '패션잡화>여성신발>샌들>스트랩샌들', '50003842', NULL, NULL, 'bcm499', 'smartstore_2'),
('Fendi', 'https://www.fendi.com/de-en/woman/shoes/mocassins-loafers', 'woman - shoes - mocassins-loafers', '패션잡화>여성신발>단화>로퍼', '50003818', NULL, NULL, 'bcm499', 'smartstore_2'),
('Fendi', 'https://www.fendi.com/de-en/woman/shoes/pumps-slingbacks', 'woman - shoes - pumps-slingbacks', '패션잡화>여성신발>힐/펌프스>펌프스', '50003830', NULL, NULL, 'bcm499', 'smartstore_2'),
('Fendi', 'https://www.fendi.com/de-en/woman/shoes/boots-ankle-boots', 'woman - shoes - boots-ankle-boots', '패션잡화>여성신발>부츠>앵클/숏부츠', '50004191', NULL, NULL, 'bcm499', 'smartstore_2'),
('Fendi', 'https://www.fendi.com/de-en/woman/fashion-jewellery/earrings', 'woman - fashion-jewellery - earrings', '패션잡화>주얼리>귀걸이>패션귀걸이', '50004164', NULL, NULL, 'bcm499', 'smartstore_2'),
('Fendi', 'https://www.fendi.com/de-en/woman/fashion-jewellery/rings', 'woman - fashion-jewellery - rings', '패션잡화>주얼리>반지>패션반지', '50004155', NULL, NULL, 'bcm499', 'smartstore_2'),
('Fendi', 'https://www.fendi.com/de-en/woman/fashion-jewellery/bracelets', 'woman - fashion-jewellery - bracelets', '패션잡화>주얼리>팔찌>패션팔찌', '50004194', NULL, NULL, 'bcm499', 'smartstore_2'),
('Fendi', 'https://www.fendi.com/de-en/woman/fashion-jewellery/necklaces', 'woman - fashion-jewellery - necklaces', '패션잡화>주얼리>목걸이>패션목걸이', '50004174', NULL, NULL, 'bcm499', 'smartstore_2'),
('Fendi', 'https://www.fendi.com/de-en/woman/accessories/sunglasses', 'woman - accessories - sunglasses', '패션잡화>선글라스/안경테>선글라스', '50000554', NULL, NULL, 'bcm499', 'smartstore_2'),
('Fendi', 'https://www.fendi.com/de-en/woman/accessories/silk-scarves', 'woman - accessories - silk-scarves', '패션잡화>패션소품>스카프>롱', '50004010', NULL, NULL, 'bcm499', 'smartstore_2'),
('Fendi', 'https://www.fendi.com/de-en/woman/accessories/scarves-ponchos', 'woman - accessories - scarves-ponchos', '패션잡화>패션소품>스카프>롱', '50004010', NULL, NULL, 'bcm499', 'smartstore_2'),
('Fendi', 'https://www.fendi.com/de-en/woman/accessories/belts', 'woman - accessories - belts', '패션잡화>벨트>여성벨트', '50000539', NULL, NULL, 'bcm499', 'smartstore_2'),
('Fendi', 'https://www.fendi.com/de-en/woman/accessories/hair-accessories', 'woman - accessories - hair-accessories', '패션잡화>헤어액세서리>헤어액세서리소품', '50000563', NULL, NULL, 'bcm499', 'smartstore_2'),
('Fendi', 'https://www.fendi.com/de-en/woman/small-leather-goods_1/wallets', 'woman - small-leather-goods_1 - wallets', '패션잡화>지갑>여성지갑>반지갑', '50003982', NULL, NULL, 'bcm499', 'smartstore_2'),
('Fendi', 'https://www.fendi.com/de-en/woman/small-leather-goods_1/card-holders', 'woman - small-leather-goods_1 - card-holders', '패션잡화>지갑>카드/명함지갑', '50000662', NULL, NULL, 'bcm499', 'smartstore_2'),
('Fendi', 'https://www.fendi.com/de-en/woman/small-leather-goods_1/pouches', 'woman - small-leather-goods_1 - pouches', '패션잡화>여성가방>파우치', '50000643', NULL, NULL, 'bcm499', 'smartstore_2'),
('Fendi', 'https://www.fendi.com/de-en/man/ready-to-wear/t-shirts-polos', 'man - ready-to-wear - t-shirts-polos', '패션의류>남성의류>티셔츠', '50000830', NULL, NULL, 'bcm499', 'smartstore_2'),
('Fendi', 'https://www.fendi.com/de-en/man/ready-to-wear/shirts', 'man - ready-to-wear - shirts', '패션의류>남성의류>셔츠/남방', '50000833', NULL, NULL, 'bcm499', 'smartstore_2'),
('Fendi', 'https://www.fendi.com/de-en/man/ready-to-wear/knitwear', 'man - ready-to-wear - knitwear', '패션의류>남성의류>니트>풀오버', '50021579', NULL, NULL, 'bcm499', 'smartstore_2'),
('Fendi', 'https://www.fendi.com/de-en/man/ready-to-wear/denim-trousers', 'man - ready-to-wear - denim-trousers', '패션의류>남성의류>바지', '50000836', NULL, NULL, 'bcm499', 'smartstore_2'),
('Fendi', 'https://www.fendi.com/de-en/man/ready-to-wear/coats-outerwear', 'man - ready-to-wear - coats-outerwear', '패션의류>남성의류>아우터>재킷', '50021640', NULL, NULL, 'bcm499', 'smartstore_2'),
('Fendi', 'https://www.fendi.com/de-en/man/ready-to-wear/jackets-suits', 'man - ready-to-wear - jackets-suits', '패션의류>남성의류>아우터>재킷', '50021640', NULL, NULL, 'bcm499', 'smartstore_2'),
('Fendi', 'https://www.fendi.com/de-en/man/ready-to-wear/coordinated-sets', 'man - ready-to-wear - coordinated-sets', '패션의류>남성의류>정장세트', '50000840', NULL, NULL, 'bcm499', 'smartstore_2'),
('Fendi', 'https://www.fendi.com/de-en/man/shoes/sneakers', 'man - shoes - sneakers', '패션잡화>남성신발>스니커즈', '50000788', NULL, NULL, 'bcm499', 'smartstore_2'),
('Fendi', 'https://www.fendi.com/de-en/man/shoes/loafers-drivers', 'man - shoes - loafers-drivers', '패션잡화>남성신발>구두', '50000787', NULL, NULL, 'bcm499', 'smartstore_2'),
('Fendi', 'https://www.fendi.com/de-en/man/shoes/lace-ups-boots', 'man - shoes - lace-ups-boots', '패션잡화>남성신발>구두', '50000787', NULL, NULL, 'bcm499', 'smartstore_2'),
('Fendi', 'https://www.fendi.com/de-en/man/shoes/slides-sandals', 'man - shoes - slides-sandals', '패션잡화>남성신발>샌들', '50000789', NULL, NULL, 'bcm499', 'smartstore_2'),
('Fendi', 'https://www.fendi.com/de-en/man/bags/pouches', 'man - bags - pouches', '패션잡화>남성가방>클러치백', '50000649', NULL, NULL, 'bcm499', 'smartstore_2'),
('Fendi', 'https://www.fendi.com/de-en/man/bags/tote-bags', 'man - bags - tote-bags', '패션잡화>남성가방>토트백', '50000647', NULL, NULL, 'bcm499', 'smartstore_2'),
('Fendi', 'https://www.fendi.com/de-en/man/small-leather-goods_1/wallets', 'man - small-leather-goods_1 - wallets', '패션잡화>지갑>남성지갑>반지갑', '50003985', NULL, NULL, 'bcm499', 'smartstore_2'),
('Fendi', 'https://www.fendi.com/de-en/man/small-leather-goods_1/card-holders', 'man - small-leather-goods_1 - card-holders', '패션잡화>지갑>카드/명함지갑', '50000662', NULL, NULL, 'bcm499', 'smartstore_2'),
('Fendi', 'https://www.fendi.com/de-en/man/small-leather-goods_1/pouches-other-accessories', 'man - small-leather-goods_1 - pouches-other-accessories', '패션잡화>남성가방>클러치백', '50000649', NULL, NULL, 'bcm499', 'smartstore_2'),
('Fendi', 'https://www.fendi.com/de-en/man/accessories/sunglasses', 'man - accessories - sunglasses', '패션잡화>선글라스/안경테>선글라스', '50000554', NULL, NULL, 'bcm499', 'smartstore_2'),
('Fendi', 'https://www.fendi.com/de-en/man/accessories/belts', 'man - accessories - belts', '패션잡화>벨트>남성벨트>캐주얼벨트', '50003989', NULL, NULL, 'bcm499', 'smartstore_2'),
('Fendi', 'https://www.fendi.com/de-en/man/accessories/scarves', 'man - accessories - scarves', '패션잡화>패션소품>스카프>롱', '50004010', NULL, NULL, 'bcm499', 'smartstore_2'),
('Fendi', 'https://www.fendi.com/de-en/man/accessories/ties', 'man - accessories - ties', '패션잡화>패션소품>넥타이>기본넥타이', '50004014', NULL, NULL, 'bcm499', 'smartstore_2'),
('Fendi', 'https://www.fendi.com/de-en/man/fashion-jewellery/bracelets', 'man - fashion-jewellery - bracelets', '패션잡화>주얼리>팔찌>패션팔찌', '50004194', NULL, NULL, 'bcm499', 'smartstore_2'),
('Fendi', 'https://www.fendi.com/de-en/man/fashion-jewellery/earrings', 'man - fashion-jewellery - earrings', '패션잡화>주얼리>귀걸이>패션귀걸이', '50004164', NULL, NULL, 'bcm499', 'smartstore_2'),
('Fendi', 'https://www.fendi.com/de-en/man/fashion-jewellery/necklaces', 'man - fashion-jewellery - necklaces', '패션잡화>주얼리>목걸이>패션목걸이', '50004174', NULL, NULL, 'bcm499', 'smartstore_2'),
('Fendi', 'https://www.fendi.com/de-en/man/fashion-jewellery/rings', 'man - fashion-jewellery - rings', '패션잡화>주얼리>반지>패션반지', '50004155', NULL, NULL, 'bcm499', 'smartstore_2');
