INSERT INTO mapping (
  site,
  "siteUrl",
  "categoryName",
  "godoMallCategoryName",
  "godoMallCategoryCode",
  designers,
  "afterDesigners",
  "customId",
  "accountPlatform"
) VALUES
('Ferragamo', 'https://www.ferragamo.com/shop/eu/en/women/shoes/pumps-24', 'Women - shoes - pumps', '패션잡화>여성신발>힐/펌프스>펌프스', '50003830', NULL, NULL, 'bcm499', 'smartstore_2'),
('Ferragamo', 'https://www.ferragamo.com/shop/eu/en/women/shoes/eu-slingbacks', 'Women - shoes - slingbacks', '패션잡화>여성신발>힐/펌프스>펌프스', '50003830', NULL, NULL, 'bcm499', 'smartstore_2'),
('Ferragamo', 'https://www.ferragamo.com/shop/eu/en/women/shoes/mules-slippers-oe', 'Women - shoes - mulesandslides', '패션잡화>여성신발>샌들>뮬/블로퍼', '50003847', NULL, NULL, 'bcm499', 'smartstore_2'),
('Ferragamo', 'https://www.ferragamo.com/shop/eu/en/women/shoes/mocassins', 'Women - shoes - moccasins', '패션잡화>여성신발>단화>로퍼', '50003818', NULL, NULL, 'bcm499', 'smartstore_2'),
('Ferragamo', 'https://www.ferragamo.com/shop/eu/en/women/shoes/ballerinas-flats', 'Women - shoes - ballerinas', '패션잡화>여성신발>단화>플랫', '50003817', NULL, NULL, 'bcm499', 'smartstore_2'),
('Ferragamo', 'https://www.ferragamo.com/shop/eu/en/women/shoes/oe-sandals-espadrilles', 'Women - shoes - sandalsandespadrilles', '패션잡화>여성신발>샌들>스트랩샌들', '50003842', NULL, NULL, 'bcm499', 'smartstore_2'),
('Ferragamo', 'https://www.ferragamo.com/shop/eu/en/women/shoes/sneakers', 'Women - shoes - sneakers', '패션잡화>여성신발>단화>스니커즈', '50003822', NULL, NULL, 'bcm499', 'smartstore_2'),
('Ferragamo', 'https://www.ferragamo.com/shop/eu/en/women/shoes/boots', 'Women - shoes - bootsandbooties', '패션잡화>여성신발>부츠>앵클/숏부츠', '50004191', NULL, NULL, 'bcm499', 'smartstore_2'),
('Ferragamo', 'https://www.ferragamo.com/shop/eu/en/women/handbags/top-handles', 'Women - handbags - tophandlesandsatchels', '패션잡화>여성가방>토트백', '50000640', NULL, NULL, 'bcm499', 'smartstore_2'),
('Ferragamo', 'https://www.ferragamo.com/shop/eu/en/women/handbags/shoulder-hobo-bags', 'Women - handbags - shoulderbagsandhobos', '패션잡화>여성가방>숄더백', '50000639', NULL, NULL, 'bcm499', 'smartstore_2'),
('Ferragamo', 'https://www.ferragamo.com/shop/eu/en/women/handbags/messenger-bags', 'Women - handbags - crossbodybags', '패션잡화>여성가방>크로스백', '50000641', NULL, NULL, 'bcm499', 'smartstore_2'),
('Ferragamo', 'https://www.ferragamo.com/shop/eu/en/women/handbags/tote-bags', 'Women - handbags - totes', '패션잡화>여성가방>토트백', '50000640', NULL, NULL, 'bcm499', 'smartstore_2'),
('Ferragamo', 'https://www.ferragamo.com/shop/eu/en/women/handbags/clutches-pochettes', 'Women - handbags - clutchesandeveningbags', '패션잡화>여성가방>클러치백', '50000642', NULL, NULL, 'bcm499', 'smartstore_2'),
('Ferragamo', 'https://www.ferragamo.com/shop/eu/en/women/rtw-women-oe/dresses-women-oe', 'Women - ready to wear - dresses', '패션의류>여성의류>원피스', '50000807', NULL, NULL, 'bcm499', 'smartstore_2'),
('Ferragamo', 'https://www.ferragamo.com/shop/eu/en/women/rtw-women-oe/knitwear-woman-oe', 'Women - ready to wear - knitwear', '패션의류>여성의류>니트>풀오버', '50021299', NULL, NULL, 'bcm499', 'smartstore_2'),
('Ferragamo', 'https://www.ferragamo.com/shop/eu/en/women/rtw-women-oe/tshirts-and-sweatshirts-women', 'Women - ready to wear - t-shirtsandsweatshirts', '패션의류>여성의류>티셔츠', '50000803', NULL, NULL, 'bcm499', 'smartstore_2'),
('Ferragamo', 'https://www.ferragamo.com/shop/eu/en/women/rtw-women-oe/topsshirts-women-oe', 'Women - ready to wear - topsandshirts', '패션의류>여성의류>블라우스/셔츠', '50000804', NULL, NULL, 'bcm499', 'smartstore_2'),
('Ferragamo', 'https://www.ferragamo.com/shop/eu/en/women/rtw-women-oe/skirts-women-oe', 'Women - ready to wear - skirts', '패션의류>여성의류>스커트', '50000808', NULL, NULL, 'bcm499', 'smartstore_2'),
('Ferragamo', 'https://www.ferragamo.com/shop/eu/en/women/rtw-women-oe/pants-women-oe', 'Women - ready to wear - pants', '패션의류>여성의류>바지', '50000810', NULL, NULL, 'bcm499', 'smartstore_2'),
('Ferragamo', 'https://www.ferragamo.com/shop/eu/en/women/rtw-women-oe/jacketandblazers-women-oe', 'Women - ready to wear - jackets', '패션의류>여성의류>아우터>재킷', '50021360', NULL, NULL, 'bcm499', 'smartstore_2'),
('Ferragamo', 'https://www.ferragamo.com/shop/eu/en/women/rtw-women-oe/outerwear-women-oe', 'Women - ready to wear - outerwear', '패션의류>여성의류>아우터>재킷', '50021360', NULL, NULL, 'bcm499', 'smartstore_2'),
('Ferragamo', 'https://www.ferragamo.com/shop/eu/en/women/wallets-small-leathers-goods/belts', 'Women - leather accessories - belts', '패션잡화>벨트>여성벨트', '50000539', NULL, NULL, 'bcm499', 'smartstore_2'),
('Ferragamo', 'https://www.ferragamo.com/shop/eu/en/women/wallets-small-leathers-goods/wallets-coin-purses', 'Women - leather accessories - walletsandcoinpurses', '패션잡화>지갑>여성지갑>반지갑', '50003982', NULL, NULL, 'bcm499', 'smartstore_2'),
('Ferragamo', 'https://www.ferragamo.com/shop/eu/en/women/wallets-small-leathers-goods/card-key-holders', 'Women - leather accessories - cardholders', '패션잡화>지갑>카드/명함지갑', '50000662', NULL, NULL, 'bcm499', 'smartstore_2'),
('Ferragamo', 'https://www.ferragamo.com/shop/eu/en/women/accessories/foulards', 'Women - soft accessories - silkscarvesandbandeau', '패션잡화>패션소품>스카프>롱', '50004010', NULL, NULL, 'bcm499', 'smartstore_2'),
('Ferragamo', 'https://www.ferragamo.com/shop/eu/en/women/accessories/stoles-w', 'Women - soft accessories - shawlsandstoles', '패션잡화>패션소품>숄', '50000567', NULL, NULL, 'bcm499', 'smartstore_2'),
('Ferragamo', 'https://www.ferragamo.com/shop/eu/en/women/accessories/hairaccessories', 'Women - soft accessories - hairaccessories', '패션잡화>헤어액세서리>헤어액세서리소품', '50000563', NULL, NULL, 'bcm499', 'smartstore_2'),
('Ferragamo', 'https://www.ferragamo.com/shop/eu/en/women/eyewear/sunglasses-women-eu-en', 'Women - eyewear - sunglasses', '패션잡화>선글라스/안경테>선글라스', '50000554', NULL, NULL, 'bcm499', 'smartstore_2'),
('Ferragamo', 'https://www.ferragamo.com/shop/eu/en/women/eyewear/optical-glasses-eu-en', 'Women - eyewear - opticalglasses', '패션잡화>선글라스/안경테>안경테', '50000556', NULL, NULL, 'bcm499', 'smartstore_2'),
('Ferragamo', 'https://www.ferragamo.com/shop/eu/en/men/man-shoes/drivers-men', 'Men - shoes - drivers', '패션잡화>남성신발>구두', '50000787', NULL, NULL, 'bcm499', 'smartstore_2'),
('Ferragamo', 'https://www.ferragamo.com/shop/eu/en/men/man-shoes/mocassins-loafers', 'Men - shoes - moccasinsandloafers', '패션잡화>남성신발>구두', '50000787', NULL, NULL, 'bcm499', 'smartstore_2'),
('Ferragamo', 'https://www.ferragamo.com/shop/eu/en/men/man-shoes/sandals', 'Men - shoes - sandals', '패션잡화>남성신발>샌들', '50000789', NULL, NULL, 'bcm499', 'smartstore_2'),
('Ferragamo', 'https://www.ferragamo.com/shop/eu/en/men/man-shoes/sneakers-', 'Men - shoes - sneakers', '패션잡화>남성신발>스니커즈', '50000788', NULL, NULL, 'bcm499', 'smartstore_2'),
('Ferragamo', 'https://www.ferragamo.com/shop/eu/en/men/man-shoes/lace-ups', 'Men - shoes - lace-upsandoxfords', '패션잡화>남성신발>구두', '50000787', NULL, NULL, 'bcm499', 'smartstore_2'),
('Ferragamo', 'https://www.ferragamo.com/shop/eu/en/men/man-shoes/monk-strap-oe', 'Men - shoes - monkstraps', '패션잡화>남성신발>구두', '50000787', NULL, NULL, 'bcm499', 'smartstore_2'),
('Ferragamo', 'https://www.ferragamo.com/shop/eu/en/men/man-shoes/boots-booties', 'Men - shoes - boots', '패션잡화>남성신발>부츠>앵클/숏부츠', '50021999', NULL, NULL, 'bcm499', 'smartstore_2'),
('Ferragamo', 'https://www.ferragamo.com/shop/eu/en/men/man-bags-luggage/messenger-and-shoulder-strap-bags', 'Men - bags - crossbodyandbeltbags', '패션잡화>남성가방>크로스백', '50000648', NULL, NULL, 'bcm499', 'smartstore_2'),
('Ferragamo', 'https://www.ferragamo.com/shop/eu/en/men/man-bags-luggage/business-bags', 'Men - bags - businessbags', '패션잡화>남성가방>브리프케이스', '50000650', NULL, NULL, 'bcm499', 'smartstore_2'),
('Ferragamo', 'https://www.ferragamo.com/shop/eu/en/men/man-bags-luggage/shoppers-oe', 'Men - bags - totebags', '패션잡화>남성가방>토트백', '50000647', NULL, NULL, 'bcm499', 'smartstore_2'),
('Ferragamo', 'https://www.ferragamo.com/shop/eu/en/men/man-bags-luggage/weekend-bags', 'Men - bags - backpacks', '패션잡화>남성가방>백팩', '50000651', NULL, NULL, 'bcm499', 'smartstore_2'),
('Ferragamo', 'https://www.ferragamo.com/shop/eu/en/men/man-bags-luggage/portfolios-clutches-oe', 'Men - bags - pouches', '패션잡화>남성가방>클러치백', '50000649', NULL, NULL, 'bcm499', 'smartstore_2'),
('Ferragamo', 'https://www.ferragamo.com/shop/eu/en/men/rtw-men-oe/shirts-men-oe', 'Men - ready to wear - shirts', '패션의류>남성의류>셔츠/남방', '50000833', NULL, NULL, 'bcm499', 'smartstore_2'),
('Ferragamo', 'https://www.ferragamo.com/shop/eu/en/men/rtw-men-oe/polo-tshirts-men-oe', 'Men - ready to wear - polosandt-shirts', '패션의류>남성의류>티셔츠', '50000830', NULL, NULL, 'bcm499', 'smartstore_2'),
('Ferragamo', 'https://www.ferragamo.com/shop/eu/en/men/rtw-men-oe/knitwear-men-oe', 'Men - ready to wear - knitwearandsweatshirts', '패션의류>남성의류>니트>풀오버', '50021579', NULL, NULL, 'bcm499', 'smartstore_2'),
('Ferragamo', 'https://www.ferragamo.com/shop/eu/en/men/rtw-men-oe/pantsandshorts-men-oe', 'Men - ready to wear - pants', '패션의류>남성의류>바지', '50000836', NULL, NULL, 'bcm499', 'smartstore_2'),
('Ferragamo', 'https://www.ferragamo.com/shop/eu/en/men/rtw-men-oe/blazers-men-oe', 'Men - ready to wear - blazersandsuits', '패션의류>남성의류>정장세트', '50000840', NULL, NULL, 'bcm499', 'smartstore_2'),
('Ferragamo', 'https://www.ferragamo.com/shop/eu/en/men/rtw-men-oe/jackets-men', 'Men - ready to wear - jackets', '패션의류>남성의류>아우터>재킷', '50021640', NULL, NULL, 'bcm499', 'smartstore_2'),
('Ferragamo', 'https://www.ferragamo.com/shop/eu/en/men/rtw-men-oe/outerwear-men-oe', 'Men - ready to wear - outerwear', '패션의류>남성의류>아우터>재킷', '50021640', NULL, NULL, 'bcm499', 'smartstore_2'),
('Ferragamo', 'https://www.ferragamo.com/shop/eu/en/men/man-wallets-small-leather-goods/man-belts', 'Men - leather accessories - belts', '패션잡화>벨트>남성벨트>캐주얼벨트', '50003989', NULL, NULL, 'bcm499', 'smartstore_2'),
('Ferragamo', 'https://www.ferragamo.com/shop/eu/en/men/man-wallets-small-leather-goods/wallet-coin-purses', 'Men - leather accessories - wallets', '패션잡화>지갑>남성지갑>반지갑', '50003985', NULL, NULL, 'bcm499', 'smartstore_2'),
('Ferragamo', 'https://www.ferragamo.com/shop/eu/en/men/man-wallets-small-leather-goods/card-case-key-holders', 'Men - leather accessories - cardholders', '패션잡화>지갑>카드/명함지갑', '50000662', NULL, NULL, 'bcm499', 'smartstore_2'),
('Ferragamo', 'https://www.ferragamo.com/shop/eu/en/men/man-wallets-small-leather-goods/dopp-kit-other-accessories', 'Men - leather accessories - pouches', '패션잡화>남성가방>클러치백', '50000649', NULL, NULL, 'bcm499', 'smartstore_2'),
('Ferragamo', 'https://www.ferragamo.com/shop/eu/en/men/man-silk-accessories/ties-man-oe', 'Men - soft accessories - ties', '패션잡화>패션소품>넥타이>기본넥타이', '50004014', NULL, NULL, 'bcm499', 'smartstore_2'),
('Ferragamo', 'https://www.ferragamo.com/shop/eu/en/men/man-silk-accessories/scarves-oe', 'Men - soft accessories - scarves', '패션잡화>패션소품>스카프>롱', '50004010', NULL, NULL, 'bcm499', 'smartstore_2'),
('Ferragamo', 'https://www.ferragamo.com/shop/eu/en/men/jewellery-watches-oe/cufflinks-oe', 'Men - jewelry and watches - cufflinks', '패션잡화>패션소품>커프스', '50000564', NULL, NULL, 'bcm499', 'smartstore_2'),
('Ferragamo', 'https://www.ferragamo.com/shop/eu/en/men/man-eyewear/sunglasses-men-eu-en', 'Men - eyewear - sunglasses', '패션잡화>선글라스/안경테>선글라스', '50000554', NULL, NULL, 'bcm499', 'smartstore_2'),
('Ferragamo', 'https://www.ferragamo.com/shop/eu/en/men/man-eyewear/optical-men-eu-en', 'Men - eyewear - opticalglasses', '패션잡화>선글라스/안경테>안경테', '50000556', NULL, NULL, 'bcm499', 'smartstore_2');
