INSERT INTO mapping (
  site,
  "siteUrl",
  "categoryName",
  "godoMallCategoryName",
  "godoMallCategoryCode",
  designers,
  "afterDesigners",
  "customId",
  "accountPlatform"
) VALUES
('Givenchy', 'https://www.givenchy.com/nl/en/women/ready-to-wear/tailoring/', 'WOMEN - Ready-to-Wear - Tailoring', '패션의류>여성의류>정장세트', '50000816', NULL, NULL, 'bcm499', 'smartstore_2'),
('Givenchy', 'https://www.givenchy.com/nl/en/women/ready-to-wear/dresses/', 'WOMEN - Ready-to-Wear - Dresses', '패션의류>여성의류>원피스', '50000807', NULL, NULL, 'bcm499', 'smartstore_2'),
('Givenchy', 'https://www.givenchy.com/nl/en/women/ready-to-wear/jackets-coats/', 'WOMEN - Ready-to-Wear - Jackets & Coats', '패션의류>여성의류>아우터>재킷', '50021360', NULL, NULL, 'bcm499', 'smartstore_2'),
('Givenchy', 'https://www.givenchy.com/nl/en/women/ready-to-wear/pants/', 'WOMEN - Ready-to-Wear - Pants & Shorts', '패션의류>여성의류>바지', '50000810', NULL, NULL, 'bcm499', 'smartstore_2'),
('Givenchy', 'https://www.givenchy.com/nl/en/women/ready-to-wear/skirts/', 'WOMEN - Ready-to-Wear - Skirts', '패션의류>여성의류>스커트', '50000808', NULL, NULL, 'bcm499', 'smartstore_2'),
('Givenchy', 'https://www.givenchy.com/nl/en/women/ready-to-wear/tops-shirts/', 'WOMEN - Ready-to-Wear - Tops', '패션의류>여성의류>블라우스/셔츠', '50000804', NULL, NULL, 'bcm499', 'smartstore_2'),
('Givenchy', 'https://www.givenchy.com/nl/en/women/ready-to-wear/t-shirts/', 'WOMEN - Ready-to-Wear - T-Shirts', '패션의류>여성의류>티셔츠', '50000803', NULL, NULL, 'bcm499', 'smartstore_2'),
('Givenchy', 'https://www.givenchy.com/nl/en/women/ready-to-wear/sweaters/', 'WOMEN - Ready-to-Wear - Sweaters', '패션의류>여성의류>니트>풀오버', '50021299', NULL, NULL, 'bcm499', 'smartstore_2'),
('Givenchy', 'https://www.givenchy.com/nl/en/women/ready-to-wear/knitwear/', 'WOMEN - Ready-to-Wear - Knitwear', '패션의류>여성의류>니트>풀오버', '50021299', NULL, NULL, 'bcm499', 'smartstore_2'),
('Givenchy', 'https://www.givenchy.com/nl/en/women/bags/cross-body-bags/', 'WOMEN - Bags - Cross-body Bags', '패션잡화>여성가방>크로스백', '50000641', NULL, NULL, 'bcm499', 'smartstore_2'),
('Givenchy', 'https://www.givenchy.com/nl/en/women/bags/shoulder-bags/', 'WOMEN - Bags - Shoulder Bags', '패션잡화>여성가방>숄더백', '50000639', NULL, NULL, 'bcm499', 'smartstore_2'),
('Givenchy', 'https://www.givenchy.com/nl/en/women/bags/top-handle-bags/', 'WOMEN - Bags - Top Handle Bags', '패션잡화>여성가방>토트백', '50000640', NULL, NULL, 'bcm499', 'smartstore_2'),
('Givenchy', 'https://www.givenchy.com/nl/en/women/bags/clutches/', 'WOMEN - Bags - Clutches', '패션잡화>여성가방>클러치백', '50000642', NULL, NULL, 'bcm499', 'smartstore_2'),
('Givenchy', 'https://www.givenchy.com/nl/en/women/bags/wallets/', 'WOMEN - Bags - Wallets', '패션잡화>지갑>여성지갑>반지갑', '50003982', NULL, NULL, 'bcm499', 'smartstore_2'),
('Givenchy', 'https://www.givenchy.com/nl/en/women/shoes/pumps/', 'WOMEN - Shoes - Pumps', '패션잡화>여성신발>힐/펌프스>펌프스', '50003830', NULL, NULL, 'bcm499', 'smartstore_2'),
('Givenchy', 'https://www.givenchy.com/nl/en/women/shoes/sandals-mules/', 'WOMEN - Shoes - Sandals & Mules', '패션잡화>여성신발>샌들>스트랩샌들', '50003842', NULL, NULL, 'bcm499', 'smartstore_2'),
('Givenchy', 'https://www.givenchy.com/nl/en/women/shoes/loafers-ballerinas/', 'WOMEN - Shoes - Loafers & Ballerinas', '패션잡화>여성신발>단화>로퍼', '50003818', NULL, NULL, 'bcm499', 'smartstore_2'),
('Givenchy', 'https://www.givenchy.com/nl/en/women/shoes/boots-ankle-boots/', 'WOMEN - Shoes - Boots & Ankle Boots', '패션잡화>여성신발>부츠>앵클/숏부츠', '50004191', NULL, NULL, 'bcm499', 'smartstore_2'),
('Givenchy', 'https://www.givenchy.com/nl/en/women/shoes/sneakers/', 'WOMEN - Shoes - Sneakers', '패션잡화>여성신발>단화>스니커즈', '50003822', NULL, NULL, 'bcm499', 'smartstore_2'),
('Givenchy', 'https://www.givenchy.com/nl/en/women/shoes/shark-boots/', 'WOMEN - Shoes - Shark Boots', '패션잡화>여성신발>부츠>앵클/숏부츠', '50004191', NULL, NULL, 'bcm499', 'smartstore_2'),
('Givenchy', 'https://www.givenchy.com/nl/en/women/jewelry/bracelets/', 'WOMEN - Jewelry - Bracelets', '패션잡화>주얼리>팔찌>패션팔찌', '50004194', NULL, NULL, 'bcm499', 'smartstore_2'),
('Givenchy', 'https://www.givenchy.com/nl/en/women/jewelry/earrings/', 'WOMEN - Jewelry - Earrings', '패션잡화>주얼리>귀걸이>패션귀걸이', '50004164', NULL, NULL, 'bcm499', 'smartstore_2'),
('Givenchy', 'https://www.givenchy.com/nl/en/women/jewelry/necklaces/', 'WOMEN - Jewelry - Necklaces', '패션잡화>주얼리>목걸이>패션목걸이', '50004174', NULL, NULL, 'bcm499', 'smartstore_2'),
('Givenchy', 'https://www.givenchy.com/nl/en/women/jewelry/rings/', 'WOMEN - Jewelry - Rings', '패션잡화>주얼리>반지>패션반지', '50004155', NULL, NULL, 'bcm499', 'smartstore_2'),
('Givenchy', 'https://www.givenchy.com/nl/en/women/accessories/sunglasses/', 'WOMEN - Accessories - Sunglasses', '패션잡화>선글라스/안경테>선글라스', '50000554', NULL, NULL, 'bcm499', 'smartstore_2'),
('Givenchy', 'https://www.givenchy.com/nl/en/women/accessories/belts/', 'WOMEN - Accessories - Belts', '패션잡화>벨트>여성벨트', '50000539', NULL, NULL, 'bcm499', 'smartstore_2'),
('Givenchy', 'https://www.givenchy.com/nl/en/women/accessories/scarves/', 'WOMEN - Accessories - Scarves', '패션잡화>패션소품>스카프>롱', '50004010', NULL, NULL, 'bcm499', 'smartstore_2'),
('Givenchy', 'https://www.givenchy.com/nl/en/men/ready-to-wear/jackets-coats/', 'MEN - Ready-to-Wear - Jackets & Coats', '패션의류>남성의류>아우터>재킷', '50021640', NULL, NULL, 'bcm499', 'smartstore_2'),
('Givenchy', 'https://www.givenchy.com/nl/en/men/ready-to-wear/bombers-blousons/', 'MEN - Ready-to-Wear - Bombers & Blousons', '패션의류>남성의류>점퍼', '50000837', NULL, NULL, 'bcm499', 'smartstore_2'),
('Givenchy', 'https://www.givenchy.com/nl/en/men/ready-to-wear/t-shirts-polos/', 'MEN - Ready-to-Wear - T-Shirts & Polos', '패션의류>남성의류>티셔츠', '50000830', NULL, NULL, 'bcm499', 'smartstore_2'),
('Givenchy', 'https://www.givenchy.com/nl/en/men/ready-to-wear/shirts/', 'MEN - Ready-to-Wear - Shirts', '패션의류>남성의류>셔츠/남방', '50000833', NULL, NULL, 'bcm499', 'smartstore_2'),
('Givenchy', 'https://www.givenchy.com/nl/en/men/ready-to-wear/pants-shorts/', 'MEN - Ready-to-Wear - Pants & Shorts', '패션의류>남성의류>바지', '50000836', NULL, NULL, 'bcm499', 'smartstore_2'),
('Givenchy', 'https://www.givenchy.com/nl/en/men/ready-to-wear/knitwear/', 'MEN - Ready-to-Wear - Sweaters', '패션의류>남성의류>니트>풀오버', '50021579', NULL, NULL, 'bcm499', 'smartstore_2'),
('Givenchy', 'https://www.givenchy.com/nl/en/men/ready-to-wear/tailoring/', 'MEN - Ready-to-Wear - Tailoring', '패션의류>남성의류>정장세트', '50000840', NULL, NULL, 'bcm499', 'smartstore_2'),
('Givenchy', 'https://www.givenchy.com/nl/en/men/bags/cross-body-bags/', 'MEN - Bags - Cross-body Bags', '패션잡화>남성가방>크로스백', '50000648', NULL, NULL, 'bcm499', 'smartstore_2'),
('Givenchy', 'https://www.givenchy.com/nl/en/men/bags/backpacks/', 'MEN - Bags - Backpacks', '패션잡화>남성가방>백팩', '50000651', NULL, NULL, 'bcm499', 'smartstore_2'),
('Givenchy', 'https://www.givenchy.com/nl/en/men/bags/weekend-bags/', 'MEN - Bags - Weekend Bags', '패션잡화>남성가방>토트백', '50000647', NULL, NULL, 'bcm499', 'smartstore_2'),
('Givenchy', 'https://www.givenchy.com/nl/en/men/bags/wallets/', 'MEN - Bags - Wallets', '패션잡화>지갑>남성지갑>반지갑', '50003985', NULL, NULL, 'bcm499', 'smartstore_2'),
('Givenchy', 'https://www.givenchy.com/nl/en/men/shoes/sneakers/', 'MEN - Shoes - Sneakers', '패션잡화>남성신발>스니커즈', '50000788', NULL, NULL, 'bcm499', 'smartstore_2'),
('Givenchy', 'https://www.givenchy.com/nl/en/men/shoes/loafers/', 'MEN - Shoes - Loafers', '패션잡화>남성신발>구두', '50000787', NULL, NULL, 'bcm499', 'smartstore_2'),
('Givenchy', 'https://www.givenchy.com/nl/en/men/shoes/sandals/', 'MEN - Shoes - Sandals', '패션잡화>남성신발>샌들', '50000789', NULL, NULL, 'bcm499', 'smartstore_2'),
('Givenchy', 'https://www.givenchy.com/nl/en/men/shoes/boots-derbies/', 'MEN - Shoes - Boots & Derbies', '패션잡화>남성신발>부츠>앵클/숏부츠', '50021999', NULL, NULL, 'bcm499', 'smartstore_2'),
('Givenchy', 'https://www.givenchy.com/nl/en/men/accessories/sunglasses/', 'MEN - Accessories - Sunglasses', '패션잡화>선글라스/안경테>선글라스', '50000554', NULL, NULL, 'bcm499', 'smartstore_2'),
('Givenchy', 'https://www.givenchy.com/nl/en/men/accessories/belts/', 'MEN - Accessories - Belts', '패션잡화>벨트>남성벨트>캐주얼벨트', '50003989', NULL, NULL, 'bcm499', 'smartstore_2'),
('Givenchy', 'https://www.givenchy.com/nl/en/men/accessories/caps/', 'MEN - Accessories - Caps', '패션잡화>모자>사파리모자', '50000546', NULL, NULL, 'bcm499', 'smartstore_2');
