INSERT INTO mapping (
  site,
  "siteUrl",
  "categoryName",
  "godoMallCategoryName",
  "godoMallCategoryCode",
  designers,
  "afterDesigners",
  "customId",
  "accountPlatform"
) VALUES
('Hermes', 'https://www.hermes.com/fr/fr/category/femme/pret-a-porter/manteaux-et-vestes/', 'Women''s - Ready-to-wear - Coats and jackets', '패션의류>여성의류>아우터>재킷', '50021360', NULL, NULL, 'bcm499', 'smartstore_2'),
('Hermes', 'https://www.hermes.com/fr/fr/category/femme/pret-a-porter/hauts-et-chemises/', 'Women''s - Ready-to-wear - Tops and shirts', '패션의류>여성의류>블라우스/셔츠', '50000804', NULL, NULL, 'bcm499', 'smartstore_2'),
('Hermes', 'https://www.hermes.com/fr/fr/category/femme/pret-a-porter/pantalons-jupes-et-shorts/', 'Women''s - Ready-to-wear - Trousers and shorts', '패션의류>여성의류>바지', '50000810', NULL, NULL, 'bcm499', 'smartstore_2'),
('Hermes', 'https://www.hermes.com/fr/fr/category/femme/pret-a-porter/mailles-et-twillaines/', 'Women''s - Ready-to-wear - Knitwear and twill', '패션의류>여성의류>니트>풀오버', '50021299', NULL, NULL, 'bcm499', 'smartstore_2'),
('Hermes', 'https://www.hermes.com/fr/fr/category/femme/chaussures/sandales/', 'Women''s Shoes - Sandals', '패션잡화>여성신발>샌들>스트랩샌들', '50003842', NULL, NULL, 'bcm499', 'smartstore_2'),
('Hermes', 'https://www.hermes.com/fr/fr/category/femme/chaussures/sneakers/', 'Women''s Shoes - Sneakers', '패션잡화>여성신발>단화>스니커즈', '50003822', NULL, NULL, 'bcm499', 'smartstore_2'),
('Hermes', 'https://www.hermes.com/fr/fr/category/femme/chaussures/mules/', 'Women''s Shoes - Mules', '패션잡화>여성신발>샌들>뮬/블로퍼', '50003847', NULL, NULL, 'bcm499', 'smartstore_2'),
('Hermes', 'https://www.hermes.com/fr/fr/category/femme/chaussures/espadrilles/', 'Women''s Shoes - Espadrilles', '패션잡화>여성신발>단화>슬립온', '50003821', NULL, NULL, 'bcm499', 'smartstore_2'),
('Hermes', 'https://www.hermes.com/fr/fr/category/femme/chaussures/mocassins-et-derbies/', 'Women''s Shoes - Loafers and Derbies', '패션잡화>여성신발>단화>로퍼', '50003818', NULL, NULL, 'bcm499', 'smartstore_2'),
('Hermes', 'https://www.hermes.com/fr/fr/category/femme/chaussures/bottes-et-bottines/', 'Women''s Shoes - Boots and Ankle Boots', '패션잡화>여성신발>부츠>앵클/숏부츠', '50004191', NULL, NULL, 'bcm499', 'smartstore_2'),
('Hermes', 'https://www.hermes.com/fr/fr/category/femme/carres-chales-et-echarpes/carres-et-accessoires-de-soie/', 'Women''s - Squares, shawls and scarves - Silk squares and accessories', '패션잡화>패션소품>스카프>롱', '50004010', NULL, NULL, 'bcm499', 'smartstore_2'),
('Hermes', 'https://www.hermes.com/fr/fr/category/femme/carres-chales-et-echarpes/chales-et-echarpes-en-cachemire/', 'Women''s - Squares, shawls and scarves - Cashmere shawls and scarves', '패션잡화>패션소품>숄', '50000567', NULL, NULL, 'bcm499', 'smartstore_2'),
('Hermes', 'https://www.hermes.com/fr/fr/category/femme/carres-chales-et-echarpes/twillys-et-autres-petits-formats/', 'Women''s - Squares, shawls and scarves - Twilly and other small sizes', '패션잡화>패션소품>스카프>쁘띠/미니', '50004011', NULL, NULL, 'bcm499', 'smartstore_2'),
('Hermes', 'https://www.hermes.com/fr/fr/category/femme/accessoires-bijoux/bracelets/', 'Women''s - Costume Jewelry - Bracelets', '패션잡화>주얼리>팔찌>패션팔찌', '50004194', NULL, NULL, 'bcm499', 'smartstore_2'),
('Hermes', 'https://www.hermes.com/fr/fr/category/femme/accessoires-bijoux/colliers-et-pendentifs/', 'Women''s - Costume Jewelry - Necklaces and Pendants', '패션잡화>주얼리>목걸이>패션목걸이', '50004174', NULL, NULL, 'bcm499', 'smartstore_2'),
('Hermes', 'https://www.hermes.com/fr/fr/category/femme/accessoires-bijoux/boucles-d-oreilles/', 'Women''s - Costume Jewelry - Earrings', '패션잡화>주얼리>귀걸이>패션귀걸이', '50004164', NULL, NULL, 'bcm499', 'smartstore_2'),
('Hermes', 'https://www.hermes.com/fr/fr/category/femme/accessoires-bijoux/bagues/', 'Women''s - Costume Jewelry - Rings', '패션잡화>주얼리>반지>패션반지', '50004155', NULL, NULL, 'bcm499', 'smartstore_2'),
('Hermes', 'https://www.hermes.com/fr/fr/category/homme/pret-a-porter/manteaux-et-vestes/', 'Men''s - Ready-to-wear - Coats and jackets', '패션의류>남성의류>아우터>재킷', '50021640', NULL, NULL, 'bcm499', 'smartstore_2'),
('Hermes', 'https://www.hermes.com/fr/fr/category/homme/pret-a-porter/chemises/', 'Men''s - Ready-to-wear - Shirts', '패션의류>남성의류>셔츠/남방', '50000833', NULL, NULL, 'bcm499', 'smartstore_2'),
('Hermes', 'https://www.hermes.com/fr/fr/category/homme/pret-a-porter/pantalons-et-shorts/', 'Men''s - Ready-to-wear - Trousers and shorts', '패션의류>남성의류>바지', '50000836', NULL, NULL, 'bcm499', 'smartstore_2'),
('Hermes', 'https://www.hermes.com/fr/fr/category/homme/pret-a-porter/t-shirts-et-polos/', 'Men''s - Ready-to-wear - T-shirts and polo shirts', '패션의류>남성의류>티셔츠', '50000830', NULL, NULL, 'bcm499', 'smartstore_2'),
('Hermes', 'https://www.hermes.com/fr/fr/category/homme/chaussures/sneakers/', 'Men''s Shoes - Sneakers', '패션잡화>남성신발>스니커즈', '50000788', NULL, NULL, 'bcm499', 'smartstore_2'),
('Hermes', 'https://www.hermes.com/fr/fr/category/homme/chaussures/sandales/', 'Men''s Shoes - Sandals', '패션잡화>남성신발>샌들', '50000789', NULL, NULL, 'bcm499', 'smartstore_2'),
('Hermes', 'https://www.hermes.com/fr/fr/category/homme/chaussures/espadrilles-et-mules/', 'Men''s Shoes - Espadrilles and Mules', '패션잡화>남성신발>슬립온', '50000783', NULL, NULL, 'bcm499', 'smartstore_2'),
('Hermes', 'https://www.hermes.com/fr/fr/category/homme/chaussures/mocassins-et-derbies/', 'Men''s Shoes - Loafers and Derbies', '패션잡화>남성신발>구두', '50000787', NULL, NULL, 'bcm499', 'smartstore_2'),
('Hermes', 'https://www.hermes.com/fr/fr/category/homme/chaussures/bottines/', 'Men''s Shoes - Ankle Boots', '패션잡화>남성신발>부츠>앵클/숏부츠', '50021999', NULL, NULL, 'bcm499', 'smartstore_2'),
('Hermes', 'https://www.hermes.com/fr/fr/category/homme/cravates-echarpes-et-carres/echarpes-et-carres/', 'Men''s - Ties, scarves and squares - Scarves and squares', '패션잡화>패션소품>스카프>롱', '50004010', NULL, NULL, 'bcm499', 'smartstore_2'),
('Hermes', 'https://www.hermes.com/fr/fr/category/maroquinerie/petite-maroquinerie/portefeuilles/', 'Leather goods - Small leather goods - Wallets', '패션잡화>지갑>여성지갑>반지갑', '50003982', NULL, NULL, 'bcm499', 'smartstore_2'),
('Hermes', 'https://www.hermes.com/fr/fr/category/maroquinerie/petite-maroquinerie/porte-cartes/', 'Leather goods - Small leather goods - Card holders', '패션잡화>지갑>카드/명함지갑', '50000662', NULL, NULL, 'bcm499', 'smartstore_2'),
('Hermes', 'https://www.hermes.com/fr/fr/category/maroquinerie/petite-maroquinerie/trousses-et-etuis/', 'Leather goods - Small leather goods - Pouches and cases', '패션잡화>여성가방>파우치', '50000643', NULL, NULL, 'bcm499', 'smartstore_2'),
('Hermes', 'https://www.hermes.com/fr/fr/category/bijouterie/bijoux-en-or/bagues/', 'Jewelry - Gold Jewelry - Rings', '패션잡화>주얼리>반지>패션반지', '50004155', NULL, NULL, 'bcm499', 'smartstore_2'),
('Hermes', 'https://www.hermes.com/fr/fr/category/bijouterie/bijoux-en-or/bracelets/', 'Jewelry - Gold Jewelry - Bracelets', '패션잡화>주얼리>팔찌>패션팔찌', '50004194', NULL, NULL, 'bcm499', 'smartstore_2'),
('Hermes', 'https://www.hermes.com/fr/fr/category/bijouterie/bijoux-en-or/colliers-et-pendentifs/', 'Jewelry - Gold Jewelry - Necklaces and Pendants', '패션잡화>주얼리>목걸이>패션목걸이', '50004174', NULL, NULL, 'bcm499', 'smartstore_2'),
('Hermes', 'https://www.hermes.com/fr/fr/category/bijouterie/bijoux-en-or/bijoux-doreilles/', 'Jewelry - Gold Jewelry - Earrings', '패션잡화>주얼리>귀걸이>패션귀걸이', '50004164', NULL, NULL, 'bcm499', 'smartstore_2'),
('Hermes', 'https://www.hermes.com/fr/fr/category/bijouterie/bijoux-en-argent/bagues/', 'Jewelry - Silver Jewelry - Rings', '패션잡화>주얼리>반지>패션반지', '50004155', NULL, NULL, 'bcm499', 'smartstore_2'),
('Hermes', 'https://www.hermes.com/fr/fr/category/bijouterie/bijoux-en-argent/bracelets/', 'Jewelry - Silver Jewelry - Bracelets', '패션잡화>주얼리>팔찌>패션팔찌', '50004194', NULL, NULL, 'bcm499', 'smartstore_2'),
('Hermes', 'https://www.hermes.com/fr/fr/category/bijouterie/bijoux-en-argent/colliers-et-pendentifs/', 'Jewelry - Silver Jewelry - Necklaces and Pendants', '패션잡화>주얼리>목걸이>패션목걸이', '50004174', NULL, NULL, 'bcm499', 'smartstore_2'),
('Hermes', 'https://www.hermes.com/fr/fr/category/bijouterie/bijoux-en-argent/bijoux-doreilles/', 'Jewelry - Silver Jewelry - Earrings', '패션잡화>주얼리>귀걸이>패션귀걸이', '50004164', NULL, NULL, 'bcm499', 'smartstore_2');
