INSERT INTO mapping (
  site,
  "siteUrl",
  "categoryName",
  "godoMallCategoryName",
  "godoMallCategoryCode",
  designers,
  "afterDesigners",
  "customId",
  "accountPlatform"
) VALUES
('Isabelmarant', 'https://isabelmarant.com/en-nl/collections/jackets-woman', 'WOMEN - ready-to-wear - JACKETS', '패션의류>여성의류>아우터>재킷', '50021360', NULL, NULL, 'bcm499', 'smartstore_2'),
('Isabelmarant', 'https://isabelmarant.com/en-nl/collections/coats-woman', 'WOMEN - ready-to-wear - COATS', '패션의류>여성의류>아우터>기타코트', '50021479', NULL, NULL, 'bcm499', 'smartstore_2'),
('Isabelmarant', 'https://isabelmarant.com/en-nl/collections/knitwear-woman', 'WOMEN - ready-to-wear - KNITWEAR', '패션의류>여성의류>니트>풀오버', '50021299', NULL, NULL, 'bcm499', 'smartstore_2'),
('Isabelmarant', 'https://isabelmarant.com/en-nl/collections/dresses-woman', 'WOMEN - ready-to-wear - DRESSES', '패션의류>여성의류>원피스', '50000807', NULL, NULL, 'bcm499', 'smartstore_2'),
('Isabelmarant', 'https://isabelmarant.com/en-nl/collections/tops-and-shirts-woman', 'WOMEN - ready-to-wear - TOPS & SHIRTS', '패션의류>여성의류>블라우스/셔츠', '50000804', NULL, NULL, 'bcm499', 'smartstore_2'),
('Isabelmarant', 'https://isabelmarant.com/en-nl/collections/pants-and-shorts-woman', 'WOMEN - ready-to-wear - PANTS & SHORTS', '패션의류>여성의류>바지', '50000810', NULL, NULL, 'bcm499', 'smartstore_2'),
('Isabelmarant', 'https://isabelmarant.com/en-nl/collections/skirts-woman', 'WOMEN - ready-to-wear - SKIRTS', '패션의류>여성의류>스커트', '50000808', NULL, NULL, 'bcm499', 'smartstore_2'),
('Isabelmarant', 'https://isabelmarant.com/en-nl/collections/tee-shirts-woman', 'WOMEN - ready-to-wear - TEE-SHIRTS', '패션의류>여성의류>티셔츠', '50000803', NULL, NULL, 'bcm499', 'smartstore_2'),
('Isabelmarant', 'https://isabelmarant.com/en-nl/collections/wedge-sneakers', 'WOMEN - shoes - Wedge sneakers', '패션잡화>여성신발>단화>스니커즈', '50003822', NULL, NULL, 'bcm499', 'smartstore_2'),
('Isabelmarant', 'https://isabelmarant.com/en-nl/collections/shoes-sneakers', 'WOMEN - shoes - Sneakers', '패션잡화>여성신발>단화>스니커즈', '50003822', NULL, NULL, 'bcm499', 'smartstore_2'),
('Isabelmarant', 'https://isabelmarant.com/en-nl/collections/shoes-boots', 'WOMEN - shoes - Boots & Ankle Boots', '패션잡화>여성신발>부츠>앵클/숏부츠', '50004191', NULL, NULL, 'bcm499', 'smartstore_2'),
('Isabelmarant', 'https://isabelmarant.com/en-nl/collections/shoes-heels', 'WOMEN - shoes - Heels', '패션잡화>여성신발>힐/펌프스>펌프스', '50003830', NULL, NULL, 'bcm499', 'smartstore_2'),
('Isabelmarant', 'https://isabelmarant.com/en-nl/collections/shoes-woman-sandals', 'WOMEN - shoes - Sandals & Mules', '패션잡화>여성신발>샌들>스트랩샌들', '50003842', NULL, NULL, 'bcm499', 'smartstore_2'),
('Isabelmarant', 'https://isabelmarant.com/en-nl/collections/bags-shoulder', 'WOMEN - bags - Shoulder Bags', '패션잡화>여성가방>숄더백', '50000639', NULL, NULL, 'bcm499', 'smartstore_2'),
('Isabelmarant', 'https://isabelmarant.com/en-nl/collections/bags-crossbody', 'WOMEN - bags - Crossbody Bags', '패션잡화>여성가방>크로스백', '50000641', NULL, NULL, 'bcm499', 'smartstore_2'),
('Isabelmarant', 'https://isabelmarant.com/en-nl/collections/bags-tote', 'WOMEN - bags - Tote Bags', '패션잡화>여성가방>토트백', '50000640', NULL, NULL, 'bcm499', 'smartstore_2'),
('Isabelmarant', 'https://isabelmarant.com/en-nl/collections/bags-fannypacks', 'WOMEN - bags - Belt Bags', '패션잡화>여성가방>힙색/슬링백', '50000645', NULL, NULL, 'bcm499', 'smartstore_2'),
('Isabelmarant', 'https://isabelmarant.com/en-nl/collections/earring', 'WOMEN - jewelry - Earrings', '패션잡화>주얼리>귀걸이>패션귀걸이', '50004164', NULL, NULL, 'bcm499', 'smartstore_2'),
('Isabelmarant', 'https://isabelmarant.com/en-nl/collections/accessories-belts', 'WOMEN - accessories - Belts', '패션잡화>벨트>여성벨트', '50000539', NULL, NULL, 'bcm499', 'smartstore_2'),
('Isabelmarant', 'https://isabelmarant.com/en-nl/collections/accessories-sunglasses', 'WOMEN - accessories - Sunglasses', '패션잡화>선글라스/안경테>선글라스', '50000554', NULL, NULL, 'bcm499', 'smartstore_2'),
('Isabelmarant', 'https://isabelmarant.com/en-nl/collections/accessories-hats', 'WOMEN - accessories - Beanies & Caps', '패션잡화>모자>사파리모자', '50000546', NULL, NULL, 'bcm499', 'smartstore_2'),
('Isabelmarant', 'https://isabelmarant.com/en-nl/collections/accessories-scarves', 'WOMEN - accessories - Scarves & Stoles', '패션잡화>패션소품>스카프>롱', '50004010', NULL, NULL, 'bcm499', 'smartstore_2'),
('Isabelmarant', 'https://isabelmarant.com/en-nl/collections/marant-man-coats-jackets', 'WOMEN - man - Coats & Jackets', '패션의류>남성의류>아우터>재킷', '50021640', NULL, NULL, 'bcm499', 'smartstore_2'),
('Isabelmarant', 'https://isabelmarant.com/en-nl/collections/marant-man-pants-shorts', 'WOMEN - man - Pants & Shorts', '패션의류>남성의류>바지', '50000836', NULL, NULL, 'bcm499', 'smartstore_2'),
('Isabelmarant', 'https://isabelmarant.com/en-nl/collections/marant-man-knitwear', 'WOMEN - man - Knitwear', '패션의류>남성의류>니트>풀오버', '50021579', NULL, NULL, 'bcm499', 'smartstore_2'),
('Isabelmarant', 'https://isabelmarant.com/en-nl/collections/marant-man-tee-shirts', 'WOMEN - man - Tee-shirts & Polos', '패션의류>남성의류>티셔츠', '50000830', NULL, NULL, 'bcm499', 'smartstore_2'),
('Isabelmarant', 'https://isabelmarant.com/en-nl/collections/marant-man-shirts', 'WOMEN - man - Shirts', '패션의류>남성의류>셔츠/남방', '50000833', NULL, NULL, 'bcm499', 'smartstore_2');
