INSERT INTO mapping (
  site,
  "siteUrl",
  "categoryName",
  "godoMallCategoryName",
  "godoMallCategoryCode",
  designers,
  "afterDesigners",
  "customId",
  "accountPlatform"
) VALUES
('Jacquemus', 'https://www.jacquemus.com/en_nl/handbags-crossbody-bags-women', 'Women-Bags-Crossbody & Handbags', '패션잡화>여성가방>크로스백', '50000641', NULL, NULL, 'bcm499', 'smartstore_2'),
('Jacquemus', 'https://www.jacquemus.com/en_nl/shoulder-bags-women', 'Women-Bags-Shoulder bags', '패션잡화>여성가방>숄더백', '50000639', NULL, NULL, 'bcm499', 'smartstore_2'),
('Jacquemus', 'https://www.jacquemus.com/en_nl/clutches-bags-women', 'Women-Bags-Clutches', '패션잡화>여성가방>클러치백', '50000642', NULL, NULL, 'bcm499', 'smartstore_2'),
('Jacquemus', 'https://www.jacquemus.com/en_nl/coats-and-jackets-women', 'Women-Ready-to-wear-Coats & Jackets', '패션의류>여성의류>아우터>재킷', '50021360', NULL, NULL, 'bcm499', 'smartstore_2'),
('Jacquemus', 'https://www.jacquemus.com/en_nl/knits-women', 'Women-Ready-to-wear-Knits', '패션의류>여성의류>니트>풀오버', '50021299', NULL, NULL, 'bcm499', 'smartstore_2'),
('Jacquemus', 'https://www.jacquemus.com/en_nl/t-shirts-women', 'Women-Ready-to-wear-T-shirts', '패션의류>여성의류>티셔츠', '50000803', NULL, NULL, 'bcm499', 'smartstore_2'),
('Jacquemus', 'https://www.jacquemus.com/en_nl/tops-shirts-women', 'Women-Ready-to-wear-Tops & Shirts', '패션의류>여성의류>블라우스/셔츠', '50000804', NULL, NULL, 'bcm499', 'smartstore_2'),
('Jacquemus', 'https://www.jacquemus.com/en_nl/trousers-and-shorts-women', 'Women-Ready-to-wear-Trousers & Shorts', '패션의류>여성의류>바지', '50000810', NULL, NULL, 'bcm499', 'smartstore_2'),
('Jacquemus', 'https://www.jacquemus.com/en_nl/suits-women', 'Women-Ready-to-wear-Suits', '패션의류>여성의류>정장세트', '50000816', NULL, NULL, 'bcm499', 'smartstore_2'),
('Jacquemus', 'https://www.jacquemus.com/en_nl/pumps-shoes-women', 'Women-Shoes-Pumps', '패션잡화>여성신발>힐/펌프스>펌프스', '50003830', NULL, NULL, 'bcm499', 'smartstore_2'),
('Jacquemus', 'https://www.jacquemus.com/en_nl/sneakers-shoes-women', 'Women-Shoes-Sneakers', '패션잡화>여성신발>단화>스니커즈', '50003822', NULL, NULL, 'bcm499', 'smartstore_2'),
('Jacquemus', 'https://www.jacquemus.com/en_nl/loafers-flats-shoes-women', 'Women-Shoes-Loafers & Flats', '패션잡화>여성신발>단화>로퍼', '50003818', NULL, NULL, 'bcm499', 'smartstore_2'),
('Jacquemus', 'https://www.jacquemus.com/en_nl/boots-shoes-women', 'Women-Shoes-Boots', '패션잡화>여성신발>부츠>앵클/숏부츠', '50004191', NULL, NULL, 'bcm499', 'smartstore_2'),
('Jacquemus', 'https://www.jacquemus.com/en_nl/hats-women', 'Women-Accessories-Hats', '패션잡화>모자>사파리모자', '50000546', NULL, NULL, 'bcm499', 'smartstore_2'),
('Jacquemus', 'https://www.jacquemus.com/en_nl/sunglasses-women', 'Women-Accessories-Sunglasses', '패션잡화>선글라스/안경테>선글라스', '50000554', NULL, NULL, 'bcm499', 'smartstore_2'),
('Jacquemus', 'https://www.jacquemus.com/en_nl/scarves-women', 'Women-Accessories-Scarves', '패션잡화>패션소품>스카프>롱', '50004010', NULL, NULL, 'bcm499', 'smartstore_2'),
('Jacquemus', 'https://www.jacquemus.com/en_nl/belts-women', 'Women-Accessories-Belts', '패션잡화>벨트>여성벨트', '50000539', NULL, NULL, 'bcm499', 'smartstore_2'),
('Jacquemus', 'https://www.jacquemus.com/en_nl/t-shirts-men', 'Men-Ready-to-wear-T-shirts', '패션의류>남성의류>티셔츠', '50000830', NULL, NULL, 'bcm499', 'smartstore_2'),
('Jacquemus', 'https://www.jacquemus.com/en_nl/shirts-men', 'Men-Ready-to-wear-Shirts', '패션의류>남성의류>셔츠/남방', '50000833', NULL, NULL, 'bcm499', 'smartstore_2'),
('Jacquemus', 'https://www.jacquemus.com/en_nl/coats-and-jackets-men', 'Men-Ready-to-wear-Coats & Jackets', '패션의류>남성의류>아우터>재킷', '50021640', NULL, NULL, 'bcm499', 'smartstore_2'),
('Jacquemus', 'https://www.jacquemus.com/en_nl/trousers-and-shorts-men', 'Men-Ready-to-wear-Trousers & Shorts', '패션의류>남성의류>바지', '50000836', NULL, NULL, 'bcm499', 'smartstore_2'),
('Jacquemus', 'https://www.jacquemus.com/en_nl/knits-men', 'Men-Ready-to-wear-Knits', '패션의류>남성의류>니트>풀오버', '50021579', NULL, NULL, 'bcm499', 'smartstore_2'),
('Jacquemus', 'https://www.jacquemus.com/en_nl/suits-men', 'Men-Ready-to-wear-Suits', '패션의류>남성의류>정장세트', '50000840', NULL, NULL, 'bcm499', 'smartstore_2'),
('Jacquemus', 'https://www.jacquemus.com/en_nl/sneakers-shoes-men', 'Men-Shoes-Sneakers', '패션잡화>남성신발>스니커즈', '50000788', NULL, NULL, 'bcm499', 'smartstore_2'),
('Jacquemus', 'https://www.jacquemus.com/en_nl/loafers-flats-shoes-men', 'Men-Shoes-Loafers & Flats', '패션잡화>남성신발>구두', '50000787', NULL, NULL, 'bcm499', 'smartstore_2'),
('Jacquemus', 'https://www.jacquemus.com/en_nl/hats-men', 'Men-Accessories & Bags-Hats', '패션잡화>모자>사파리모자', '50000546', NULL, NULL, 'bcm499', 'smartstore_2'),
('Jacquemus', 'https://www.jacquemus.com/en_nl/scarves-men', 'Men-Accessories & Bags-Scarves', '패션잡화>패션소품>스카프>롱', '50004010', NULL, NULL, 'bcm499', 'smartstore_2'),
('Jacquemus', 'https://www.jacquemus.com/en_nl/belts-men', 'Men-Accessories & Bags-Belts', '패션잡화>벨트>남성벨트>캐주얼벨트', '50003989', NULL, NULL, 'bcm499', 'smartstore_2');
