INSERT INTO mapping (
  site,
  "siteUrl",
  "categoryName",
  "godoMallCategoryName",
  "godoMallCategoryCode",
  designers,
  "afterDesigners",
  "customId",
  "accountPlatform"
) VALUES
('Ourlegacy', 'https://www.ourlegacy.com/mens/shirting', 'MEN - READY TO WEAR - SHIRTING', '패션의류>남성의류>셔츠/남방', '50000833', NULL, NULL, 'bcm499', 'smartstore_2'),
('Ourlegacy', 'https://www.ourlegacy.com/mens/jersey', 'MEN - READY TO WEAR - JERSEY', '패션의류>남성의류>티셔츠', '50000830', NULL, NULL, 'bcm499', 'smartstore_2'),
('Ourlegacy', 'https://www.ourlegacy.com/mens/outerwear', 'MEN - READY TO WEAR - OUTERWEAR', '패션의류>남성의류>아우터>재킷', '50021640', NULL, NULL, 'bcm499', 'smartstore_2'),
('Ourlegacy', 'https://www.ourlegacy.com/mens/knitwear', 'MEN - READY TO WEAR - KNITWEAR', '패션의류>남성의류>니트>풀오버', '50021579', NULL, NULL, 'bcm499', 'smartstore_2'),
('Ourlegacy', 'https://www.ourlegacy.com/mens/suiting', 'MEN - READY TO WEAR - SUITING', '패션의류>남성의류>정장세트', '50000840', NULL, NULL, 'bcm499', 'smartstore_2'),
('Ourlegacy', 'https://www.ourlegacy.com/mens/trousers', 'MEN - READY TO WEAR - TROUSERS', '패션의류>남성의류>바지', '50000836', NULL, NULL, 'bcm499', 'smartstore_2'),
('Ourlegacy', 'https://www.ourlegacy.com/mens/shorts', 'MEN - READY TO WEAR - SHORTS', '패션의류>남성의류>바지', '50000836', NULL, NULL, 'bcm499', 'smartstore_2'),
('Ourlegacy', 'https://www.ourlegacy.com/womens/shirting', 'WOMEN - READY TO WEAR - SHIRTING', '패션의류>여성의류>블라우스/셔츠', '50000804', NULL, NULL, 'bcm499', 'smartstore_2'),
('Ourlegacy', 'https://www.ourlegacy.com/womens/jersey', 'WOMEN - READY TO WEAR - JERSEY', '패션의류>여성의류>티셔츠', '50000803', NULL, NULL, 'bcm499', 'smartstore_2'),
('Ourlegacy', 'https://www.ourlegacy.com/womens/tops', 'WOMEN - READY TO WEAR - TOPS', '패션의류>여성의류>티셔츠', '50000803', NULL, NULL, 'bcm499', 'smartstore_2'),
('Ourlegacy', 'https://www.ourlegacy.com/womens/knitwear', 'WOMEN - READY TO WEAR - KNITWEAR', '패션의류>여성의류>니트>풀오버', '50021299', NULL, NULL, 'bcm499', 'smartstore_2'),
('Ourlegacy', 'https://www.ourlegacy.com/womens/skirts', 'WOMEN - READY TO WEAR - SKIRTS', '패션의류>여성의류>스커트', '50000808', NULL, NULL, 'bcm499', 'smartstore_2'),
('Ourlegacy', 'https://www.ourlegacy.com/womens/dresses', 'WOMEN - READY TO WEAR - DRESSES', '패션의류>여성의류>원피스', '50000807', NULL, NULL, 'bcm499', 'smartstore_2'),
('Ourlegacy', 'https://www.ourlegacy.com/womens/trousers', 'WOMEN - READY TO WEAR - TROUSERS', '패션의류>여성의류>바지', '50000810', NULL, NULL, 'bcm499', 'smartstore_2'),
('Ourlegacy', 'https://www.ourlegacy.com/womens/shorts', 'WOMEN - READY TO WEAR - SHORTS', '패션의류>여성의류>바지', '50000810', NULL, NULL, 'bcm499', 'smartstore_2'),
('Ourlegacy', 'https://www.ourlegacy.com/womens/suiting', 'WOMEN - READY TO WEAR - SUITING', '패션의류>여성의류>정장세트', '50000816', NULL, NULL, 'bcm499', 'smartstore_2'),
('Ourlegacy', 'https://www.ourlegacy.com/womens/outerwear', 'WOMEN - READY TO WEAR - OUTERWEAR', '패션의류>여성의류>아우터>재킷', '50021360', NULL, NULL, 'bcm499', 'smartstore_2'),
('Ourlegacy', 'https://www.ourlegacy.com/footwear/mens-footwear/mens-boots', 'FOOTWEAR - MENS SHOES - Boots', '패션잡화>남성신발>부츠>앵클/숏부츠', '50021999', NULL, NULL, 'bcm499', 'smartstore_2'),
('Ourlegacy', 'https://www.ourlegacy.com/footwear/mens-footwear/mens-mules', 'FOOTWEAR - MENS SHOES - Mules', '패션잡화>남성신발>슬리퍼', '50000790', NULL, NULL, 'bcm499', 'smartstore_2'),
('Ourlegacy', 'https://www.ourlegacy.com/footwear/mens-footwear/mens-sneakers', 'FOOTWEAR - MENS SHOES - Sneakers', '패션잡화>남성신발>스니커즈', '50000788', NULL, NULL, 'bcm499', 'smartstore_2'),
('Ourlegacy', 'https://www.ourlegacy.com/footwear/womens-footwear/womens-boots', 'FOOTWEAR - WOMENS SHOES - Boots', '패션잡화>여성신발>부츠>앵클/숏부츠', '50004191', NULL, NULL, 'bcm499', 'smartstore_2'),
('Ourlegacy', 'https://www.ourlegacy.com/footwear/womens-footwear/womens-mules', 'FOOTWEAR - WOMENS SHOES - Mules', '패션잡화>여성신발>샌들>뮬/블로퍼', '50003847', NULL, NULL, 'bcm499', 'smartstore_2'),
('Ourlegacy', 'https://www.ourlegacy.com/footwear/womens-footwear/womens-sneakers', 'FOOTWEAR - WOMENS SHOES - Sneakers', '패션잡화>여성신발>단화>스니커즈', '50003822', NULL, NULL, 'bcm499', 'smartstore_2'),
('Ourlegacy', 'https://www.ourlegacy.com/accessories/belts', 'ACCESSORIES - ACCESSORIES - Belts', '패션잡화>벨트>여성벨트', '50000539', NULL, NULL, 'bcm499', 'smartstore_2'),
('Ourlegacy', 'https://www.ourlegacy.com/accessories/eyewear', 'ACCESSORIES - ACCESSORIES - Eyewear', '패션잡화>선글라스/안경테>선글라스', '50000554', NULL, NULL, 'bcm499', 'smartstore_2'),
('Ourlegacy', 'https://www.ourlegacy.com/accessories/hats', 'ACCESSORIES - ACCESSORIES - Hats', '패션잡화>모자>사파리모자', '50000546', NULL, NULL, 'bcm499', 'smartstore_2'),
('Ourlegacy', 'https://www.ourlegacy.com/accessories/scarves', 'ACCESSORIES - ACCESSORIES - Scarves', '패션잡화>패션소품>스카프>롱', '50004010', NULL, NULL, 'bcm499', 'smartstore_2'),
('Ourlegacy', 'https://www.ourlegacy.com/accessories/ties', 'ACCESSORIES - ACCESSORIES - Ties', '패션잡화>패션소품>넥타이>기본넥타이', '50004014', NULL, NULL, 'bcm499', 'smartstore_2');
