INSERT INTO mapping (
  site,
  "siteUrl",
  "categoryName",
  "godoMallCategoryName",
  "godoMallCategoryCode",
  designers,
  "afterDesigners",
  "customId",
  "accountPlatform"
) VALUES
('Prada', 'https://www.prada.com/de/en/womens/bags/shoulder-bags/c/10066EU', 'women - bags - shoulder-bags', '패션잡화>여성가방>숄더백', '50000639', NULL, NULL, 'bcm499', 'smartstore_2'),
('Prada', 'https://www.prada.com/de/en/womens/bags/top-handles/c/10067EU', 'women - bags - top-handles', '패션잡화>여성가방>토트백', '50000640', NULL, NULL, 'bcm499', 'smartstore_2'),
('Prada', 'https://www.prada.com/de/en/womens/bags/totes/c/10068EU', 'women - bags - totes', '패션잡화>여성가방>토트백', '50000640', NULL, NULL, 'bcm499', 'smartstore_2'),
('Prada', 'https://www.prada.com/de/en/womens/bags/backpacks/c/10063EU', 'women - bags - backpacks', '패션잡화>여성가방>백팩', '50000644', NULL, NULL, 'bcm499', 'smartstore_2'),
('Prada', 'https://www.prada.com/de/en/womens/ready-to-wear/dresses/c/10050EU', 'women - ready-to-wear - dresses', '패션의류>여성의류>원피스', '50000807', NULL, NULL, 'bcm499', 'smartstore_2'),
('Prada', 'https://www.prada.com/de/en/womens/ready-to-wear/shirts-and-tops/c/10058EU', 'women - ready-to-wear - shirts-and-tops', '패션의류>여성의류>블라우스/셔츠', '50000804', NULL, NULL, 'bcm499', 'smartstore_2'),
('Prada', 'https://www.prada.com/de/en/womens/ready-to-wear/t-shirts-and-sweatshirts/c/10061EU', 'women - ready-to-wear - t-shirts-and-sweatshirts', '패션의류>여성의류>티셔츠', '50000803', NULL, NULL, 'bcm499', 'smartstore_2'),
('Prada', 'https://www.prada.com/de/en/womens/ready-to-wear/skirts/c/10059EU', 'women - ready-to-wear - skirts', '패션의류>여성의류>스커트', '50000808', NULL, NULL, 'bcm499', 'smartstore_2'),
('Prada', 'https://www.prada.com/de/en/womens/ready-to-wear/knitwear/c/10054EU', 'women - ready-to-wear - knitwear', '패션의류>여성의류>니트>풀오버', '50021299', NULL, NULL, 'bcm499', 'smartstore_2'),
('Prada', 'https://www.prada.com/de/en/womens/ready-to-wear/outerwear/c/10056EU', 'women - ready-to-wear - outerwear', '패션의류>여성의류>아우터>재킷', '50021360', NULL, NULL, 'bcm499', 'smartstore_2'),
('Prada', 'https://www.prada.com/de/en/womens/ready-to-wear/trousers-and-shorts/c/10060EU', 'women - ready-to-wear - trousers-and-shorts', '패션의류>여성의류>바지', '50000810', NULL, NULL, 'bcm499', 'smartstore_2'),
('Prada', 'https://www.prada.com/de/en/womens/ready-to-wear/jackets-and-coats/c/10052EU', 'women - ready-to-wear - jackets-and-coats', '패션의류>여성의류>아우터>재킷', '50021360', NULL, NULL, 'bcm499', 'smartstore_2'),
('Prada', 'https://www.prada.com/de/en/womens/shoes/sandals-and-mules/c/10720EU', 'women - shoes - sandals-and-mules', '패션잡화>여성신발>샌들>스트랩샌들', '50003842', NULL, NULL, 'bcm499', 'smartstore_2'),
('Prada', 'https://www.prada.com/de/en/womens/shoes/pumps-and-ballerinas/c/10075EU', 'women - shoes - pumps-and-ballerinas', '패션잡화>여성신발>힐/펌프스>펌프스', '50003830', NULL, NULL, 'bcm499', 'smartstore_2'),
('Prada', 'https://www.prada.com/de/en/womens/shoes/loafers-and-lace-ups/c/10074EU', 'women - shoes - loafers-and-lace-ups', '패션잡화>여성신발>단화>로퍼', '50003818', NULL, NULL, 'bcm499', 'smartstore_2'),
('Prada', 'https://www.prada.com/de/en/womens/shoes/ankle-boots-and-boots/c/10071EU', 'women - shoes - ankle-boots-and-boots', '패션잡화>여성신발>부츠>앵클/숏부츠', '50004191', NULL, NULL, 'bcm499', 'smartstore_2'),
('Prada', 'https://www.prada.com/de/en/womens/shoes/sneakers/c/10078EU', 'women - shoes - sneakers', '패션잡화>여성신발>단화>스니커즈', '50003822', NULL, NULL, 'bcm499', 'smartstore_2'),
('Prada', 'https://www.prada.com/de/en/womens/small-leather-goods/card-holders/c/10343EU', 'women - small-leather-goods - card-holders', '패션잡화>지갑>카드/명함지갑', '50000662', NULL, NULL, 'bcm499', 'smartstore_2'),
('Prada', 'https://www.prada.com/de/en/womens/small-leather-goods/small-wallets/c/10341EU', 'women - small-leather-goods - small-wallets', '패션잡화>지갑>여성지갑>반지갑', '50003982', NULL, NULL, 'bcm499', 'smartstore_2'),
('Prada', 'https://www.prada.com/de/en/womens/small-leather-goods/large-wallets/c/10342EU', 'women - small-leather-goods - large-wallets', '패션잡화>지갑>여성지갑>장지갑', '50003984', NULL, NULL, 'bcm499', 'smartstore_2'),
('Prada', 'https://www.prada.com/de/en/womens/accessories/sunglasses/c/10086EU', 'women - accessories - sunglasses', '패션잡화>선글라스/안경테>선글라스', '50000554', NULL, NULL, 'bcm499', 'smartstore_2'),
('Prada', 'https://www.prada.com/de/en/womens/accessories/pouches/c/10705EU', 'women - accessories - pouches', '패션잡화>여성가방>파우치', '50000643', NULL, NULL, 'bcm499', 'smartstore_2'),
('Prada', 'https://www.prada.com/de/en/womens/accessories/silks-and-scarves/c/10085EU', 'women - accessories - silks-and-scarves', '패션잡화>패션소품>스카프>롱', '50004010', NULL, NULL, 'bcm499', 'smartstore_2'),
('Prada', 'https://www.prada.com/de/en/womens/accessories/belts/c/10080EU', 'women - accessories - belts', '패션잡화>벨트>여성벨트', '50000539', NULL, NULL, 'bcm499', 'smartstore_2'),
('Prada', 'https://www.prada.com/de/en/womens/accessories/headbands-and-hair-accessories/c/10083EU', 'women - accessories - headbands-and-hair-accessories', '패션잡화>헤어액세서리>헤어밴드', '50000560', NULL, NULL, 'bcm499', 'smartstore_2'),
('Prada', 'https://www.prada.com/de/en/mens/ready-to-wear/shirts/c/10138EU', 'men - ready-to-wear - shirts', '패션의류>남성의류>셔츠/남방', '50000833', NULL, NULL, 'bcm499', 'smartstore_2'),
('Prada', 'https://www.prada.com/de/en/mens/ready-to-wear/outerwear/c/10136EU', 'men - ready-to-wear - outerwear', '패션의류>남성의류>아우터>재킷', '50021640', NULL, NULL, 'bcm499', 'smartstore_2'),
('Prada', 'https://www.prada.com/de/en/mens/ready-to-wear/jackets-and-coats/c/10132EU', 'men - ready-to-wear - jackets-and-coats', '패션의류>남성의류>아우터>재킷', '50021640', NULL, NULL, 'bcm499', 'smartstore_2'),
('Prada', 'https://www.prada.com/de/en/mens/ready-to-wear/knitwear/c/10134EU', 'men - ready-to-wear - knitwear', '패션의류>남성의류>니트>풀오버', '50021579', NULL, NULL, 'bcm499', 'smartstore_2'),
('Prada', 'https://www.prada.com/de/en/mens/ready-to-wear/trousers-and-bermudas/c/10141EU', 'men - ready-to-wear - trousers-and-bermudas', '패션의류>남성의류>바지', '50000836', NULL, NULL, 'bcm499', 'smartstore_2'),
('Prada', 'https://www.prada.com/de/en/mens/ready-to-wear/suits/c/10139EU', 'men - ready-to-wear - suits', '패션의류>남성의류>정장세트', '50000840', NULL, NULL, 'bcm499', 'smartstore_2'),
('Prada', 'https://www.prada.com/de/en/mens/ready-to-wear/t-shirts-and-polo-shirts/c/10142EU', 'men - ready-to-wear - t-shirts-and-polo-shirts', '패션의류>남성의류>티셔츠', '50000830', NULL, NULL, 'bcm499', 'smartstore_2'),
('Prada', 'https://www.prada.com/de/en/mens/shoes/loafers/c/10153EU', 'men - shoes - loafers', '패션잡화>남성신발>구두', '50000787', NULL, NULL, 'bcm499', 'smartstore_2'),
('Prada', 'https://www.prada.com/de/en/mens/shoes/sneakers/c/10155EU', 'men - shoes - sneakers', '패션잡화>남성신발>스니커즈', '50000788', NULL, NULL, 'bcm499', 'smartstore_2'),
('Prada', 'https://www.prada.com/de/en/mens/shoes/sandals/c/10154EU', 'men - shoes - sandals', '패션잡화>남성신발>샌들', '50000789', NULL, NULL, 'bcm499', 'smartstore_2'),
('Prada', 'https://www.prada.com/de/en/mens/shoes/lace-ups/c/10152EU', 'men - shoes - lace-ups', '패션잡화>남성신발>구두', '50000787', NULL, NULL, 'bcm499', 'smartstore_2'),
('Prada', 'https://www.prada.com/de/en/mens/shoes/boots/c/10150EU', 'men - shoes - boots', '패션잡화>남성신발>부츠>앵클/숏부츠', '50021999', NULL, NULL, 'bcm499', 'smartstore_2'),
('Prada', 'https://www.prada.com/de/en/mens/shoes/americas-cup/c/10297EU', 'men - shoes - america''s-cup', '패션잡화>남성신발>스니커즈', '50000788', NULL, NULL, 'bcm499', 'smartstore_2'),
('Prada', 'https://www.prada.com/de/en/mens/small-leather-goods/card-holders/c/10349EU', 'men - small-leather-goods - card-holders', '패션잡화>지갑>카드/명함지갑', '50000662', NULL, NULL, 'bcm499', 'smartstore_2'),
('Prada', 'https://www.prada.com/de/en/mens/small-leather-goods/small-wallets/c/10347EU', 'men - small-leather-goods - small-wallets', '패션잡화>지갑>남성지갑>반지갑', '50003985', NULL, NULL, 'bcm499', 'smartstore_2'),
('Prada', 'https://www.prada.com/de/en/mens/small-leather-goods/large-wallets/c/10348EU', 'men - small-leather-goods - large-wallets', '패션잡화>지갑>남성지갑>장지갑', '50003987', NULL, NULL, 'bcm499', 'smartstore_2'),
('Prada', 'https://www.prada.com/de/en/mens/travel/pouches/c/10177EU', 'men - travel - pouches', '패션잡화>남성가방>클러치백', '50000649', NULL, NULL, 'bcm499', 'smartstore_2'),
('Prada', 'https://www.prada.com/de/en/mens/accessories/sunglasses/c/10163EU', 'men - accessories - sunglasses', '패션잡화>선글라스/안경테>선글라스', '50000554', NULL, NULL, 'bcm499', 'smartstore_2'),
('Prada', 'https://www.prada.com/de/en/mens/accessories/belts/c/10157EU', 'men - accessories - belts', '패션잡화>벨트>남성벨트>캐주얼벨트', '50003989', NULL, NULL, 'bcm499', 'smartstore_2'),
('Prada', 'https://www.prada.com/de/en/mens/accessories/silks-and-scarves/c/10162EU', 'men - accessories - silks-and-scarves', '패션잡화>패션소품>스카프>롱', '50004010', NULL, NULL, 'bcm499', 'smartstore_2'),
('Prada', 'https://www.prada.com/de/en/mens/accessories/ties-and-bow-ties/c/10164EU', 'men - accessories - ties-and-bow-ties', '패션잡화>패션소품>넥타이>기본넥타이', '50004014', NULL, NULL, 'bcm499', 'smartstore_2');
