INSERT INTO mapping (
  site,
  "siteUrl",
  "categoryName",
  "godoMallCategoryName",
  "godoMallCategoryCode",
  designers,
  "afterDesigners",
  "customId",
  "accountPlatform"
) VALUES
('Sandro', 'https://fr.sandro-paris.com/fr/femme/ceintures/', 'WOMAN - ACCESSORIES - Belts', '패션잡화>벨트>여성벨트', '50000539', NULL, NULL, 'bcm499', 'smartstore_2'),
('Sandro', 'https://fr.sandro-paris.com/fr/femme/robes/', 'WOMAN - READY-TO-WEAR - Dresses', '패션의류>여성의류>원피스', '50000807', NULL, NULL, 'bcm499', 'smartstore_2'),
('Sandro', 'https://fr.sandro-paris.com/fr/femme/ensembles/', 'WOMAN - READY-TO-WEAR - Outfits', '패션의류>여성의류>정장세트', '50000816', NULL, NULL, 'bcm499', 'smartstore_2'),
('Sandro', 'https://fr.sandro-paris.com/fr/femme/blousons-vestes/', 'WOMAN - READY-TO-WEAR - Jackets & Coats', '패션의류>여성의류>아우터>재킷', '50021360', NULL, NULL, 'bcm499', 'smartstore_2'),
('Sandro', 'https://fr.sandro-paris.com/fr/femme/pulls-cardigans/', 'WOMAN - READY-TO-WEAR - Sweaters & Cardigans', '패션의류>여성의류>니트>풀오버', '50021299', NULL, NULL, 'bcm499', 'smartstore_2'),
('Sandro', 'https://fr.sandro-paris.com/fr/femme/tops-chemises/', 'WOMAN - READY-TO-WEAR - Tops & Shirts', '패션의류>여성의류>블라우스/셔츠', '50000804', NULL, NULL, 'bcm499', 'smartstore_2'),
('Sandro', 'https://fr.sandro-paris.com/fr/femme/tailleurs/', 'WOMAN - READY-TO-WEAR - Suits', '패션의류>여성의류>정장세트', '50000816', NULL, NULL, 'bcm499', 'smartstore_2'),
('Sandro', 'https://fr.sandro-paris.com/fr/femme/pantalons/', 'WOMAN - READY-TO-WEAR - Trousers & Jeans', '패션의류>여성의류>바지', '50000810', NULL, NULL, 'bcm499', 'smartstore_2'),
('Sandro', 'https://fr.sandro-paris.com/fr/femme/jupes-shorts/', 'WOMAN - READY-TO-WEAR - Skirts & Shorts', '패션의류>여성의류>스커트', '50000808', NULL, NULL, 'bcm499', 'smartstore_2'),
('Sandro', 'https://fr.sandro-paris.com/fr/femme/t-shirts/', 'WOMAN - READY-TO-WEAR - T-Shirts', '패션의류>여성의류>티셔츠', '50000803', NULL, NULL, 'bcm499', 'smartstore_2'),
('Sandro', 'https://fr.sandro-paris.com/fr/femme/sacs-a-bandouliere/', 'WOMAN - BAGS - Shoulder Bags', '패션잡화>여성가방>크로스백', '50000641', NULL, NULL, 'bcm499', 'smartstore_2'),
('Sandro', 'https://fr.sandro-paris.com/fr/femme/sacs-porte-epaule/', 'WOMAN - BAGS - Shoulder Bags', '패션잡화>여성가방>숄더백', '50000639', NULL, NULL, 'bcm499', 'smartstore_2'),
('Sandro', 'https://fr.sandro-paris.com/fr/femme/sacs-cabas/', 'WOMAN - SACS - Sacs cabas', '패션잡화>여성가방>토트백', '50000640', NULL, NULL, 'bcm499', 'smartstore_2'),
('Sandro', 'https://fr.sandro-paris.com/fr/femme/baskets/', 'WOMAN - SHOES - Sneakers', '패션잡화>여성신발>단화>스니커즈', '50003822', NULL, NULL, 'bcm499', 'smartstore_2'),
('Sandro', 'https://fr.sandro-paris.com/fr/femme/mocassins-mules/', 'WOMAN - SHOES - Moccasins', '패션잡화>여성신발>단화>로퍼', '50003818', NULL, NULL, 'bcm499', 'smartstore_2'),
('Sandro', 'https://fr.sandro-paris.com/fr/femme/bottines/', 'WOMAN - SHOES - Boots & Ankle Boots', '패션잡화>여성신발>부츠>앵클/숏부츠', '50004191', NULL, NULL, 'bcm499', 'smartstore_2'),
('Sandro', 'https://fr.sandro-paris.com/fr/femme/sandales-a-talons/', 'WOMAN - SHOES - Sandals & Mules', '패션잡화>여성신발>샌들>스트랩샌들', '50003842', NULL, NULL, 'bcm499', 'smartstore_2'),
('Sandro', 'https://fr.sandro-paris.com/fr/femme/foulards-echarpes/', 'WOMAN - ACCESSORIES - Scarves & Shawls', '패션잡화>패션소품>스카프>롱', '50004010', NULL, NULL, 'bcm499', 'smartstore_2'),
('Sandro', 'https://fr.sandro-paris.com/fr/femme/casquettes-bobs/', 'WOMAN - ACCESSORIES - Caps & Bucket Hats', '패션잡화>모자>사파리모자', '50000546', NULL, NULL, 'bcm499', 'smartstore_2'),
('Sandro', 'https://fr.sandro-paris.com/fr/femme/accessoires-cheveux/', 'WOMAN - ACCESSORIES - Hair Accessories', '패션잡화>헤어액세서리>헤어액세서리소품', '50000563', NULL, NULL, 'bcm499', 'smartstore_2'),
('Sandro', 'https://fr.sandro-paris.com/fr/femme/lunettes-de-soleil/', 'WOMAN - ACCESSORIES - Sunglasses', '패션잡화>선글라스/안경테>선글라스', '50000554', NULL, NULL, 'bcm499', 'smartstore_2'),
('Sandro', 'https://fr.sandro-paris.com/fr/homme/trenchs-manteaux/', 'MAN - READY-TO-WEAR - Jackets & Coats', '패션의류>남성의류>아우터>재킷', '50021640', NULL, NULL, 'bcm499', 'smartstore_2'),
('Sandro', 'https://fr.sandro-paris.com/fr/homme/blousons-vestes/', 'MAN - READY-TO-WEAR - Jackets & Blazers', '패션의류>남성의류>아우터>재킷', '50021640', NULL, NULL, 'bcm499', 'smartstore_2'),
('Sandro', 'https://fr.sandro-paris.com/fr/homme/pulls-cardigans/', 'MAN - READY-TO-WEAR - Sweaters & Cardigans', '패션의류>남성의류>니트>풀오버', '50021579', NULL, NULL, 'bcm499', 'smartstore_2'),
('Sandro', 'https://fr.sandro-paris.com/fr/homme/chemises/', 'MAN - READY-TO-WEAR - Shirts', '패션의류>남성의류>셔츠/남방', '50000833', NULL, NULL, 'bcm499', 'smartstore_2'),
('Sandro', 'https://fr.sandro-paris.com/fr/homme/costumes-smokings/', 'MAN - READY-TO-WEAR - Suits & Tuxedos', '패션의류>남성의류>정장세트', '50000840', NULL, NULL, 'bcm499', 'smartstore_2'),
('Sandro', 'https://fr.sandro-paris.com/fr/homme/pantalons-shorts/', 'MEN - READY-TO-WEAR - Trousers & Shorts', '패션의류>남성의류>바지', '50000836', NULL, NULL, 'bcm499', 'smartstore_2'),
('Sandro', 'https://fr.sandro-paris.com/fr/homme/t-shirts-polos/', 'MEN - READY-TO-WEAR - T-Shirts & Polos', '패션의류>남성의류>티셔츠', '50000830', NULL, NULL, 'bcm499', 'smartstore_2'),
('Sandro', 'https://fr.sandro-paris.com/fr/homme/ensembles/', 'MAN - READY-TO-WEAR - Suits', '패션의류>남성의류>정장세트', '50000840', NULL, NULL, 'bcm499', 'smartstore_2'),
('Sandro', 'https://fr.sandro-paris.com/fr/homme/sneakers/', 'MAN - CHAUSSURES - Sneakers', '패션잡화>남성신발>스니커즈', '50000788', NULL, NULL, 'bcm499', 'smartstore_2'),
('Sandro', 'https://fr.sandro-paris.com/fr/homme/chaussures-villes/', 'MEN - SHOES - Derbies & Loafers', '패션잡화>남성신발>구두', '50000787', NULL, NULL, 'bcm499', 'smartstore_2'),
('Sandro', 'https://fr.sandro-paris.com/fr/homme/sandales/', 'MAN - SHOES - Sandals', '패션잡화>남성신발>샌들', '50000789', NULL, NULL, 'bcm499', 'smartstore_2'),
('Sandro', 'https://fr.sandro-paris.com/fr/homme/sacs-a-bandouliere/', 'MAN - ACCESSORIES - Shoulder Bags', '패션잡화>남성가방>크로스백', '50000648', NULL, NULL, 'bcm499', 'smartstore_2'),
('Sandro', 'https://fr.sandro-paris.com/fr/homme/sacs-business/', 'MAN - ACCESSORIES - Business Bags', '패션잡화>남성가방>브리프케이스', '50000650', NULL, NULL, 'bcm499', 'smartstore_2'),
('Sandro', 'https://fr.sandro-paris.com/fr/homme/sacs-a-dos/', 'MAN - ACCESSORIES - Backpacks', '패션잡화>남성가방>백팩', '50000651', NULL, NULL, 'bcm499', 'smartstore_2'),
('Sandro', 'https://fr.sandro-paris.com/fr/homme/grands-sacs/', 'MAN - ACCESSORIES - Large bags', '패션잡화>남성가방>토트백', '50000647', NULL, NULL, 'bcm499', 'smartstore_2'),
('Sandro', 'https://fr.sandro-paris.com/fr/homme/ceintures/', 'MAN - ACCESSORIES - Belts', '패션잡화>벨트>남성벨트>캐주얼벨트', '50003989', NULL, NULL, 'bcm499', 'smartstore_2'),
('Sandro', 'https://fr.sandro-paris.com/fr/homme/casquettes-bobs/', 'MAN - ACCESSORIES - Caps & Bucket Hats', '패션잡화>모자>사파리모자', '50000546', NULL, NULL, 'bcm499', 'smartstore_2'),
('Sandro', 'https://fr.sandro-paris.com/fr/homme/lunettes-de-soleil/', 'MAN - ACCESSORIES - Sunglasses', '패션잡화>선글라스/안경테>선글라스', '50000554', NULL, NULL, 'bcm499', 'smartstore_2');
