INSERT INTO mapping (
  site,
  "siteUrl",
  "categoryName",
  "godoMallCategoryName",
  "godoMallCategoryCode",
  designers,
  "afterDesigners",
  "customId",
  "accountPlatform"
) VALUES
('Thombrowne', 'https://www.thombrowne.com/en-eu/collections/mens-knitwear-sweaters', 'MEN - READY TO WEAR - KNITWEAR & SWEATERS', '패션의류>남성의류>니트>풀오버', '50021579', NULL, NULL, 'bcm499', 'smartstore_2'),
('Thombrowne', 'https://www.thombrowne.com/en-eu/collections/mens-sport-coats-tailoring', 'MEN - READY TO WEAR - SPORT COATS & TAILORING', '패션의류>남성의류>아우터>재킷', '50021640', NULL, NULL, 'bcm499', 'smartstore_2'),
('Thombrowne', 'https://www.thombrowne.com/en-eu/collections/mens-shirting', 'MEN - READY TO WEAR - SHIRTS', '패션의류>남성의류>셔츠/남방', '50000833', NULL, NULL, 'bcm499', 'smartstore_2'),
('Thombrowne', 'https://www.thombrowne.com/en-eu/collections/mens-suits', 'MEN - READY TO WEAR - SUITS', '패션의류>남성의류>정장세트', '50000840', NULL, NULL, 'bcm499', 'smartstore_2'),
('Thombrowne', 'https://www.thombrowne.com/en-eu/collections/mens-outerwear', 'MEN - READY TO WEAR - COATS & OUTERWEAR', '패션의류>남성의류>아우터>재킷', '50021640', NULL, NULL, 'bcm499', 'smartstore_2'),
('Thombrowne', 'https://www.thombrowne.com/en-eu/collections/mens-pants', 'MEN - READY TO WEAR - PANTS', '패션의류>남성의류>바지', '50000836', NULL, NULL, 'bcm499', 'smartstore_2'),
('Thombrowne', 'https://www.thombrowne.com/en-eu/collections/mens-casual-and-shirt-jackets', 'MEN - READY TO WEAR - CASUAL & SHIRT JACKETS', '패션의류>남성의류>아우터>재킷', '50021640', NULL, NULL, 'bcm499', 'smartstore_2'),
('Thombrowne', 'https://www.thombrowne.com/en-eu/collections/mens-t-shirts-polos', 'MEN - READY TO WEAR - T-SHIRTS & POLOS', '패션의류>남성의류>티셔츠', '50000830', NULL, NULL, 'bcm499', 'smartstore_2'),
('Thombrowne', 'https://www.thombrowne.com/en-eu/collections/mens-shorts', 'MEN - READY TO WEAR - SHORTS', '패션의류>남성의류>바지', '50000836', NULL, NULL, 'bcm499', 'smartstore_2'),
('Thombrowne', 'https://www.thombrowne.com/en-eu/collections/mens-briefcase-totes', 'MEN - BAGS & LEATHER GOODS - BRIEFCASES & TOTES', '패션잡화>남성가방>브리프케이스', '50000650', NULL, NULL, 'bcm499', 'smartstore_2'),
('Thombrowne', 'https://www.thombrowne.com/en-eu/collections/mens-crossbody-bags', 'MEN - BAGS & LEATHER GOODS - CROSSBODY BAGS', '패션잡화>남성가방>크로스백', '50000648', NULL, NULL, 'bcm499', 'smartstore_2'),
('Thombrowne', 'https://www.thombrowne.com/en-eu/collections/mens-backpacks-belt-bags', 'MEN - BAGS & LEATHER GOODS - BACKPACKS', '패션잡화>남성가방>백팩', '50000651', NULL, NULL, 'bcm499', 'smartstore_2'),
('Thombrowne', 'https://www.thombrowne.com/en-eu/collections/mens-wallets-cardholders', 'MEN - BAGS & LEATHER GOODS - WALLETS & CARDHOLDERS', '패션잡화>지갑>카드/명함지갑', '50000662', NULL, NULL, 'bcm499', 'smartstore_2'),
('Thombrowne', 'https://www.thombrowne.com/en-eu/collections/mens-brogues-loafers', 'MEN - FOOTWEAR - BROGUES & LOAFERS', '패션잡화>남성신발>구두', '50000787', NULL, NULL, 'bcm499', 'smartstore_2'),
('Thombrowne', 'https://www.thombrowne.com/en-eu/collections/mens-sneakers', 'MEN - FOOTWEAR - SNEAKERS', '패션잡화>남성신발>스니커즈', '50000788', NULL, NULL, 'bcm499', 'smartstore_2'),
('Thombrowne', 'https://www.thombrowne.com/en-eu/collections/mens-boots', 'MEN - FOOTWEAR - BOOTS', '패션잡화>남성신발>부츠>앵클/숏부츠', '50021999', NULL, NULL, 'bcm499', 'smartstore_2'),
('Thombrowne', 'https://www.thombrowne.com/en-eu/collections/mens-slippers-sandals', 'MEN - FOOTWEAR - SANDALS', '패션잡화>남성신발>샌들', '50000789', NULL, NULL, 'bcm499', 'smartstore_2'),
('Thombrowne', 'https://www.thombrowne.com/en-eu/collections/eyeglasses', 'MEN - ACCESSORIES - EYEGLASSES', '패션잡화>선글라스/안경테>안경테', '50000556', NULL, NULL, 'bcm499', 'smartstore_2'),
('Thombrowne', 'https://www.thombrowne.com/en-eu/collections/sunglasses', 'MEN - ACCESSORIES - SUNGLASSES', '패션잡화>선글라스/안경테>선글라스', '50000554', NULL, NULL, 'bcm499', 'smartstore_2'),
('Thombrowne', 'https://www.thombrowne.com/en-eu/collections/mens-hats', 'MEN - ACCESSORIES - HATS', '패션잡화>모자>사파리모자', '50000546', NULL, NULL, 'bcm499', 'smartstore_2'),
('Thombrowne', 'https://www.thombrowne.com/en-eu/collections/ties', 'MEN - ACCESSORIES - TIES & TIE BARS', '패션잡화>패션소품>넥타이>기본넥타이', '50004014', NULL, NULL, 'bcm499', 'smartstore_2'),
('Thombrowne', 'https://www.thombrowne.com/en-eu/collections/womens-knitwear', 'WOMEN - READY TO WEAR - KNITWEAR & SWEATERS', '패션의류>여성의류>니트>풀오버', '50021299', NULL, NULL, 'bcm499', 'smartstore_2'),
('Thombrowne', 'https://www.thombrowne.com/en-eu/collections/womens-tops-shirts', 'WOMEN - READY TO WEAR - TOPS & SHIRTS', '패션의류>여성의류>블라우스/셔츠', '50000804', NULL, NULL, 'bcm499', 'smartstore_2'),
('Thombrowne', 'https://www.thombrowne.com/en-eu/collections/womens-dresses', 'WOMEN - READY TO WEAR - DRESSES', '패션의류>여성의류>원피스', '50000807', NULL, NULL, 'bcm499', 'smartstore_2'),
('Thombrowne', 'https://www.thombrowne.com/en-eu/collections/womens-sport-coats-tailoring', 'WOMEN - READY TO WEAR - SPORT COAT & TAILORING', '패션의류>여성의류>아우터>재킷', '50021360', NULL, NULL, 'bcm499', 'smartstore_2'),
('Thombrowne', 'https://www.thombrowne.com/en-eu/collections/womens-outerwear', 'WOMEN - READY TO WEAR - COATS & OUTERWEAR', '패션의류>여성의류>아우터>재킷', '50021360', NULL, NULL, 'bcm499', 'smartstore_2'),
('Thombrowne', 'https://www.thombrowne.com/en-eu/collections/womens-skirts', 'WOMEN - READY TO WEAR - SKIRTS', '패션의류>여성의류>스커트', '50000808', NULL, NULL, 'bcm499', 'smartstore_2'),
('Thombrowne', 'https://www.thombrowne.com/en-eu/collections/womens-t-shirts-and-polos', 'WOMEN - READY TO WEAR - T-SHIRTS & POLOS', '패션의류>여성의류>티셔츠', '50000803', NULL, NULL, 'bcm499', 'smartstore_2'),
('Thombrowne', 'https://www.thombrowne.com/en-eu/collections/womens-casual-jackets', 'WOMEN - READY TO WEAR - CASUAL JACKETS', '패션의류>여성의류>아우터>재킷', '50021360', NULL, NULL, 'bcm499', 'smartstore_2'),
('Thombrowne', 'https://www.thombrowne.com/en-eu/collections/womens-pants-shorts', 'WOMEN - READY TO WEAR - PANTS & SHORTS', '패션의류>여성의류>바지', '50000810', NULL, NULL, 'bcm499', 'smartstore_2'),
('Thombrowne', 'https://www.thombrowne.com/en-eu/collections/womens-totes-top-handle-bags', 'WOMEN - BAGS & LEATHER GOODS - TOTES & TOP HANDLE BAGS', '패션잡화>여성가방>토트백', '50000640', NULL, NULL, 'bcm499', 'smartstore_2'),
('Thombrowne', 'https://www.thombrowne.com/en-eu/collections/womens-crossbody-bags', 'WOMEN - BAGS & LEATHER GOODS - CROSSBODY BAGS', '패션잡화>여성가방>크로스백', '50000641', NULL, NULL, 'bcm499', 'smartstore_2'),
('Thombrowne', 'https://www.thombrowne.com/en-eu/collections/womens-purses-wallets', 'WOMEN - BAGS & LEATHER GOODS - PURSES & WALLETS', '패션잡화>지갑>여성지갑>반지갑', '50003982', NULL, NULL, 'bcm499', 'smartstore_2'),
('Thombrowne', 'https://www.thombrowne.com/en-eu/collections/womens-pouches', 'WOMEN - BAGS & LEATHER GOODS - POUCHES', '패션잡화>여성가방>파우치', '50000643', NULL, NULL, 'bcm499', 'smartstore_2'),
('Thombrowne', 'https://www.thombrowne.com/en-eu/collections/womens-brogues-loafers', 'WOMEN - FOOTWEAR - BROGUES & LOAFERS', '패션잡화>여성신발>단화>로퍼', '50003818', NULL, NULL, 'bcm499', 'smartstore_2'),
('Thombrowne', 'https://www.thombrowne.com/en-eu/collections/womens-heels', 'WOMEN - FOOTWEAR - HEELS', '패션잡화>여성신발>힐/펌프스>펌프스', '50003830', NULL, NULL, 'bcm499', 'smartstore_2'),
('Thombrowne', 'https://www.thombrowne.com/en-eu/collections/womens-boots', 'WOMEN - FOOTWEAR - BOOTS', '패션잡화>여성신발>부츠>앵클/숏부츠', '50004191', NULL, NULL, 'bcm499', 'smartstore_2'),
('Thombrowne', 'https://www.thombrowne.com/en-eu/collections/womens-slippers-sandals', 'WOMEN - FOOTWEAR - SLIPPERS & SANDALS', '패션잡화>여성신발>샌들>스트랩샌들', '50003842', NULL, NULL, 'bcm499', 'smartstore_2'),
('Thombrowne', 'https://www.thombrowne.com/en-eu/collections/womens-sneakers', 'WOMEN - FOOTWEAR - SNEAKERS', '패션잡화>여성신발>단화>스니커즈', '50003822', NULL, NULL, 'bcm499', 'smartstore_2'),
('Thombrowne', 'https://www.thombrowne.com/en-eu/collections/eyeglasses', 'WOMEN - ACCESSORIES - EYEGLASSES', '패션잡화>선글라스/안경테>안경테', '50000556', NULL, NULL, 'bcm499', 'smartstore_2'),
('Thombrowne', 'https://www.thombrowne.com/en-eu/collections/sunglasses', 'WOMEN - ACCESSORIES - SUNGLASSES', '패션잡화>선글라스/안경테>선글라스', '50000554', NULL, NULL, 'bcm499', 'smartstore_2'),
('Thombrowne', 'https://www.thombrowne.com/en-eu/collections/ties', 'WOMEN - ACCESSORIES - TIES & TIE BARS', '패션잡화>패션소품>넥타이>기본넥타이', '50004014', NULL, NULL, 'bcm499', 'smartstore_2'),
('Thombrowne', 'https://www.thombrowne.com/en-eu/collections/brooches', 'WOMEN - ACCESSORIES - BROOCHES', '패션잡화>패션소품>브로치>패션브로치', '50004028', NULL, NULL, 'bcm499', 'smartstore_2'),
('Thombrowne', 'https://www.thombrowne.com/en-eu/collections/womens-hair-accessories', 'WOMEN - ACCESSORIES - HAIR ACCESSORIES', '패션잡화>헤어액세서리>헤어액세서리소품', '50000563', NULL, NULL, 'bcm499', 'smartstore_2');
