INSERT INTO mapping (
  site,
  "siteUrl",
  "categoryName",
  "godoMallCategoryName",
  "godoMallCategoryCode",
  designers,
  "afterDesigners",
  "customId",
  "accountPlatform"
) VALUES
('Tods', 'https://www.tods.com/fr-fr/Femme/Chaussures/Mocassins/c/114-Tods/', 'WOMEN - Shoes - Loafers', '패션잡화>여성신발>단화>로퍼', '50003818', NULL, NULL, 'bcm499', 'smartstore_2'),
('Tods', 'https://www.tods.com/fr-fr/Femme/Chaussures/Gommino-et-City-Gommino/c/111-Tods/', 'WOMEN - Shoes - Mocassin Gommino® ＆ Mocassin Gommino® CityNEW', '패션잡화>여성신발>단화>로퍼', '50003818', NULL, NULL, 'bcm499', 'smartstore_2'),
('Tods', 'https://www.tods.com/fr-fr/Femme/Chaussures/Baskets/c/118-Tods/', 'WOMEN - Chaussures - Sneakers', '패션잡화>여성신발>단화>스니커즈', '50003822', NULL, NULL, 'bcm499', 'smartstore_2'),
('Tods', 'https://www.tods.com/fr-fr/Femme/Chaussures/Escarpins/c/116-Tods/', 'WOMEN - Shoes - Pumps', '패션잡화>여성신발>힐/펌프스>펌프스', '50003830', NULL, NULL, 'bcm499', 'smartstore_2'),
('Tods', 'https://www.tods.com/fr-fr/Femme/Chaussures/Sandales-et-Mules/c/176-Tods/', 'WOMEN - Shoes - Sandals and Mules NEW', '패션잡화>여성신발>샌들>스트랩샌들', '50003842', NULL, NULL, 'bcm499', 'smartstore_2'),
('Tods', 'https://www.tods.com/fr-fr/Femme/Chaussures/Ballerines/c/113-Tods/', 'WOMEN - Shoes - Ballerinas', '패션잡화>여성신발>단화>플랫', '50003817', NULL, NULL, 'bcm499', 'smartstore_2'),
('Tods', 'https://www.tods.com/fr-fr/Femme/Chaussures/Bottes-et-Bottines/c/117-Tods/', 'WOMEN - Shoes - Boots and Ankle Boots', '패션잡화>여성신발>부츠>앵클/숏부츠', '50004191', NULL, NULL, 'bcm499', 'smartstore_2'),
('Tods', 'https://www.tods.com/fr-fr/Femme/Sacs/Sacs-Cabas/c/123-Tods/', 'WOMEN - Sacs - Sacs Cabas', '패션잡화>여성가방>토트백', '50000640', NULL, NULL, 'bcm499', 'smartstore_2'),
('Tods', 'https://www.tods.com/fr-fr/Femme/Sacs/Sacs-%C3%A0-main/c/121-Tods/', 'WOMEN - Sacs - Sacs', '패션잡화>여성가방>토트백', '50000640', NULL, NULL, 'bcm499', 'smartstore_2'),
('Tods', 'https://www.tods.com/fr-fr/Femme/Sacs/Sacs-port%C3%A9s-%C3%A9paule-et-Sacs-%C3%A0-bandouli%C3%A8re/c/122-Tods/', 'WOMEN - Bags - Shoulder Bags and Crossbody Bags', '패션잡화>여성가방>숄더백', '50000639', NULL, NULL, 'bcm499', 'smartstore_2'),
('Tods', 'https://www.tods.com/fr-fr/Femme/Sacs/Sacs-Seau/c/154-Tods/', 'WOMEN - Bags - Bucket Bags', '패션잡화>여성가방>숄더백', '50000639', NULL, NULL, 'bcm499', 'smartstore_2'),
('Tods', 'https://www.tods.com/fr-fr/Femme/Accessoires/Portefeuilles-et-Porte-cartes/c/131-Tods/', 'WOMEN - Accessories - Wallets and Card Holders', '패션잡화>지갑>카드/명함지갑', '50000662', NULL, NULL, 'bcm499', 'smartstore_2'),
('Tods', 'https://www.tods.com/fr-fr/Femme/Accessoires/Lunettes-de-soleil/c/135-Tods/', 'WOMEN - Accessories - Sunglasses', '패션잡화>선글라스/안경테>선글라스', '50000554', NULL, NULL, 'bcm499', 'smartstore_2'),
('Tods', 'https://www.tods.com/fr-fr/Femme/Must-have/Robes/c/168-Tods/', 'WOMEN - Ready-to-wear - Dresses', '패션의류>여성의류>원피스', '50000807', NULL, NULL, 'bcm499', 'smartstore_2'),
('Tods', 'https://www.tods.com/fr-fr/Femme/Must-have/Pulls/c/166-Tods/', 'WOMEN - Ready-to-wear - Sweaters NEW', '패션의류>여성의류>니트>풀오버', '50021299', NULL, NULL, 'bcm499', 'smartstore_2'),
('Tods', 'https://www.tods.com/fr-fr/Femme/Chemises-et-Tops/c/164-Tods/', 'WOMEN - Ready-to-wear - Shirts and Tops NEW', '패션의류>여성의류>블라우스/셔츠', '50000804', NULL, NULL, 'bcm499', 'smartstore_2'),
('Tods', 'https://www.tods.com/fr-fr/Femme/Must-have/Pantalons-et-Jupes/c/163-Tods/', 'WOMEN - Ready-to-wear - Trousers and Skirts', '패션의류>여성의류>바지', '50000810', NULL, NULL, 'bcm499', 'smartstore_2'),
('Tods', 'https://www.tods.com/fr-fr/Femme/Must-have/V%C3%AAtement-de-Dessus/c/151-Tods/', 'WOMEN - Ready-to-wear - Outerwear', '패션의류>여성의류>아우터>재킷', '50021360', NULL, NULL, 'bcm499', 'smartstore_2'),
('Tods', 'https://www.tods.com/fr-fr/Homme/Chaussures/Gommino-et-City-Gommino/c/211-Tods/', 'MEN - Shoes - Mocassin Gommino® ＆ Mocassin Gommino® City', '패션잡화>남성신발>구두', '50000787', NULL, NULL, 'bcm499', 'smartstore_2'),
('Tods', 'https://www.tods.com/fr-fr/Homme/Chaussures/Mocassins/c/213-Tods/', 'MEN - Chaussures - MocassinsNEW', '패션잡화>남성신발>구두', '50000787', NULL, NULL, 'bcm499', 'smartstore_2'),
('Tods', 'https://www.tods.com/fr-fr/Homme/Chaussures/Baskets/c/217-Tods/', 'MEN - Chaussures - Sneakers', '패션잡화>남성신발>스니커즈', '50000788', NULL, NULL, 'bcm499', 'smartstore_2'),
('Tods', 'https://www.tods.com/fr-fr/Homme/Chaussures/Slip-on/c/208-Tods/', 'MEN - Chaussures - Slip-on', '패션잡화>남성신발>슬립온', '50000783', NULL, NULL, 'bcm499', 'smartstore_2'),
('Tods', 'https://www.tods.com/fr-fr/Homme/Chaussures/Chaussures-%C3%A0-lacets/c/214-Tods/', 'MEN - Shoes - Lace-up shoes', '패션잡화>남성신발>구두', '50000787', NULL, NULL, 'bcm499', 'smartstore_2'),
('Tods', 'https://www.tods.com/fr-fr/Homme/Chaussures/Bottillons/c/215-Tods/', 'MEN - Shoes - Ankle boots', '패션잡화>남성신발>부츠>앵클/숏부츠', '50021999', NULL, NULL, 'bcm499', 'smartstore_2'),
('Tods', 'https://www.tods.com/fr-fr/Homme/Chaussures/Bottines/c/216-Tods/', 'MEN - Shoes - Ankle Boots', '패션잡화>남성신발>부츠>앵클/숏부츠', '50021999', NULL, NULL, 'bcm499', 'smartstore_2'),
('Tods', 'https://www.tods.com/fr-fr/Homme/V%C3%AAtement-de-Dessus/c/248-Tods/', 'MEN - Ready-to-wear - Outerwear NEW', '패션의류>남성의류>아우터>재킷', '50021640', NULL, NULL, 'bcm499', 'smartstore_2'),
('Tods', 'https://www.tods.com/fr-fr/Homme/Pulls/c/268-Tods/', 'MEN - Ready-to-wear - Sweaters', '패션의류>남성의류>니트>풀오버', '50021579', NULL, NULL, 'bcm499', 'smartstore_2'),
('Tods', 'https://www.tods.com/fr-fr/Homme/Chemises/c/273-Tods/', 'MEN - Ready-to-wear - Shirts', '패션의류>남성의류>셔츠/남방', '50000833', NULL, NULL, 'bcm499', 'smartstore_2'),
('Tods', 'https://www.tods.com/fr-fr/Homme/Polo/c/269-Tods/', 'MEN - Ready-to-wear - PoloNEW', '패션의류>남성의류>티셔츠', '50000830', NULL, NULL, 'bcm499', 'smartstore_2'),
('Tods', 'https://www.tods.com/fr-fr/Homme/T-Shirt/c/270-Tods/', 'MEN - Ready-to-wear - T-Shirt', '패션의류>남성의류>티셔츠', '50000830', NULL, NULL, 'bcm499', 'smartstore_2'),
('Tods', 'https://www.tods.com/fr-fr/Homme/Pantalons/c/285-Tods/', 'MEN - Ready-to-wear - Trousers', '패션의류>남성의류>바지', '50000836', NULL, NULL, 'bcm499', 'smartstore_2'),
('Tods', 'https://www.tods.com/fr-fr/Homme/Ceintures/c/236-Tods/', 'MEN - Belts - View all', '패션잡화>벨트>남성벨트>캐주얼벨트', '50003989', NULL, NULL, 'bcm499', 'smartstore_2'),
('Tods', 'https://www.tods.com/fr-fr/Homme/Ceintures/Ceintures-T-Timeless/c/262-Tods/', 'MEN - Belts - Timeless T Belts', '패션잡화>벨트>남성벨트>캐주얼벨트', '50003989', NULL, NULL, 'bcm499', 'smartstore_2'),
('Tods', 'https://www.tods.com/fr-fr/Homme/Ceintures/Ceintures-formelles/c/263-Tods/', 'MEN - Belts - Formal Belts', '패션잡화>벨트>남성벨트>정장벨트', '50003988', NULL, NULL, 'bcm499', 'smartstore_2'),
('Tods', 'https://www.tods.com/fr-fr/Homme/Ceintures/Ceintures-d%C3%A9contract%C3%A9es/c/266-Tods/', 'MEN - Belts - Casual Belts', '패션잡화>벨트>남성벨트>캐주얼벨트', '50003989', NULL, NULL, 'bcm499', 'smartstore_2'),
('Tods', 'https://www.tods.com/fr-fr/Homme/Sacs/Sacs-%C3%A0-dos-et-Sacs-%C3%A0-bandouli%C3%A8re/c/222-Tods/', 'MEN - Bags - Backpacks and Shoulder Bags', '패션잡화>남성가방>백팩', '50000651', NULL, NULL, 'bcm499', 'smartstore_2'),
('Tods', 'https://www.tods.com/fr-fr/Homme/Sacs/Sacs/c/223-Tods/', 'MEN - Bags - Handbags', '패션잡화>남성가방>토트백', '50000647', NULL, NULL, 'bcm499', 'smartstore_2'),
('Tods', 'https://www.tods.com/fr-fr/Homme/Accessoires/Portefeuilles-et-Porte-cartes/c/231-Tods/', 'MEN - Accessories - Wallets and Card Holders', '패션잡화>지갑>카드/명함지갑', '50000662', NULL, NULL, 'bcm499', 'smartstore_2'),
('Tods', 'https://www.tods.com/fr-fr/Homme/Accessoires/Bracelets/c/235-Tods/', 'MEN - Accessories - Bracelets', '패션잡화>주얼리>팔찌>패션팔찌', '50004194', NULL, NULL, 'bcm499', 'smartstore_2'),
('Tods', 'https://www.tods.com/fr-fr/Homme/Accessoires/Lunettes-de-soleil/c/238-Tods/', 'MEN - Accessories - Sunglasses', '패션잡화>선글라스/안경테>선글라스', '50000554', NULL, NULL, 'bcm499', 'smartstore_2');
