INSERT INTO mapping (
  site,
  "siteUrl",
  "categoryName",
  "godoMallCategoryName",
  "godoMallCategoryCode",
  designers,
  "afterDesigners",
  "customId",
  "accountPlatform"
) VALUES
('Tomford', 'https://www.tomfordfashion.fr/en-fr/men/ready-to-wear/outerwear/', '남성 - Ready to Wear - Outerwear', '패션의류>남성의류>아우터>재킷', '50021640', NULL, NULL, 'bcm499', 'smartstore_2'),
('Tomford', 'https://www.tomfordfashion.fr/en-fr/men/ready-to-wear/knitwear/', '남성 - Ready to Wear - Knitwear', '패션의류>남성의류>니트>풀오버', '50021579', NULL, NULL, 'bcm499', 'smartstore_2'),
('Tomford', 'https://www.tomfordfashion.fr/en-fr/men/ready-to-wear/jackets/', '남성 - Ready to Wear - Jackets', '패션의류>남성의류>아우터>재킷', '50021640', NULL, NULL, 'bcm499', 'smartstore_2'),
('Tomford', 'https://www.tomfordfashion.fr/en-fr/men/ready-to-wear/suits-and-tuxedos/', '남성 - Ready to Wear - Suits & Tuxedos', '패션의류>남성의류>정장세트', '50000840', NULL, NULL, 'bcm499', 'smartstore_2'),
('Tomford', 'https://www.tomfordfashion.fr/en-fr/men/ready-to-wear/shirts/', '남성 - Ready to Wear - Shirts', '패션의류>남성의류>셔츠/남방', '50000833', NULL, NULL, 'bcm499', 'smartstore_2'),
('Tomford', 'https://www.tomfordfashion.fr/en-fr/men/ready-to-wear/polos-and-t-shirts/', '남성 - Ready to Wear - Polos & T-Shirts', '패션의류>남성의류>티셔츠', '50000830', NULL, NULL, 'bcm499', 'smartstore_2'),
('Tomford', 'https://www.tomfordfashion.fr/en-fr/men/ready-to-wear/pants-and-shorts/', '남성 - Ready to Wear - Pants & Shorts', '패션의류>남성의류>바지', '50000836', NULL, NULL, 'bcm499', 'smartstore_2'),
('Tomford', 'https://www.tomfordfashion.fr/en-fr/men/shoes/lace-ups/', '남성 - Shoes - Lace-ups', '패션잡화>남성신발>구두', '50000787', NULL, NULL, 'bcm499', 'smartstore_2'),
('Tomford', 'https://www.tomfordfashion.fr/en-fr/men/shoes/monk-straps/', '남성 - Shoes - Monk Straps', '패션잡화>남성신발>구두', '50000787', NULL, NULL, 'bcm499', 'smartstore_2'),
('Tomford', 'https://www.tomfordfashion.fr/en-fr/men/shoes/boots/', '남성 - Shoes - Boots', '패션잡화>남성신발>부츠>앵클/숏부츠', '50021999', NULL, NULL, 'bcm499', 'smartstore_2'),
('Tomford', 'https://www.tomfordfashion.fr/en-fr/men/shoes/loafers/', '남성 - Shoes - Loafers', '패션잡화>남성신발>구두', '50000787', NULL, NULL, 'bcm499', 'smartstore_2'),
('Tomford', 'https://www.tomfordfashion.fr/en-fr/men/shoes/sneakers/', '남성 - Shoes - Sneakers', '패션잡화>남성신발>스니커즈', '50000788', NULL, NULL, 'bcm499', 'smartstore_2'),
('Tomford', 'https://www.tomfordfashion.fr/en-fr/men/shoes/espadrilles-and-sandals/', '남성 - Shoes - Espadrilles & Sandals', '패션잡화>남성신발>샌들', '50000789', NULL, NULL, 'bcm499', 'smartstore_2'),
('Tomford', 'https://www.tomfordfashion.fr/en-fr/men/shoes/evening/', '남성 - Shoes - Evening', '패션잡화>남성신발>구두', '50000787', NULL, NULL, 'bcm499', 'smartstore_2'),
('Tomford', 'https://www.tomfordfashion.fr/en-fr/men/bags/backpacks/', '남성 - Bags - Backpacks', '패션잡화>남성가방>백팩', '50000651', NULL, NULL, 'bcm499', 'smartstore_2'),
('Tomford', 'https://www.tomfordfashion.fr/en-fr/men/bags/briefcases/', '남성 - Bags - Briefcases', '패션잡화>남성가방>브리프케이스', '50000650', NULL, NULL, 'bcm499', 'smartstore_2'),
('Tomford', 'https://www.tomfordfashion.fr/en-fr/men/accessories/belts/', '남성 - Accessories - Belts', '패션잡화>벨트>남성벨트>캐주얼벨트', '50003989', NULL, NULL, 'bcm499', 'smartstore_2'),
('Tomford', 'https://www.tomfordfashion.fr/en-fr/men/accessories/wallets-and-card-holders/', '남성 - Accessories - Wallets & Card Holders', '패션잡화>지갑>카드/명함지갑', '50000662', NULL, NULL, 'bcm499', 'smartstore_2'),
('Tomford', 'https://www.tomfordfashion.fr/en-fr/men/accessories/ties-and-bow-ties/', '남성 - Accessories - Ties & Bow Ties', '패션잡화>패션소품>넥타이>기본넥타이', '50004014', NULL, NULL, 'bcm499', 'smartstore_2'),
('Tomford', 'https://www.tomfordfashion.fr/en-fr/men/accessories/scarves/', '남성 - Accessories - Scarves', '패션잡화>패션소품>스카프>롱', '50004010', NULL, NULL, 'bcm499', 'smartstore_2'),
('Tomford', 'https://www.tomfordfashion.fr/en-fr/women/ready-to-wear/matching-sets/', '여성 - Ready to Wear - Matching Sets', '패션의류>여성의류>정장세트', '50000816', NULL, NULL, 'bcm499', 'smartstore_2'),
('Tomford', 'https://www.tomfordfashion.fr/en-fr/women/ready-to-wear/dresses/', '여성 - Ready to Wear - Dresses', '패션의류>여성의류>원피스', '50000807', NULL, NULL, 'bcm499', 'smartstore_2'),
('Tomford', 'https://www.tomfordfashion.fr/en-fr/women/ready-to-wear/jackets/', '여성 - Ready to Wear - Jackets', '패션의류>여성의류>아우터>재킷', '50021360', NULL, NULL, 'bcm499', 'smartstore_2'),
('Tomford', 'https://www.tomfordfashion.fr/en-fr/women/ready-to-wear/outerwear/', '여성 - Ready to Wear - Outerwear', '패션의류>여성의류>아우터>재킷', '50021360', NULL, NULL, 'bcm499', 'smartstore_2'),
('Tomford', 'https://www.tomfordfashion.fr/en-fr/women/ready-to-wear/knitwear/', '여성 - Ready to Wear - Knitwear', '패션의류>여성의류>니트>풀오버', '50021299', NULL, NULL, 'bcm499', 'smartstore_2'),
('Tomford', 'https://www.tomfordfashion.fr/en-fr/women/ready-to-wear/tops/', '여성 - Ready to Wear - Tops', '패션의류>여성의류>티셔츠', '50000803', NULL, NULL, 'bcm499', 'smartstore_2'),
('Tomford', 'https://www.tomfordfashion.fr/en-fr/women/ready-to-wear/pants-and-shorts/', '여성 - Ready to Wear - Pants & Shorts', '패션의류>여성의류>바지', '50000810', NULL, NULL, 'bcm499', 'smartstore_2'),
('Tomford', 'https://www.tomfordfashion.fr/en-fr/women/ready-to-wear/skirts/', '여성 - Ready to Wear - Skirts', '패션의류>여성의류>스커트', '50000808', NULL, NULL, 'bcm499', 'smartstore_2'),
('Tomford', 'https://www.tomfordfashion.fr/en-fr/women/shoes/slingbacks-and-pumps/', '여성 - Shoes - Slingbacks & Pumps', '패션잡화>여성신발>힐/펌프스>펌프스', '50003830', NULL, NULL, 'bcm499', 'smartstore_2'),
('Tomford', 'https://www.tomfordfashion.fr/en-fr/women/shoes/sandals/', '여성 - Shoes - Sandals', '패션잡화>여성신발>샌들>스트랩샌들', '50003842', NULL, NULL, 'bcm499', 'smartstore_2'),
('Tomford', 'https://www.tomfordfashion.fr/en-fr/women/shoes/flats/', '여성 - Shoes - Flats', '패션잡화>여성신발>단화>플랫', '50003817', NULL, NULL, 'bcm499', 'smartstore_2'),
('Tomford', 'https://www.tomfordfashion.fr/en-fr/women/shoes/boots/', '여성 - Shoes - Boots', '패션잡화>여성신발>부츠>앵클/숏부츠', '50004191', NULL, NULL, 'bcm499', 'smartstore_2'),
('Tomford', 'https://www.tomfordfashion.fr/en-fr/women/bags/shoulder-bags/', '여성 - Bags - Shoulder Bags', '패션잡화>여성가방>숄더백', '50000639', NULL, NULL, 'bcm499', 'smartstore_2'),
('Tomford', 'https://www.tomfordfashion.fr/en-fr/women/bags/crossbody-bags/', '여성 - Bags - Crossbody Bags', '패션잡화>여성가방>크로스백', '50000641', NULL, NULL, 'bcm499', 'smartstore_2'),
('Tomford', 'https://www.tomfordfashion.fr/en-fr/women/bags/top-handles/', '여성 - Bags - TOP HANDLES', '패션잡화>여성가방>토트백', '50000640', NULL, NULL, 'bcm499', 'smartstore_2'),
('Tomford', 'https://www.tomfordfashion.fr/en-fr/women/bags/tote-bags/', '여성 - Bags - Tote Bags', '패션잡화>여성가방>토트백', '50000640', NULL, NULL, 'bcm499', 'smartstore_2'),
('Tomford', 'https://www.tomfordfashion.fr/en-fr/women/bags/clutches/', '여성 - Bags - Clutches', '패션잡화>여성가방>클러치백', '50000642', NULL, NULL, 'bcm499', 'smartstore_2'),
('Tomford', 'https://www.tomfordfashion.fr/en-fr/women/accessories/belts/', '여성 - Accessories - Belts', '패션잡화>벨트>여성벨트', '50000539', NULL, NULL, 'bcm499', 'smartstore_2'),
('Tomford', 'https://www.tomfordfashion.fr/en-fr/women/accessories/wallets-and-card-holders/', '여성 - Accessories - Wallets & Card Holders', '패션잡화>지갑>카드/명함지갑', '50000662', NULL, NULL, 'bcm499', 'smartstore_2'),
('Tomford', 'https://www.tomfordfashion.fr/en-fr/women/accessories/scarves/', '여성 - Accessories - Scarves', '패션잡화>패션소품>스카프>롱', '50004010', NULL, NULL, 'bcm499', 'smartstore_2'),
('Tomford', 'https://www.tomfordfashion.fr/en-fr/eyewear/men/sunglasses/', '남성 - Eyewear - SUNGLASSES', '패션잡화>선글라스/안경테>선글라스', '50000554', NULL, NULL, 'bcm499', 'smartstore_2'),
('Tomford', 'https://www.tomfordfashion.fr/en-fr/eyewear/men/optical/', '남성 - Eyewear - OPTICAL', '패션잡화>선글라스/안경테>안경테', '50000556', NULL, NULL, 'bcm499', 'smartstore_2'),
('Tomford', 'https://www.tomfordfashion.fr/en-fr/eyewear/women/sunglasses/', '여성 - Eyewear - SUNGLASSES', '패션잡화>선글라스/안경테>선글라스', '50000554', NULL, NULL, 'bcm499', 'smartstore_2'),
('Tomford', 'https://www.tomfordfashion.fr/en-fr/eyewear/women/optical/', '여성 - Eyewear - OPTICAL', '패션잡화>선글라스/안경테>안경테', '50000556', NULL, NULL, 'bcm499', 'smartstore_2');
