INSERT INTO mapping (
  site,
  "siteUrl",
  "categoryName",
  "godoMallCategoryName",
  "godoMallCategoryCode",
  designers,
  "afterDesigners",
  "customId",
  "accountPlatform"
)
VALUES
('Valentino', 'https://www.valentino.com/en-fr/women/ready-to-wear/dresses', '여성 - Ready To Wear - 드레스', '패션의류>여성의류>원피스', '50000807', NULL, NULL, 'bcm499', 'smartstore_2'),
('Valentino', 'https://www.valentino.com/en-fr/women/ready-to-wear/gowns', '여성 - Ready To Wear - 가운', '패션의류>여성의류>원피스', '50000807', NULL, NULL, 'bcm499', 'smartstore_2'),
('Valentino', 'https://www.valentino.com/en-fr/women/ready-to-wear/shirts-and-tops', '여성 - Ready To Wear - 셔츠 & 탑', '패션의류>여성의류>블라우스/셔츠', '50000804', NULL, NULL, 'bcm499', 'smartstore_2'),
('Valentino', 'https://www.valentino.com/en-fr/women/ready-to-wear/coats-and-outerwear', '여성 - Ready To Wear - 코트 & 아우터', '패션의류>여성의류>아우터>재킷', '50021360', NULL, NULL, 'bcm499', 'smartstore_2'),
('Valentino', 'https://www.valentino.com/en-fr/women/ready-to-wear/jackets-and-blazers', '여성 - Ready To Wear - 재킷 & 블레이저', '패션의류>여성의류>아우터>재킷', '50021360', NULL, NULL, 'bcm499', 'smartstore_2'),
('Valentino', 'https://www.valentino.com/en-fr/women/ready-to-wear/knitwear', '여성 - Ready To Wear - 니트웨어', '패션의류>여성의류>니트>풀오버', '50021299', NULL, NULL, 'bcm499', 'smartstore_2'),
('Valentino', 'https://www.valentino.com/en-fr/women/ready-to-wear/t-shirts-and-sweatshirts', '여성 - Ready To Wear - 티셔츠 & 스웨트셔츠', '패션의류>여성의류>티셔츠', '50000803', NULL, NULL, 'bcm499', 'smartstore_2'),
('Valentino', 'https://www.valentino.com/en-fr/women/ready-to-wear/skirts', '여성 - Ready To Wear - 스커트', '패션의류>여성의류>스커트', '50000808', NULL, NULL, 'bcm499', 'smartstore_2'),
('Valentino', 'https://www.valentino.com/en-fr/women/ready-to-wear/pants-and-shorts', '여성 - Ready To Wear - 팬츠 & 쇼츠', '패션의류>여성의류>바지', '50000810', NULL, NULL, 'bcm499', 'smartstore_2'),
('Valentino', 'https://www.valentino.com/en-fr/women/bags/shoulder-bags', '여성 - 가방 - 숄더백', '패션잡화>여성가방>숄더백', '50000639', NULL, NULL, 'bcm499', 'smartstore_2'),
('Valentino', 'https://www.valentino.com/en-fr/women/bags/top-handle-bags', '여성 - 가방 - 탑 핸들 백', '패션잡화>여성가방>토트백', '50000640', NULL, NULL, 'bcm499', 'smartstore_2'),
('Valentino', 'https://www.valentino.com/en-fr/women/bags/totes', '여성 - 가방 - 토트백', '패션잡화>여성가방>토트백', '50000640', NULL, NULL, 'bcm499', 'smartstore_2'),
('Valentino', 'https://www.valentino.com/en-fr/women/bags/clutches', '여성 - 가방 - 클러치', '패션잡화>여성가방>클러치백', '50000642', NULL, NULL, 'bcm499', 'smartstore_2'),
('Valentino', 'https://www.valentino.com/en-fr/women/shoes/pumps', '여성 - 슈즈 - 펌프스 & 슬링백', '패션잡화>여성신발>힐/펌프스>펌프스', '50003830', NULL, NULL, 'bcm499', 'smartstore_2'),
('Valentino', 'https://www.valentino.com/en-fr/women/shoes/ballerinas', '여성 - 슈즈 - 발레리나', '패션잡화>여성신발>단화>플랫', '50003817', NULL, NULL, 'bcm499', 'smartstore_2'),
('Valentino', 'https://www.valentino.com/en-fr/women/shoes/sandals', '여성 - 슈즈 - 샌들', '패션잡화>여성신발>샌들>스트랩샌들', '50003842', NULL, NULL, 'bcm499', 'smartstore_2'),
('Valentino', 'https://www.valentino.com/en-fr/women/shoes/slides-and-thongs', '여성 - 슈즈 - 슬라이드 & 통 샌들', '패션잡화>여성신발>샌들>스트랩샌들', '50003842', NULL, NULL, 'bcm499', 'smartstore_2'),
('Valentino', 'https://www.valentino.com/en-fr/women/shoes/espadrilles-and-wedges', '여성 - 슈즈 - 에스파드류 & 웨지', '패션잡화>여성신발>단화>슬립온', '50003821', NULL, NULL, 'bcm499', 'smartstore_2'),
('Valentino', 'https://www.valentino.com/en-fr/women/shoes/sneakers', '여성 - 슈즈 - 스니커즈', '패션잡화>여성신발>단화>스니커즈', '50003822', NULL, NULL, 'bcm499', 'smartstore_2'),
('Valentino', 'https://www.valentino.com/en-fr/women/shoes/loafers-and-oxfords', '여성 - 슈즈 - 로퍼', '패션잡화>여성신발>단화>로퍼', '50003818', NULL, NULL, 'bcm499', 'smartstore_2'),
('Valentino', 'https://www.valentino.com/en-fr/women/shoes/boots', '여성 - 슈즈 - 부츠 & 앵클부츠', '패션잡화>여성신발>부츠>앵클/숏부츠', '50004191', NULL, NULL, 'bcm499', 'smartstore_2'),
('Valentino', 'https://www.valentino.com/en-fr/women/accessories/wallets-and-card-holders', '여성 - 액세서리 - 지갑 & 카드홀더', '패션잡화>지갑>카드/명함지갑', '50000662', NULL, NULL, 'bcm499', 'smartstore_2'),
('Valentino', 'https://www.valentino.com/en-fr/women/accessories/belts', '여성 - 액세서리 - 벨트', '패션잡화>벨트>여성벨트', '50000539', NULL, NULL, 'bcm499', 'smartstore_2'),
('Valentino', 'https://www.valentino.com/en-fr/women/accessories/eyewear', '여성 - 액세서리 - 아이웨어', '패션잡화>선글라스/안경테>선글라스', '50000554', NULL, NULL, 'bcm499', 'smartstore_2'),
('Valentino', 'https://www.valentino.com/en-fr/men/ready-to-wear/coats-and-blazers', '남성 - Ready to Wear - 코트 & 블레이저', '패션의류>남성의류>아우터>재킷', '50021640', NULL, NULL, 'bcm499', 'smartstore_2'),
('Valentino', 'https://www.valentino.com/en-fr/men/ready-to-wear/suits', '남성 - Ready to Wear - 수트', '패션의류>남성의류>정장세트', '50000840', NULL, NULL, 'bcm499', 'smartstore_2'),
('Valentino', 'https://www.valentino.com/en-fr/men/ready-to-wear/outerwear', '남성 - Ready to Wear - 아우터', '패션의류>남성의류>아우터>재킷', '50021640', NULL, NULL, 'bcm499', 'smartstore_2'),
('Valentino', 'https://www.valentino.com/en-fr/men/ready-to-wear/knitwear', '남성 - Ready to Wear - 니트웨어', '패션의류>남성의류>니트>풀오버', '50021579', NULL, NULL, 'bcm499', 'smartstore_2'),
('Valentino', 'https://www.valentino.com/en-fr/men/ready-to-wear/shirts', '남성 - Ready to Wear - 셔츠', '패션의류>남성의류>셔츠/남방', '50000833', NULL, NULL, 'bcm499', 'smartstore_2'),
('Valentino', 'https://www.valentino.com/en-fr/men/ready-to-wear/t-shirts-and-sweatshirts', '남성 - Ready to Wear - 티셔츠 & 스웨트셔츠', '패션의류>남성의류>티셔츠', '50000830', NULL, NULL, 'bcm499', 'smartstore_2'),
('Valentino', 'https://www.valentino.com/en-fr/men/ready-to-wear/pants-and-shorts', '남성 - Ready to Wear - 팬츠 & 쇼츠', '패션의류>남성의류>바지', '50000836', NULL, NULL, 'bcm499', 'smartstore_2'),
('Valentino', 'https://www.valentino.com/en-fr/men/bags/shoulder-bags', '남성 - 가방 - 숄더백', '패션잡화>남성가방>숄더백', '50000646', NULL, NULL, 'bcm499', 'smartstore_2'),
('Valentino', 'https://www.valentino.com/en-fr/men/bags/backpacks', '남성 - 가방 - 백팩', '패션잡화>남성가방>백팩', '50000651', NULL, NULL, 'bcm499', 'smartstore_2'),
('Valentino', 'https://www.valentino.com/en-fr/men/bags/belt-bags', '남성 - 가방 - 벨트백', '패션잡화>남성가방>힙색/슬링백', '50000652', NULL, NULL, 'bcm499', 'smartstore_2'),
('Valentino', 'https://www.valentino.com/en-fr/men/bags/totes', '남성 - 가방 - 토트백', '패션잡화>남성가방>토트백', '50000647', NULL, NULL, 'bcm499', 'smartstore_2'),
('Valentino', 'https://www.valentino.com/en-fr/men/bags/clutches-and-pouches', '남성 - 가방 - 클러치 & 파우치', '패션잡화>남성가방>클러치백', '50000649', NULL, NULL, 'bcm499', 'smartstore_2'),
('Valentino', 'https://www.valentino.com/en-fr/men/shoes/sneakers', '남성 - 슈즈 - 스니커즈', '패션잡화>남성신발>스니커즈', '50000788', NULL, NULL, 'bcm499', 'smartstore_2'),
('Valentino', 'https://www.valentino.com/en-fr/men/shoes/sandals', '남성 - 슈즈 - 샌들 & 슬라이드', '패션잡화>남성신발>샌들', '50000789', NULL, NULL, 'bcm499', 'smartstore_2'),
('Valentino', 'https://www.valentino.com/en-fr/men/shoes/loafers-and-driver', '남성 - 슈즈 - 로퍼', '패션잡화>남성신발>구두', '50000787', NULL, NULL, 'bcm499', 'smartstore_2'),
('Valentino', 'https://www.valentino.com/en-fr/men/shoes/lace-ups', '남성 - 슈즈 - 레이스업', '패션잡화>남성신발>구두', '50000787', NULL, NULL, 'bcm499', 'smartstore_2'),
('Valentino', 'https://www.valentino.com/en-fr/men/shoes/boots', '남성 - 슈즈 - 부츠', '패션잡화>남성신발>부츠>앵클/숏부츠', '50021999', NULL, NULL, 'bcm499', 'smartstore_2'),
('Valentino', 'https://www.valentino.com/en-fr/men/accessories/wallets-and-card-holders', '남성 - 액세서리 - 지갑 & 카드홀더', '패션잡화>지갑>카드/명함지갑', '50000662', NULL, NULL, 'bcm499', 'smartstore_2'),
('Valentino', 'https://www.valentino.com/en-fr/men/accessories/belts', '남성 - 액세서리 - 벨트', '패션잡화>벨트>남성벨트>캐주얼벨트', '50003989', NULL, NULL, 'bcm499', 'smartstore_2'),
('Valentino', 'https://www.valentino.com/en-fr/men/accessories/ties', '남성 - 액세서리 - 타이', '패션잡화>패션소품>넥타이>기본넥타이', '50004014', NULL, NULL, 'bcm499', 'smartstore_2'),
('Valentino', 'https://www.valentino.com/en-fr/men/accessories/eyewear', '남성 - 액세서리 - 아이웨어', '패션잡화>선글라스/안경테>선글라스', '50000554', NULL, NULL, 'bcm499', 'smartstore_2')
ON CONFLICT (site, "siteUrl", "godoMallCategoryCode", "customId", "accountPlatform")
DO UPDATE SET
  "categoryName" = EXCLUDED."categoryName",
  "godoMallCategoryName" = EXCLUDED."godoMallCategoryName",
  designers = EXCLUDED.designers,
  "afterDesigners" = EXCLUDED."afterDesigners";
