INSERT INTO mapping (
  site,
  "siteUrl",
  "categoryName",
  "godoMallCategoryName",
  "godoMallCategoryCode",
  designers,
  "afterDesigners",
  "customId",
  "accountPlatform"
) VALUES
('YSL', 'https://www.ysl.com/en-de/ca/shop-women/shoes/flat-sandals', '여성 - SHOES - FLAT SANDALS', '패션잡화>여성신발>샌들>스트랩샌들', '50003842', NULL, NULL, 'bcm499', 'smartstore_2'),
('YSL', 'https://www.ysl.com/en-de/ca/shop-women/shoes/sneakers', '여성 - SHOES - SNEAKERS', '패션잡화>여성신발>단화>스니커즈', '50003822', NULL, NULL, 'bcm499', 'smartstore_2'),
('YSL', 'https://www.ysl.com/en-de/ca/shop-women/ready-to-wear/outerwear', '여성 - READY TO WEAR - OUTERWEAR', '패션의류>여성의류>아우터>재킷', '50021360', NULL, NULL, 'bcm499', 'smartstore_2'),
('YSL', 'https://www.ysl.com/en-de/ca/shop-women/ready-to-wear/coats', '여성 - READY TO WEAR - COATS', '패션의류>여성의류>아우터>재킷', '50021360', NULL, NULL, 'bcm499', 'smartstore_2'),
('YSL', 'https://www.ysl.com/en-de/ca/shop-women/ready-to-wear/shirts-and-tops', '여성 - READY TO WEAR - SHIRTS AND TOPS', '패션의류>여성의류>블라우스/셔츠', '50000804', NULL, NULL, 'bcm499', 'smartstore_2'),
('YSL', 'https://www.ysl.com/en-de/ca/shop-women/ready-to-wear/knitwear', '여성 - READY TO WEAR - KNITWEAR', '패션의류>여성의류>니트>풀오버', '50021299', NULL, NULL, 'bcm499', 'smartstore_2'),
('YSL', 'https://www.ysl.com/en-de/ca/shop-women/ready-to-wear/jersey', '여성 - READY TO WEAR - JERSEY', '패션의류>여성의류>티셔츠', '50000803', NULL, NULL, 'bcm499', 'smartstore_2'),
('YSL', 'https://www.ysl.com/en-de/ca/shop-women/shoes/booties', '여성 - SHOES - BOOTIES', '패션잡화>여성신발>부츠>앵클/숏부츠', '50004191', NULL, NULL, 'bcm499', 'smartstore_2'),
('YSL', 'https://www.ysl.com/en-de/ca/shop-women/shoes/boots', '여성 - SHOES - BOOTS', '패션잡화>여성신발>부츠>앵클/숏부츠', '50004191', NULL, NULL, 'bcm499', 'smartstore_2'),
('YSL', 'https://www.ysl.com/en-de/ca/shop-women/shoes/pumps-and-slingbacks', '여성 - SHOES - PUMPS AND SLINGBACKS', '패션잡화>여성신발>힐/펌프스>펌프스', '50003830', NULL, NULL, 'bcm499', 'smartstore_2'),
('YSL', 'https://www.ysl.com/en-de/ca/shop-women/shoes/sandals', '여성 - SHOES - SANDALS', '패션잡화>여성신발>샌들>스트랩샌들', '50003842', NULL, NULL, 'bcm499', 'smartstore_2'),
('YSL', 'https://www.ysl.com/en-de/ca/shop-women/shoes/mules-and-wedges', '여성 - SHOES - MULES', '패션잡화>여성신발>샌들>뮬/블로퍼', '50003847', NULL, NULL, 'bcm499', 'smartstore_2'),
('YSL', 'https://www.ysl.com/en-de/ca/shop-women/shoes/flats-and-loafers', '여성 - SHOES - LOAFERS', '패션잡화>여성신발>단화>로퍼', '50003818', NULL, NULL, 'bcm499', 'smartstore_2'),
('YSL', 'https://www.ysl.com/en-de/ca/shop-women/shoes/ballerinas', '여성 - SHOES - BALLERINAS', '패션잡화>여성신발>단화>플랫', '50003817', NULL, NULL, 'bcm499', 'smartstore_2'),
('YSL', 'https://www.ysl.com/en-de/ca/shop-women/handbags/shoulder-bags', '여성 - HANDBAGS - SHOULDER BAGS', '패션잡화>여성가방>숄더백', '50000639', NULL, NULL, 'bcm499', 'smartstore_2'),
('YSL', 'https://www.ysl.com/en-de/ca/shop-women/handbags/crossbody-bags', '여성 - HANDBAGS - CROSSBODY BAGS', '패션잡화>여성가방>크로스백', '50000641', NULL, NULL, 'bcm499', 'smartstore_2'),
('YSL', 'https://www.ysl.com/en-de/ca/shop-women/handbags/top-handles', '여성 - HANDBAGS - TOP HANDLES', '패션잡화>여성가방>토트백', '50000640', NULL, NULL, 'bcm499', 'smartstore_2'),
('YSL', 'https://www.ysl.com/en-de/ca/shop-women/handbags/hobos-and-buckets', '여성 - HANDBAGS - HOBOS', '패션잡화>여성가방>숄더백', '50000639', NULL, NULL, 'bcm499', 'smartstore_2'),
('YSL', 'https://www.ysl.com/en-de/ca/shop-women/handbags/buckets', '여성 - HANDBAGS - BUCKETS', '패션잡화>여성가방>숄더백', '50000639', NULL, NULL, 'bcm499', 'smartstore_2'),
('YSL', 'https://www.ysl.com/en-de/ca/shop-women/handbags/clutches-and-evening', '여성 - HANDBAGS - CLUTCHES AND EVENING', '패션잡화>여성가방>클러치백', '50000642', NULL, NULL, 'bcm499', 'smartstore_2'),
('YSL', 'https://www.ysl.com/en-de/ca/shop-women/handbags/totes', '여성 - HANDBAGS - TOTES', '패션잡화>여성가방>토트백', '50000640', NULL, NULL, 'bcm499', 'smartstore_2'),
('YSL', 'https://www.ysl.com/en-de/ca/shop-women/small-leather-goods/pouches', '여성 - SMALL LEATHER GOODS - POUCHES', '패션잡화>여성가방>파우치', '50000643', NULL, NULL, 'bcm499', 'smartstore_2'),
('YSL', 'https://www.ysl.com/en-de/ca/shop-women/small-leather-goods/wallets', '여성 - SMALL LEATHER GOODS - WALLETS', '패션잡화>지갑>여성지갑>반지갑', '50003982', NULL, NULL, 'bcm499', 'smartstore_2'),
('YSL', 'https://www.ysl.com/en-de/ca/shop-women/small-leather-goods/card-cases', '여성 - SMALL LEATHER GOODS - CARD CASES', '패션잡화>지갑>카드/명함지갑', '50000662', NULL, NULL, 'bcm499', 'smartstore_2'),
('YSL', 'https://www.ysl.com/en-de/ca/shop-women/accessories/belts', '여성 - ACCESSORIES - BELTS', '패션잡화>벨트>여성벨트', '50000539', NULL, NULL, 'bcm499', 'smartstore_2'),
('YSL', 'https://www.ysl.com/en-de/ca/shop-women/accessories/sunglasses', '여성 - ACCESSORIES - SUNGLASSES', '패션잡화>선글라스/안경테>선글라스', '50000554', NULL, NULL, 'bcm499', 'smartstore_2'),
('YSL', 'https://www.ysl.com/en-de/ca/shop-women/accessories/hats', '여성 - ACCESSORIES - HATS', '패션잡화>모자>사파리모자', '50000546', NULL, NULL, 'bcm499', 'smartstore_2'),
('YSL', 'https://www.ysl.com/en-de/ca/shop-women/accessories/scarves-and-silk', '여성 - ACCESSORIES - SCARVES AND SILK', '패션잡화>패션소품>스카프>롱', '50004010', NULL, NULL, 'bcm499', 'smartstore_2'),
('YSL', 'https://www.ysl.com/en-de/ca/shop-women/jewelry/cuffs-and-bracelets', '여성 - JEWELRY - CUFFS AND BRACELETS', '패션잡화>주얼리>팔찌>패션팔찌', '50004194', NULL, NULL, 'bcm499', 'smartstore_2'),
('YSL', 'https://www.ysl.com/en-de/ca/shop-women/jewelry/earrings', '여성 - JEWELRY - EARRINGS', '패션잡화>주얼리>귀걸이>패션귀걸이', '50004164', NULL, NULL, 'bcm499', 'smartstore_2'),
('YSL', 'https://www.ysl.com/en-de/ca/shop-women/jewelry/necklaces', '여성 - JEWELRY - NECKLACES', '패션잡화>주얼리>목걸이>패션목걸이', '50004174', NULL, NULL, 'bcm499', 'smartstore_2'),
('YSL', 'https://www.ysl.com/en-de/ca/shop-men/ready-to-wear/outerwear', '남성 - READY TO WEAR - OUTERWEAR', '패션의류>남성의류>아우터>재킷', '50021640', NULL, NULL, 'bcm499', 'smartstore_2'),
('YSL', 'https://www.ysl.com/en-de/ca/shop-men/ready-to-wear/coats-and-trench', '남성 - READY TO WEAR - COATS AND TRENCH', '패션의류>남성의류>아우터>재킷', '50021640', NULL, NULL, 'bcm499', 'smartstore_2'),
('YSL', 'https://www.ysl.com/en-de/ca/shop-men/ready-to-wear/shirts', '남성 - READY TO WEAR - SHIRTS', '패션의류>남성의류>셔츠/남방', '50000833', NULL, NULL, 'bcm499', 'smartstore_2'),
('YSL', 'https://www.ysl.com/en-de/ca/shop-men/ready-to-wear/knitwear', '남성 - READY TO WEAR - KNITWEAR', '패션의류>남성의류>니트>풀오버', '50021579', NULL, NULL, 'bcm499', 'smartstore_2'),
('YSL', 'https://www.ysl.com/en-de/ca/shop-men/ready-to-wear/jersey', '남성 - READY TO WEAR - JERSEY', '패션의류>남성의류>티셔츠', '50000830', NULL, NULL, 'bcm499', 'smartstore_2'),
('YSL', 'https://www.ysl.com/en-de/ca/shop-men/shoes/loafers', '남성 - SHOES - LOAFERS', '패션잡화>남성신발>구두', '50000787', NULL, NULL, 'bcm499', 'smartstore_2'),
('YSL', 'https://www.ysl.com/en-de/ca/shop-men/shoes/boots', '남성 - SHOES - BOOTS', '패션잡화>남성신발>부츠>앵클/숏부츠', '50021999', NULL, NULL, 'bcm499', 'smartstore_2'),
('YSL', 'https://www.ysl.com/en-de/ca/shop-men/shoes/derbies', '남성 - SHOES - DERBIES', '패션잡화>남성신발>구두', '50000787', NULL, NULL, 'bcm499', 'smartstore_2'),
('YSL', 'https://www.ysl.com/en-de/ca/shop-men/shoes/sandals', '남성 - SHOES - SANDALS', '패션잡화>남성신발>샌들', '50000789', NULL, NULL, 'bcm499', 'smartstore_2'),
('YSL', 'https://www.ysl.com/en-de/ca/shop-men/shoes/sneakers', '남성 - SHOES - SNEAKERS', '패션잡화>남성신발>스니커즈', '50000788', NULL, NULL, 'bcm499', 'smartstore_2'),
('YSL', 'https://www.ysl.com/en-de/ca/shop-men/bags/messengers', '남성 - BAGS - MESSENGERS', '패션잡화>남성가방>크로스백', '50000648', NULL, NULL, 'bcm499', 'smartstore_2'),
('YSL', 'https://www.ysl.com/en-de/ca/shop-men/bags/backpacks', '남성 - BAGS - BACKPACKS', '패션잡화>남성가방>백팩', '50000651', NULL, NULL, 'bcm499', 'smartstore_2'),
('YSL', 'https://www.ysl.com/en-de/ca/shop-men/bags/totes', '남성 - BAGS - TOTES', '패션잡화>남성가방>토트백', '50000647', NULL, NULL, 'bcm499', 'smartstore_2'),
('YSL', 'https://www.ysl.com/en-de/ca/shop-men/bags/briefcases', '남성 - BAGS - BRIEFCASES', '패션잡화>남성가방>브리프케이스', '50000650', NULL, NULL, 'bcm499', 'smartstore_2'),
('YSL', 'https://www.ysl.com/en-de/ca/shop-men/small-leather-goods/card-cases', '남성 - SMALL LEATHER GOODS - CARD CASES', '패션잡화>지갑>카드/명함지갑', '50000662', NULL, NULL, 'bcm499', 'smartstore_2'),
('YSL', 'https://www.ysl.com/en-de/ca/shop-men/small-leather-goods/wallets', '남성 - SMALL LEATHER GOODS - WALLETS', '패션잡화>지갑>남성지갑>반지갑', '50003985', NULL, NULL, 'bcm499', 'smartstore_2'),
('YSL', 'https://www.ysl.com/en-de/ca/shop-men/small-leather-goods/pouches', '남성 - SMALL LEATHER GOODS - POUCHES', '패션잡화>남성가방>클러치백', '50000649', NULL, NULL, 'bcm499', 'smartstore_2'),
('YSL', 'https://www.ysl.com/en-de/ca/shop-men/accessories/belts', '남성 - ACCESSORIES - BELTS', '패션잡화>벨트>남성벨트>캐주얼벨트', '50003989', NULL, NULL, 'bcm499', 'smartstore_2'),
('YSL', 'https://www.ysl.com/en-de/ca/shop-men/accessories/sunglasses', '남성 - ACCESSORIES - SUNGLASSES', '패션잡화>선글라스/안경테>선글라스', '50000554', NULL, NULL, 'bcm499', 'smartstore_2'),
('YSL', 'https://www.ysl.com/en-de/ca/shop-men/accessories/scarves-and-ties', '남성 - ACCESSORIES - TIES AND SILK', '패션잡화>패션소품>스카프>롱', '50004010', NULL, NULL, 'bcm499', 'smartstore_2');
